// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_credentials.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserAICredential = `-- name: DeleteUserAICredential :exec
DELETE FROM user_ai_credentials WHERE user_id = $1 AND provider = $2
`

type DeleteUserAICredentialParams struct {
	UserID   pgtype.UUID
	Provider string
}

func (q *Queries) DeleteUserAICredential(ctx context.Context, arg DeleteUserAICredentialParams) error {
	_, err := q.db.Exec(ctx, deleteUserAICredential, arg.UserID, arg.Provider)
	return err
}

const getUserAICredential = `-- name: GetUserAICredential :one
SELECT id, user_id, provider, api_key_enc, created_at, updated_at FROM user_ai_credentials WHERE user_id = $1 AND provider = $2 LIMIT 1
`

type GetUserAICredentialParams struct {
	UserID   pgtype.UUID
	Provider string
}

func (q *Queries) GetUserAICredential(ctx context.Context, arg GetUserAICredentialParams) (UserAiCredential, error) {
	row := q.db.QueryRow(ctx, getUserAICredential, arg.UserID, arg.Provider)
	var i UserAiCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ApiKeyEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAICredentialProviders = `-- name: ListUserAICredentialProviders :many
SELECT provider FROM user_ai_credentials WHERE user_id = $1 ORDER BY provider
`

func (q *Queries) ListUserAICredentialProviders(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserAICredentialProviders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserAICredential = `-- name: UpsertUserAICredential :one
INSERT INTO user_ai_credentials (user_id, provider, api_key_enc)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, provider) DO UPDATE SET
    api_key_enc = EXCLUDED.api_key_enc,
    updated_at  = now()
RETURNING id, user_id, provider, api_key_enc, created_at, updated_at
`

type UpsertUserAICredentialParams struct {
	UserID    pgtype.UUID
	Provider  string
	ApiKeyEnc string
}

func (q *Queries) UpsertUserAICredential(ctx context.Context, arg UpsertUserAICredentialParams) (UserAiCredential, error) {
	row := q.db.QueryRow(ctx, upsertUserAICredential, arg.UserID, arg.Provider, arg.ApiKeyEnc)
	var i UserAiCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ApiKeyEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
