// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (user_id, job_id, status_id, notes, applied_at, salary_info)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, job_id, status_id, notes, applied_at, salary_info, created_at, updated_at
`

type CreateApplicationParams struct {
	UserID     pgtype.UUID
	JobID      pgtype.UUID
	StatusID   pgtype.UUID
	Notes      pgtype.Text
	AppliedAt  pgtype.Date
	SalaryInfo pgtype.Text
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.UserID,
		arg.JobID,
		arg.StatusID,
		arg.Notes,
		arg.AppliedAt,
		arg.SalaryInfo,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.StatusID,
		&i.Notes,
		&i.AppliedAt,
		&i.SalaryInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = $1 AND user_id = $2
`

type DeleteApplicationParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteApplication(ctx context.Context, arg DeleteApplicationParams) error {
	_, err := q.db.Exec(ctx, deleteApplication, arg.ID, arg.UserID)
	return err
}

const getApplicationByUserAndJob = `-- name: GetApplicationByUserAndJob :one
SELECT
    a.id, a.user_id, a.job_id, a.status_id,
    a.notes, a.applied_at, a.salary_info, a.created_at, a.updated_at,
    s.name   AS status_name,
    s.colour AS status_colour
FROM applications a
LEFT JOIN application_statuses s ON a.status_id = s.id
WHERE a.user_id = $1 AND a.job_id = $2
`

type GetApplicationByUserAndJobParams struct {
	UserID pgtype.UUID
	JobID  pgtype.UUID
}

type GetApplicationByUserAndJobRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	JobID        pgtype.UUID
	StatusID     pgtype.UUID
	Notes        pgtype.Text
	AppliedAt    pgtype.Date
	SalaryInfo   pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	StatusName   pgtype.Text
	StatusColour pgtype.Text
}

func (q *Queries) GetApplicationByUserAndJob(ctx context.Context, arg GetApplicationByUserAndJobParams) (GetApplicationByUserAndJobRow, error) {
	row := q.db.QueryRow(ctx, getApplicationByUserAndJob, arg.UserID, arg.JobID)
	var i GetApplicationByUserAndJobRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.StatusID,
		&i.Notes,
		&i.AppliedAt,
		&i.SalaryInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusName,
		&i.StatusColour,
	)
	return i, err
}

const getApplicationsForJobs = `-- name: GetApplicationsForJobs :many
SELECT
    a.job_id,
    a.id,
    a.status_id,
    s.name   AS status_name,
    s.colour AS status_colour
FROM applications a
LEFT JOIN application_statuses s ON a.status_id = s.id
WHERE a.user_id = $1 AND a.job_id = ANY($2::uuid[])
`

type GetApplicationsForJobsParams struct {
	UserID  pgtype.UUID
	Column2 []pgtype.UUID
}

type GetApplicationsForJobsRow struct {
	JobID        pgtype.UUID
	ID           pgtype.UUID
	StatusID     pgtype.UUID
	StatusName   pgtype.Text
	StatusColour pgtype.Text
}

func (q *Queries) GetApplicationsForJobs(ctx context.Context, arg GetApplicationsForJobsParams) ([]GetApplicationsForJobsRow, error) {
	rows, err := q.db.Query(ctx, getApplicationsForJobs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplicationsForJobsRow
	for rows.Next() {
		var i GetApplicationsForJobsRow
		if err := rows.Scan(
			&i.JobID,
			&i.ID,
			&i.StatusID,
			&i.StatusName,
			&i.StatusColour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByUser = `-- name: ListApplicationsByUser :many
SELECT
    a.id, a.user_id, a.job_id, a.status_id,
    a.notes, a.applied_at, a.salary_info, a.created_at, a.updated_at,
    j.title        AS job_title,
    j.company_slug AS job_company_slug,
    j.location     AS job_location,
    j.url          AS job_url,
    s.name         AS status_name,
    s.colour       AS status_colour
FROM applications a
JOIN jobs j ON a.job_id = j.id
LEFT JOIN application_statuses s ON a.status_id = s.id
WHERE a.user_id = $1
ORDER BY a.updated_at DESC
`

type ListApplicationsByUserRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	JobID          pgtype.UUID
	StatusID       pgtype.UUID
	Notes          pgtype.Text
	AppliedAt      pgtype.Date
	SalaryInfo     pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	JobTitle       string
	JobCompanySlug string
	JobLocation    string
	JobUrl         string
	StatusName     pgtype.Text
	StatusColour   pgtype.Text
}

func (q *Queries) ListApplicationsByUser(ctx context.Context, userID pgtype.UUID) ([]ListApplicationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsByUserRow
	for rows.Next() {
		var i ListApplicationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.StatusID,
			&i.Notes,
			&i.AppliedAt,
			&i.SalaryInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
			&i.JobCompanySlug,
			&i.JobLocation,
			&i.JobUrl,
			&i.StatusName,
			&i.StatusColour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByUserAndStatus = `-- name: ListApplicationsByUserAndStatus :many
SELECT
    a.id, a.user_id, a.job_id, a.status_id,
    a.notes, a.applied_at, a.salary_info, a.created_at, a.updated_at,
    j.title        AS job_title,
    j.company_slug AS job_company_slug,
    j.location     AS job_location,
    j.url          AS job_url,
    s.name         AS status_name,
    s.colour       AS status_colour
FROM applications a
JOIN jobs j ON a.job_id = j.id
LEFT JOIN application_statuses s ON a.status_id = s.id
WHERE a.user_id = $1 AND a.status_id = $2
ORDER BY a.updated_at DESC
`

type ListApplicationsByUserAndStatusParams struct {
	UserID   pgtype.UUID
	StatusID pgtype.UUID
}

type ListApplicationsByUserAndStatusRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	JobID          pgtype.UUID
	StatusID       pgtype.UUID
	Notes          pgtype.Text
	AppliedAt      pgtype.Date
	SalaryInfo     pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	JobTitle       string
	JobCompanySlug string
	JobLocation    string
	JobUrl         string
	StatusName     pgtype.Text
	StatusColour   pgtype.Text
}

func (q *Queries) ListApplicationsByUserAndStatus(ctx context.Context, arg ListApplicationsByUserAndStatusParams) ([]ListApplicationsByUserAndStatusRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByUserAndStatus, arg.UserID, arg.StatusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsByUserAndStatusRow
	for rows.Next() {
		var i ListApplicationsByUserAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.StatusID,
			&i.Notes,
			&i.AppliedAt,
			&i.SalaryInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
			&i.JobCompanySlug,
			&i.JobLocation,
			&i.JobUrl,
			&i.StatusName,
			&i.StatusColour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET status_id = $3, notes = $4, applied_at = $5, salary_info = $6, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, job_id, status_id, notes, applied_at, salary_info, created_at, updated_at
`

type UpdateApplicationParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	StatusID   pgtype.UUID
	Notes      pgtype.Text
	AppliedAt  pgtype.Date
	SalaryInfo pgtype.Text
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.UserID,
		arg.StatusID,
		arg.Notes,
		arg.AppliedAt,
		arg.SalaryInfo,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.StatusID,
		&i.Notes,
		&i.AppliedAt,
		&i.SalaryInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
