// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package pgsqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertJobs = `-- name: UpsertJobs :batchexec
INSERT INTO jobs (title, location, url, company_slug, source, updated_at, scraped_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (url) DO UPDATE SET
    title      = EXCLUDED.title,
    location   = EXCLUDED.location,
    updated_at = EXCLUDED.updated_at,
    scraped_at = NOW()
`

type UpsertJobsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertJobsParams struct {
	Title       string
	Location    string
	Url         string
	CompanySlug string
	Source      string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertJobs(ctx context.Context, arg []UpsertJobsParams) *UpsertJobsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Title,
			a.Location,
			a.Url,
			a.CompanySlug,
			a.Source,
			a.UpdatedAt,
		}
		batch.Queue(upsertJobs, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertJobsBatchResults{br, len(arg), false}
}

func (b *UpsertJobsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertJobsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
