// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompany = `-- name: GetCompany :one
SELECT id, slug, name, ats_source, ats_token, first_seen_at, created_at, updated_at FROM companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.AtsSource,
		&i.AtsToken,
		&i.FirstSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompaniesForUser = `-- name: ListCompaniesForUser :many
SELECT c.id, c.slug, c.name, c.ats_source, c.ats_token, c.first_seen_at,
    (SELECT COUNT(*) FROM jobs j WHERE j.company_slug = c.slug) AS job_count,
    st.id AS target_id,
    COALESCE(st.enabled, FALSE) AS tracked,
    st.check_interval_minutes,
    st.last_checked_at
FROM companies c
LEFT JOIN source_targets st
    ON st.user_id = $1 AND st.source = c.ats_source AND st.value = c.ats_token
ORDER BY c.name
`

type ListCompaniesForUserRow struct {
	ID                   pgtype.UUID
	Slug                 string
	Name                 string
	AtsSource            pgtype.Text
	AtsToken             pgtype.Text
	FirstSeenAt          pgtype.Timestamptz
	JobCount             int64
	TargetID             pgtype.UUID
	Tracked              bool
	CheckIntervalMinutes pgtype.Int4
	LastCheckedAt        pgtype.Timestamptz
}

func (q *Queries) ListCompaniesForUser(ctx context.Context, userID pgtype.UUID) ([]ListCompaniesForUserRow, error) {
	rows, err := q.db.Query(ctx, listCompaniesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesForUserRow
	for rows.Next() {
		var i ListCompaniesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.AtsSource,
			&i.AtsToken,
			&i.FirstSeenAt,
			&i.JobCount,
			&i.TargetID,
			&i.Tracked,
			&i.CheckIntervalMinutes,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompany = `-- name: UpsertCompany :one
INSERT INTO companies (slug, name, ats_source, ats_token)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE SET
    ats_source = COALESCE(companies.ats_source, EXCLUDED.ats_source),
    ats_token  = COALESCE(companies.ats_token,  EXCLUDED.ats_token),
    updated_at = NOW()
RETURNING id, slug, name, ats_source, ats_token, first_seen_at, created_at, updated_at
`

type UpsertCompanyParams struct {
	Slug      string
	Name      string
	AtsSource pgtype.Text
	AtsToken  pgtype.Text
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, upsertCompany,
		arg.Slug,
		arg.Name,
		arg.AtsSource,
		arg.AtsToken,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.AtsSource,
		&i.AtsToken,
		&i.FirstSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
