// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_boards.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCompanyBoards = `-- name: ListCompanyBoards :many
SELECT id, company_id, source, board_token, status, verification_method, verified_at, last_linked_at, retired_at, superseded_at, created_at FROM company_boards WHERE company_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListCompanyBoards(ctx context.Context, companyID pgtype.UUID) ([]CompanyBoard, error) {
	rows, err := q.db.Query(ctx, listCompanyBoards, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyBoard
	for rows.Next() {
		var i CompanyBoard
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Source,
			&i.BoardToken,
			&i.Status,
			&i.VerificationMethod,
			&i.VerifiedAt,
			&i.LastLinkedAt,
			&i.RetiredAt,
			&i.SupersededAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCandidateBoard = `-- name: UpsertCandidateBoard :one
INSERT INTO company_boards (company_id, source, board_token)
VALUES ($1, $2, $3)
ON CONFLICT (source, board_token) DO UPDATE SET source = EXCLUDED.source
WHERE company_boards.company_id = EXCLUDED.company_id
RETURNING id, company_id, source, board_token, status, verification_method, verified_at, last_linked_at, retired_at, superseded_at, created_at
`

type UpsertCandidateBoardParams struct {
	CompanyID  pgtype.UUID
	Source     string
	BoardToken string
}

func (q *Queries) UpsertCandidateBoard(ctx context.Context, arg UpsertCandidateBoardParams) (CompanyBoard, error) {
	row := q.db.QueryRow(ctx, upsertCandidateBoard, arg.CompanyID, arg.Source, arg.BoardToken)
	var i CompanyBoard
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.BoardToken,
		&i.Status,
		&i.VerificationMethod,
		&i.VerifiedAt,
		&i.LastLinkedAt,
		&i.RetiredAt,
		&i.SupersededAt,
		&i.CreatedAt,
	)
	return i, err
}

const verifyCompanyBoard = `-- name: VerifyCompanyBoard :one
UPDATE company_boards
SET status = 'verified', verification_method = $4, verified_at = NOW()
WHERE company_id = $1 AND source = $2 AND board_token = $3 AND status = 'candidate'
RETURNING id, company_id, source, board_token, status, verification_method, verified_at, last_linked_at, retired_at, superseded_at, created_at
`

type VerifyCompanyBoardParams struct {
	CompanyID          pgtype.UUID
	Source             string
	BoardToken         string
	VerificationMethod pgtype.Text
}

func (q *Queries) VerifyCompanyBoard(ctx context.Context, arg VerifyCompanyBoardParams) (CompanyBoard, error) {
	row := q.db.QueryRow(ctx, verifyCompanyBoard,
		arg.CompanyID,
		arg.Source,
		arg.BoardToken,
		arg.VerificationMethod,
	)
	var i CompanyBoard
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.BoardToken,
		&i.Status,
		&i.VerificationMethod,
		&i.VerifiedAt,
		&i.LastLinkedAt,
		&i.RetiredAt,
		&i.SupersededAt,
		&i.CreatedAt,
	)
	return i, err
}
