// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: effect_outbox.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backfillCompanyJobFingerprints = `-- name: BackfillCompanyJobFingerprints :exec
UPDATE jobs j SET content_fingerprint = encode(sha256(convert_to(
    replace(replace(replace(replace(replace(to_json(ARRAY[
        j.title, j.description, j.location, j.salary_raw, j.work_arrangement
    ])::text,
    '&', chr(92) || 'u0026'), '<', chr(92) || 'u003c'),
    '>', chr(92) || 'u003e'), chr(8232), chr(92) || 'u2028'),
    chr(8233), chr(92) || 'u2029'), 'UTF8')), 'hex')
FROM companies c
WHERE c.id = $1::uuid AND (j.company_id = c.id OR j.company_slug = c.slug)
    AND j.closed_at IS NULL AND j.content_fingerprint IS NULL
`

func (q *Queries) BackfillCompanyJobFingerprints(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, backfillCompanyJobFingerprints, dollar_1)
	return err
}

const claimScoringEffect = `-- name: ClaimScoringEffect :one
WITH next AS (
    SELECT id FROM effect_outbox
    WHERE (status = 'pending' AND due_at <= NOW())
       OR (status = 'running' AND lease_until <= NOW())
    ORDER BY due_at, id LIMIT 1 FOR UPDATE SKIP LOCKED
)
UPDATE effect_outbox e SET status = 'running', attempts = attempts + 1,
    lease_until = NOW() + interval '5 minutes'
FROM next WHERE e.id = next.id
RETURNING e.id, e.job_id, e.user_id, e.fingerprint, e.config_version, e.model, e.attempts, e.first_discovery
`

type ClaimScoringEffectRow struct {
	ID             pgtype.UUID
	JobID          pgtype.UUID
	UserID         pgtype.UUID
	Fingerprint    string
	ConfigVersion  pgtype.Timestamptz
	Model          string
	Attempts       int32
	FirstDiscovery bool
}

func (q *Queries) ClaimScoringEffect(ctx context.Context) (ClaimScoringEffectRow, error) {
	row := q.db.QueryRow(ctx, claimScoringEffect)
	var i ClaimScoringEffectRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.Fingerprint,
		&i.ConfigVersion,
		&i.Model,
		&i.Attempts,
		&i.FirstDiscovery,
	)
	return i, err
}

const completeScoringEffect = `-- name: CompleteScoringEffect :execrows
WITH completed AS (
    UPDATE effect_outbox SET status = 'done', lease_until = NULL, last_error = ''
    WHERE id = $5::uuid AND attempts = $6::int AND status = 'running'
    RETURNING job_id, user_id, fingerprint, config_version, model
)
INSERT INTO job_scores (job_id, user_id, suitability_score, reasoning, matched, missing,
    suitability_skipped, score_fingerprint, score_config_version, score_model)
SELECT e.job_id, e.user_id, $1::int, $2::text,
    $3::text[], $4::text[], false,
    e.fingerprint, e.config_version, e.model
FROM completed e JOIN jobs j ON j.id = e.job_id
LEFT JOIN search_config sc ON sc.user_id = e.user_id
LEFT JOIN user_ai_prefs p ON p.user_id = e.user_id
WHERE j.content_fingerprint = e.fingerprint
    AND COALESCE(sc.updated_at, 'epoch'::timestamptz) = e.config_version
    AND COALESCE(p.suitability_model, 'claude-haiku-4-5-20251001') = e.model
ON CONFLICT (job_id, user_id) DO UPDATE SET
    suitability_score = EXCLUDED.suitability_score, reasoning = EXCLUDED.reasoning,
    matched = EXCLUDED.matched, missing = EXCLUDED.missing, suitability_skipped = false,
    score_fingerprint = EXCLUDED.score_fingerprint,
    score_config_version = EXCLUDED.score_config_version, score_model = EXCLUDED.score_model,
    updated_at = NOW()
`

type CompleteScoringEffectParams struct {
	Score     int32
	Reasoning string
	Matched   []string
	Missing   []string
	ID        pgtype.UUID
	Attempts  int32
}

func (q *Queries) CompleteScoringEffect(ctx context.Context, arg CompleteScoringEffectParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeScoringEffect,
		arg.Score,
		arg.Reasoning,
		arg.Matched,
		arg.Missing,
		arg.ID,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failScoringEffect = `-- name: FailScoringEffect :exec
UPDATE effect_outbox SET
    status = CASE WHEN attempts >= 8 THEN 'failed' ELSE 'pending' END,
    due_at = NOW() + make_interval(secs => LEAST(3600, 30 * power(2, attempts)::int)),
    lease_until = NULL,
    last_error = $1::text
WHERE id = $2::uuid AND attempts = $3::int AND status = 'running'
`

type FailScoringEffectParams struct {
	LastError string
	ID        pgtype.UUID
	Attempts  int32
}

func (q *Queries) FailScoringEffect(ctx context.Context, arg FailScoringEffectParams) error {
	_, err := q.db.Exec(ctx, failScoringEffect, arg.LastError, arg.ID, arg.Attempts)
	return err
}

const findInterestedUsers = `-- name: FindInterestedUsers :many
SELECT u.id AS user_id,
    COALESCE(sc.excluded_title_keywords, '{}')::text[] AS excluded_title_keywords,
    COALESCE(sc.excluded_companies, '{}')::text[] AS excluded_companies,
    COALESCE(sc.excluded_seniority, '{}')::text[] AS excluded_seniority,
    COALESCE(sc.excluded_locations, '{}')::text[] AS excluded_locations,
    COALESCE(sc.updated_at, 'epoch'::timestamptz) AS config_version,
    COALESCE(p.suitability_model, 'claude-haiku-4-5-20251001') AS model
FROM users u
LEFT JOIN search_config sc ON sc.user_id = u.id
LEFT JOIN user_ai_prefs p ON p.user_id = u.id
WHERE EXISTS (
    SELECT 1 FROM tracked_companies tc JOIN companies c ON c.id = tc.company_id
    WHERE tc.user_id = u.id AND tc.enabled AND
        (c.id = $1::uuid OR c.slug = $2::text)
) OR EXISTS (
    SELECT 1 FROM source_targets st WHERE st.user_id = u.id AND st.enabled
        AND st.source = $3::text
        AND ($4::boolean OR st.value = $2::text)
)
`

type FindInterestedUsersParams struct {
	CompanyID   pgtype.UUID
	CompanySlug string
	Source      string
	Discovery   bool
}

type FindInterestedUsersRow struct {
	UserID                pgtype.UUID
	ExcludedTitleKeywords []string
	ExcludedCompanies     []string
	ExcludedSeniority     []string
	ExcludedLocations     []string
	ConfigVersion         pgtype.Timestamptz
	Model                 string
}

func (q *Queries) FindInterestedUsers(ctx context.Context, arg FindInterestedUsersParams) ([]FindInterestedUsersRow, error) {
	rows, err := q.db.Query(ctx, findInterestedUsers,
		arg.CompanyID,
		arg.CompanySlug,
		arg.Source,
		arg.Discovery,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindInterestedUsersRow
	for rows.Next() {
		var i FindInterestedUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.ExcludedTitleKeywords,
			&i.ExcludedCompanies,
			&i.ExcludedSeniority,
			&i.ExcludedLocations,
			&i.ConfigVersion,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoringStatus = `-- name: GetScoringStatus :one
SELECT
    (SELECT count(*) FROM effect_outbox WHERE user_id = $1::uuid AND status IN ('pending', 'running')) AS pending,
    (SELECT count(*) FROM effect_outbox WHERE user_id = $1::uuid AND status = 'failed') AS failed,
    (SELECT count(*) FROM job_scores s JOIN jobs j ON j.id = s.job_id
        LEFT JOIN search_config sc ON sc.user_id = s.user_id
        LEFT JOIN user_ai_prefs p ON p.user_id = s.user_id
        WHERE s.user_id = $1::uuid AND
            (s.score_fingerprint IS DISTINCT FROM j.content_fingerprint OR
             s.score_config_version IS DISTINCT FROM COALESCE(sc.updated_at, 'epoch'::timestamptz) OR
             s.score_model IS DISTINCT FROM COALESCE(p.suitability_model, 'claude-haiku-4-5-20251001'))) AS stale
`

type GetScoringStatusRow struct {
	Pending int64
	Failed  int64
	Stale   int64
}

func (q *Queries) GetScoringStatus(ctx context.Context, userID pgtype.UUID) (GetScoringStatusRow, error) {
	row := q.db.QueryRow(ctx, getScoringStatus, userID)
	var i GetScoringStatusRow
	err := row.Scan(&i.Pending, &i.Failed, &i.Stale)
	return i, err
}

const insertScoringEffect = `-- name: InsertScoringEffect :exec
INSERT INTO effect_outbox (job_id, user_id, fingerprint, config_version, model, first_discovery)
VALUES ($1::uuid, $2::uuid, $3::text,
    $4::timestamptz, $5::text, $6::boolean)
ON CONFLICT DO NOTHING
`

type InsertScoringEffectParams struct {
	JobID          pgtype.UUID
	UserID         pgtype.UUID
	Fingerprint    string
	ConfigVersion  pgtype.Timestamptz
	Model          string
	FirstDiscovery bool
}

func (q *Queries) InsertScoringEffect(ctx context.Context, arg InsertScoringEffectParams) error {
	_, err := q.db.Exec(ctx, insertScoringEffect,
		arg.JobID,
		arg.UserID,
		arg.Fingerprint,
		arg.ConfigVersion,
		arg.Model,
		arg.FirstDiscovery,
	)
	return err
}

const queueRescore = `-- name: QueueRescore :execrows
WITH interested AS (
    SELECT job_id FROM job_scores WHERE user_id = $1::uuid
    UNION
    SELECT job_id FROM effect_outbox WHERE user_id = $1::uuid
)
INSERT INTO effect_outbox (job_id, user_id, fingerprint, config_version, model)
SELECT j.id, $1::uuid, j.content_fingerprint,
    COALESCE(sc.updated_at, 'epoch'::timestamptz),
    COALESCE(p.suitability_model, 'claude-haiku-4-5-20251001')
FROM interested i JOIN jobs j ON j.id = i.job_id
LEFT JOIN search_config sc ON sc.user_id = $1::uuid
LEFT JOIN user_ai_prefs p ON p.user_id = $1::uuid
WHERE j.closed_at IS NULL
    AND j.content_fingerprint IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM effect_outbox e
        WHERE e.job_id = j.id AND e.user_id = $1::uuid
        AND e.fingerprint = j.content_fingerprint
        AND e.config_version = COALESCE(sc.updated_at, 'epoch'::timestamptz)
        AND e.model = COALESCE(p.suitability_model, 'claude-haiku-4-5-20251001'))
ORDER BY j.id LIMIT 100
ON CONFLICT DO NOTHING
`

func (q *Queries) QueueRescore(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, queueRescore, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queueTrackingScores = `-- name: QueueTrackingScores :exec
INSERT INTO effect_outbox (job_id, user_id, fingerprint, config_version, model)
SELECT j.id, $1::uuid, j.content_fingerprint,
    COALESCE(sc.updated_at, 'epoch'::timestamptz),
    COALESCE(p.suitability_model, 'claude-haiku-4-5-20251001')
FROM jobs j JOIN companies c ON c.id = $2::uuid
LEFT JOIN search_config sc ON sc.user_id = $1::uuid
LEFT JOIN user_ai_prefs p ON p.user_id = $1::uuid
WHERE j.closed_at IS NULL AND j.content_fingerprint IS NOT NULL
    AND (j.company_id = c.id OR j.company_slug = c.slug)
ON CONFLICT DO NOTHING
`

type QueueTrackingScoresParams struct {
	UserID    pgtype.UUID
	CompanyID pgtype.UUID
}

func (q *Queries) QueueTrackingScores(ctx context.Context, arg QueueTrackingScoresParams) error {
	_, err := q.db.Exec(ctx, queueTrackingScores, arg.UserID, arg.CompanyID)
	return err
}
