// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_scores.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJobScore = `-- name: GetJobScore :one
SELECT id, job_id, user_id, relevance_score, suitability_score, created_at, updated_at FROM job_scores WHERE job_id = $1 AND user_id = $2 LIMIT 1
`

type GetJobScoreParams struct {
	JobID  pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetJobScore(ctx context.Context, arg GetJobScoreParams) (JobScore, error) {
	row := q.db.QueryRow(ctx, getJobScore, arg.JobID, arg.UserID)
	var i JobScore
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.RelevanceScore,
		&i.SuitabilityScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertJobScoreRelevance = `-- name: UpsertJobScoreRelevance :exec
INSERT INTO job_scores (job_id, user_id, relevance_score)
VALUES ($1, $2, $3)
ON CONFLICT (job_id, user_id) DO UPDATE SET
    relevance_score = EXCLUDED.relevance_score,
    updated_at = NOW()
`

type UpsertJobScoreRelevanceParams struct {
	JobID          pgtype.UUID
	UserID         pgtype.UUID
	RelevanceScore pgtype.Int4
}

func (q *Queries) UpsertJobScoreRelevance(ctx context.Context, arg UpsertJobScoreRelevanceParams) error {
	_, err := q.db.Exec(ctx, upsertJobScoreRelevance, arg.JobID, arg.UserID, arg.RelevanceScore)
	return err
}

const upsertJobScoreSuitability = `-- name: UpsertJobScoreSuitability :exec
INSERT INTO job_scores (job_id, user_id, suitability_score)
VALUES ($1, $2, $3)
ON CONFLICT (job_id, user_id) DO UPDATE SET
    suitability_score = EXCLUDED.suitability_score,
    updated_at = NOW()
`

type UpsertJobScoreSuitabilityParams struct {
	JobID            pgtype.UUID
	UserID           pgtype.UUID
	SuitabilityScore pgtype.Int4
}

func (q *Queries) UpsertJobScoreSuitability(ctx context.Context, arg UpsertJobScoreSuitabilityParams) error {
	_, err := q.db.Exec(ctx, upsertJobScoreSuitability, arg.JobID, arg.UserID, arg.SuitabilityScore)
	return err
}
