// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_scores.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJobScore = `-- name: GetJobScore :one
SELECT id, job_id, user_id, relevance_score, suitability_score, reasoning, matched, missing, suitability_skipped, score_fingerprint, score_config_version, score_model, created_at, updated_at FROM job_scores WHERE job_id = $1 AND user_id = $2 LIMIT 1
`

type GetJobScoreParams struct {
	JobID  pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetJobScore(ctx context.Context, arg GetJobScoreParams) (JobScore, error) {
	row := q.db.QueryRow(ctx, getJobScore, arg.JobID, arg.UserID)
	var i JobScore
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.RelevanceScore,
		&i.SuitabilityScore,
		&i.Reasoning,
		&i.Matched,
		&i.Missing,
		&i.SuitabilitySkipped,
		&i.ScoreFingerprint,
		&i.ScoreConfigVersion,
		&i.ScoreModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertJobScoreSuitability = `-- name: UpsertJobScoreSuitability :exec
INSERT INTO job_scores (job_id, user_id, suitability_score, reasoning, matched, missing, suitability_skipped)
VALUES ($1, $2, $3, $4, $5, $6, false)
ON CONFLICT (job_id, user_id) DO UPDATE SET
    suitability_score   = EXCLUDED.suitability_score,
    reasoning           = EXCLUDED.reasoning,
    matched             = EXCLUDED.matched,
    missing             = EXCLUDED.missing,
    suitability_skipped = false,
    updated_at          = NOW()
`

type UpsertJobScoreSuitabilityParams struct {
	JobID            pgtype.UUID
	UserID           pgtype.UUID
	SuitabilityScore pgtype.Int4
	Reasoning        pgtype.Text
	Matched          []string
	Missing          []string
}

func (q *Queries) UpsertJobScoreSuitability(ctx context.Context, arg UpsertJobScoreSuitabilityParams) error {
	_, err := q.db.Exec(ctx, upsertJobScoreSuitability,
		arg.JobID,
		arg.UserID,
		arg.SuitabilityScore,
		arg.Reasoning,
		arg.Matched,
		arg.Missing,
	)
	return err
}
