// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const existingURLs = `-- name: ExistingURLs :many
SELECT url FROM jobs WHERE url = ANY($1::text[])
`

func (q *Queries) ExistingURLs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, existingURLs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at, j.description, j.salary_raw, j.work_arrangement, j.company_id, j.primary_board_id, j.provider_posting_id, j.content_fingerprint, js.suitability_score, js.breakdown
FROM jobs j
LEFT JOIN job_scores js ON js.job_id = j.id AND js.user_id = $2
WHERE j.id = $1
LIMIT 1
`

type GetJobParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetJobRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	Description        string
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	SuitabilityScore   pgtype.Int4
	Breakdown          []byte
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (GetJobRow, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.UserID)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.CompanySlug,
		&i.Source,
		&i.UpdatedAt,
		&i.ScrapedAt,
		&i.Description,
		&i.SalaryRaw,
		&i.WorkArrangement,
		&i.CompanyID,
		&i.PrimaryBoardID,
		&i.ProviderPostingID,
		&i.ContentFingerprint,
		&i.SuitabilityScore,
		&i.Breakdown,
	)
	return i, err
}

const getJobByURL = `-- name: GetJobByURL :one
SELECT id, title, location, url, company_slug, source, updated_at, scraped_at, description, salary_raw, work_arrangement, closed_at, company_id, primary_board_id, provider_posting_id, content_fingerprint, content_changed_at, first_discovered_at FROM jobs WHERE url = $1 LIMIT 1
`

func (q *Queries) GetJobByURL(ctx context.Context, url string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByURL, url)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.CompanySlug,
		&i.Source,
		&i.UpdatedAt,
		&i.ScrapedAt,
		&i.Description,
		&i.SalaryRaw,
		&i.WorkArrangement,
		&i.ClosedAt,
		&i.CompanyID,
		&i.PrimaryBoardID,
		&i.ProviderPostingID,
		&i.ContentFingerprint,
		&i.ContentChangedAt,
		&i.FirstDiscoveredAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at, j.salary_raw, j.work_arrangement, j.company_id, j.primary_board_id, j.provider_posting_id, j.content_fingerprint, js.suitability_score, js.breakdown
FROM jobs j
LEFT JOIN job_scores js ON js.job_id = j.id AND js.user_id = $1
WHERE j.closed_at IS NULL
ORDER BY COALESCE(js.suitability_score, -1) DESC, j.scraped_at DESC
`

type ListJobsRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	SuitabilityScore   pgtype.Int4
	Breakdown          []byte
}

func (q *Queries) ListJobs(ctx context.Context, userID pgtype.UUID) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
			&i.SalaryRaw,
			&i.WorkArrangement,
			&i.CompanyID,
			&i.PrimaryBoardID,
			&i.ProviderPostingID,
			&i.ContentFingerprint,
			&i.SuitabilityScore,
			&i.Breakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsSince = `-- name: ListJobsSince :many
SELECT id, title, location, url, company_slug, source, updated_at, scraped_at, description, salary_raw, work_arrangement, closed_at, company_id, primary_board_id, provider_posting_id, content_fingerprint, content_changed_at, first_discovered_at FROM jobs WHERE scraped_at > $1 ORDER BY scraped_at DESC
`

func (q *Queries) ListJobsSince(ctx context.Context, scrapedAt pgtype.Timestamptz) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsSince, scrapedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
			&i.Description,
			&i.SalaryRaw,
			&i.WorkArrangement,
			&i.ClosedAt,
			&i.CompanyID,
			&i.PrimaryBoardID,
			&i.ProviderPostingID,
			&i.ContentFingerprint,
			&i.ContentChangedAt,
			&i.FirstDiscoveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobsClosed = `-- name: MarkJobsClosed :exec
UPDATE jobs SET closed_at = NOW() WHERE url = ANY($1::text[]) AND closed_at IS NULL
`

func (q *Queries) MarkJobsClosed(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, markJobsClosed, dollar_1)
	return err
}

const openJobURLsForBoard = `-- name: OpenJobURLsForBoard :many
SELECT url FROM jobs WHERE source = $1 AND company_slug = $2 AND closed_at IS NULL
`

type OpenJobURLsForBoardParams struct {
	Source      string
	CompanySlug string
}

func (q *Queries) OpenJobURLsForBoard(ctx context.Context, arg OpenJobURLsForBoardParams) ([]string, error) {
	rows, err := q.db.Query(ctx, openJobURLsForBoard, arg.Source, arg.CompanySlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageJobs = `-- name: PageJobs :many
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at, j.salary_raw, j.work_arrangement, j.company_id, j.primary_board_id, j.provider_posting_id, j.content_fingerprint, js.suitability_score, js.breakdown
FROM jobs j
LEFT JOIN job_scores js ON js.job_id = j.id AND js.user_id = $1::uuid
WHERE ($2::timestamptz IS NULL OR (j.scraped_at, j.id) < ($2::timestamptz, $3::uuid))
  AND ($4::uuid IS NULL OR j.company_id = $4::uuid OR (j.company_id IS NULL AND j.company_slug = (SELECT slug FROM companies WHERE id = $4::uuid)))
  AND ($5::text = 'all' OR ($5::text = 'open' AND j.closed_at IS NULL) OR ($5::text = 'closed' AND j.closed_at IS NOT NULL))
ORDER BY j.scraped_at DESC, j.id DESC
LIMIT $6::int
`

type PageJobsParams struct {
	UserID       pgtype.UUID
	CursorTime   pgtype.Timestamptz
	CursorID     pgtype.UUID
	CompanyID    pgtype.UUID
	Availability string
	PageLimit    int32
}

type PageJobsRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	SuitabilityScore   pgtype.Int4
	Breakdown          []byte
}

func (q *Queries) PageJobs(ctx context.Context, arg PageJobsParams) ([]PageJobsRow, error) {
	rows, err := q.db.Query(ctx, pageJobs,
		arg.UserID,
		arg.CursorTime,
		arg.CursorID,
		arg.CompanyID,
		arg.Availability,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageJobsRow
	for rows.Next() {
		var i PageJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
			&i.SalaryRaw,
			&i.WorkArrangement,
			&i.CompanyID,
			&i.PrimaryBoardID,
			&i.ProviderPostingID,
			&i.ContentFingerprint,
			&i.SuitabilityScore,
			&i.Breakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJob = `-- name: UpsertJob :one
INSERT INTO jobs (title, location, url, company_slug, source, updated_at, scraped_at, description, salary_raw, work_arrangement)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), $7, $8, $9)
ON CONFLICT (url) DO UPDATE SET
    title            = EXCLUDED.title,
    location         = EXCLUDED.location,
    updated_at       = EXCLUDED.updated_at,
    scraped_at       = NOW(),
    description      = EXCLUDED.description,
    salary_raw       = EXCLUDED.salary_raw,
    work_arrangement = EXCLUDED.work_arrangement,
    closed_at        = NULL
RETURNING id, title, location, url, company_slug, source, updated_at, scraped_at, description, salary_raw, work_arrangement, closed_at, company_id, primary_board_id, provider_posting_id, content_fingerprint, content_changed_at, first_discovered_at
`

type UpsertJobParams struct {
	Title           string
	Location        string
	Url             string
	CompanySlug     string
	Source          string
	UpdatedAt       pgtype.Timestamptz
	Description     string
	SalaryRaw       string
	WorkArrangement string
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, upsertJob,
		arg.Title,
		arg.Location,
		arg.Url,
		arg.CompanySlug,
		arg.Source,
		arg.UpdatedAt,
		arg.Description,
		arg.SalaryRaw,
		arg.WorkArrangement,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.CompanySlug,
		&i.Source,
		&i.UpdatedAt,
		&i.ScrapedAt,
		&i.Description,
		&i.SalaryRaw,
		&i.WorkArrangement,
		&i.ClosedAt,
		&i.CompanyID,
		&i.PrimaryBoardID,
		&i.ProviderPostingID,
		&i.ContentFingerprint,
		&i.ContentChangedAt,
		&i.FirstDiscoveredAt,
	)
	return i, err
}
