// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJobByURL = `-- name: GetJobByURL :one
SELECT id, title, location, url, company_slug, source, updated_at, scraped_at FROM jobs WHERE url = $1 LIMIT 1
`

func (q *Queries) GetJobByURL(ctx context.Context, url string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByURL, url)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.CompanySlug,
		&i.Source,
		&i.UpdatedAt,
		&i.ScrapedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, title, location, url, company_slug, source, updated_at, scraped_at FROM jobs ORDER BY scraped_at DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJob = `-- name: UpsertJob :one
INSERT INTO jobs (title, location, url, company_slug, source, updated_at, scraped_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (url) DO UPDATE SET
    title      = EXCLUDED.title,
    location   = EXCLUDED.location,
    updated_at = EXCLUDED.updated_at,
    scraped_at = NOW()
RETURNING id, title, location, url, company_slug, source, updated_at, scraped_at
`

type UpsertJobParams struct {
	Title       string
	Location    string
	Url         string
	CompanySlug string
	Source      string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, upsertJob,
		arg.Title,
		arg.Location,
		arg.Url,
		arg.CompanySlug,
		arg.Source,
		arg.UpdatedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.CompanySlug,
		&i.Source,
		&i.UpdatedAt,
		&i.ScrapedAt,
	)
	return i, err
}
