// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const existingURLs = `-- name: ExistingURLs :many
SELECT url FROM jobs WHERE url = ANY($1::text[])
`

func (q *Queries) ExistingURLs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, existingURLs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobByURL = `-- name: GetJobByURL :one
SELECT id, title, location, url, company_slug, source, updated_at, scraped_at, description, salary_raw, work_arrangement FROM jobs WHERE url = $1 LIMIT 1
`

func (q *Queries) GetJobByURL(ctx context.Context, url string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByURL, url)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.CompanySlug,
		&i.Source,
		&i.UpdatedAt,
		&i.ScrapedAt,
		&i.Description,
		&i.SalaryRaw,
		&i.WorkArrangement,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at, j.description, j.salary_raw, j.work_arrangement, js.relevance_score, js.suitability_score
FROM jobs j
LEFT JOIN job_scores js ON js.job_id = j.id AND js.user_id = $1
ORDER BY COALESCE(js.suitability_score, -1) DESC, j.scraped_at DESC
`

type ListJobsRow struct {
	ID               pgtype.UUID
	Title            string
	Location         string
	Url              string
	CompanySlug      string
	Source           string
	UpdatedAt        pgtype.Timestamptz
	ScrapedAt        pgtype.Timestamptz
	Description      string
	SalaryRaw        string
	WorkArrangement  string
	RelevanceScore   pgtype.Int4
	SuitabilityScore pgtype.Int4
}

func (q *Queries) ListJobs(ctx context.Context, userID pgtype.UUID) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
			&i.Description,
			&i.SalaryRaw,
			&i.WorkArrangement,
			&i.RelevanceScore,
			&i.SuitabilityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsSince = `-- name: ListJobsSince :many
SELECT id, title, location, url, company_slug, source, updated_at, scraped_at, description, salary_raw, work_arrangement FROM jobs WHERE scraped_at > $1 ORDER BY scraped_at DESC
`

func (q *Queries) ListJobsSince(ctx context.Context, scrapedAt pgtype.Timestamptz) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsSince, scrapedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
			&i.Description,
			&i.SalaryRaw,
			&i.WorkArrangement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJob = `-- name: UpsertJob :one
INSERT INTO jobs (title, location, url, company_slug, source, updated_at, scraped_at, description, salary_raw, work_arrangement)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), $7, $8, $9)
ON CONFLICT (url) DO UPDATE SET
    title            = EXCLUDED.title,
    location         = EXCLUDED.location,
    updated_at       = EXCLUDED.updated_at,
    scraped_at       = NOW(),
    description      = EXCLUDED.description,
    salary_raw       = EXCLUDED.salary_raw,
    work_arrangement = EXCLUDED.work_arrangement
RETURNING id, title, location, url, company_slug, source, updated_at, scraped_at, description, salary_raw, work_arrangement
`

type UpsertJobParams struct {
	Title           string
	Location        string
	Url             string
	CompanySlug     string
	Source          string
	UpdatedAt       pgtype.Timestamptz
	Description     string
	SalaryRaw       string
	WorkArrangement string
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, upsertJob,
		arg.Title,
		arg.Location,
		arg.Url,
		arg.CompanySlug,
		arg.Source,
		arg.UpdatedAt,
		arg.Description,
		arg.SalaryRaw,
		arg.WorkArrangement,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.CompanySlug,
		&i.Source,
		&i.UpdatedAt,
		&i.ScrapedAt,
		&i.Description,
		&i.SalaryRaw,
		&i.WorkArrangement,
	)
	return i, err
}
