// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID          pgtype.UUID
	Title       string
	Location    string
	Url         string
	CompanySlug string
	Source      string
	UpdatedAt   pgtype.Timestamptz
	ScrapedAt   pgtype.Timestamptz
}
