// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	JobID      pgtype.UUID
	StatusID   pgtype.UUID
	Notes      pgtype.Text
	AppliedAt  pgtype.Date
	SalaryInfo pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ApplicationStatus struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Colour    string
	CreatedAt pgtype.Timestamptz
}

type BoardJobObservation struct {
	BoardID             pgtype.UUID
	JobID               pgtype.UUID
	LastSeenAt          pgtype.Timestamptz
	LastSnapshotVersion int64
}

type BoardPollState struct {
	BoardID                  pgtype.UUID
	LastCompletedAt          pgtype.Timestamptz
	LastScheduledAt          pgtype.Timestamptz
	LastStartedAt            pgtype.Timestamptz
	LastSnapshotVersion      int64
	ConsecutiveCompleteEmpty int32
	ConsecutiveFailures      int32
	LeaseOwner               pgtype.Text
	LeaseUntil               pgtype.Timestamptz
	NextDueAt                pgtype.Timestamptz
}

type CandidateAssessment struct {
	CandidateID         pgtype.UUID
	UserID              pgtype.UUID
	SearchConfigVersion pgtype.Timestamptz
	Relevance           bool
	EvaluatedAt         pgtype.Timestamptz
}

type CandidateDiscovery struct {
	CandidateID    pgtype.UUID
	SourceTargetID pgtype.UUID
	LastSeenAt     pgtype.Timestamptz
}

type Company struct {
	ID                pgtype.UUID
	Slug              string
	Name              string
	AtsSource         pgtype.Text
	AtsToken          pgtype.Text
	Domain            pgtype.Text
	LinkedinCompanyID pgtype.Text
	LastCrawledAt     pgtype.Timestamptz
	FirstSeenAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type CompanyBoard struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	Source             string
	BoardToken         string
	Status             string
	VerificationMethod pgtype.Text
	VerifiedAt         pgtype.Timestamptz
	LastLinkedAt       pgtype.Timestamptz
	RetiredAt          pgtype.Timestamptz
	SupersededAt       pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type EffectOutbox struct {
	ID             pgtype.UUID
	JobID          pgtype.UUID
	UserID         pgtype.UUID
	Fingerprint    string
	ConfigVersion  pgtype.Timestamptz
	Model          string
	FirstDiscovery bool
	Status         string
	Attempts       int32
	DueAt          pgtype.Timestamptz
	LeaseUntil     pgtype.Timestamptz
	LastError      string
	CreatedAt      pgtype.Timestamptz
}

type HarvestRun struct {
	Harvester       string
	LastSucceededAt pgtype.Timestamptz
}

type Job struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	Description        string
	SalaryRaw          string
	WorkArrangement    string
	ClosedAt           pgtype.Timestamptz
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	ContentChangedAt   pgtype.Timestamptz
	FirstDiscoveredAt  pgtype.Timestamptz
}

type JobCandidate struct {
	ID            pgtype.UUID
	NormalizedUrl string
	Source        string
	CardTitle     string
	CardCompany   string
	CardLocation  string
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	DetailState   string
}

type JobScore struct {
	ID                 pgtype.UUID
	JobID              pgtype.UUID
	UserID             pgtype.UUID
	SuitabilityScore   pgtype.Int4
	Criteria           []byte
	Confidence         pgtype.Float4
	Cost               pgtype.Numeric
	ScoreFingerprint   pgtype.Text
	ScoreConfigVersion pgtype.Timestamptz
	ScoreModel         pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type JobUrl struct {
	JobID         pgtype.UUID
	NormalizedUrl string
	Source        string
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
}

type NotificationDigest struct {
	ID       pgtype.UUID
	SentAt   pgtype.Timestamptz
	JobCount int32
}

type SearchConfig struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	ExcludedTitleKeywords []string
	ExcludedCompanies     []string
	ExcludedSeniority     []string
	ExcludedLocations     []string
	NotifyThreshold       int32
	ScoringQuestions      []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type SourceTarget struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	Source               string
	Value                string
	Enabled              bool
	Filters              []byte
	CompanyID            pgtype.UUID
	CheckIntervalMinutes int32
	LastCheckedAt        pgtype.Timestamptz
	RunStatus            string
	RunID                pgtype.UUID
	LastRunAt            pgtype.Timestamptz
	LastRunError         string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type TrackedCompany struct {
	UserID               pgtype.UUID
	CompanyID            pgtype.UUID
	Enabled              bool
	CheckIntervalMinutes int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type TrackedDoc struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	DocID   string
	AddedAt pgtype.Timestamptz
}

type TrackedDocTab struct {
	ID           pgtype.UUID
	TrackedDocID pgtype.UUID
	TabID        string
	Title        string
	Visible      bool
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	Email        pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type UserAiCredential struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Provider  string
	ApiKeyEnc string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
