// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	JobID      pgtype.UUID
	StatusID   pgtype.UUID
	Notes      pgtype.Text
	AppliedAt  pgtype.Date
	SalaryInfo pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ApplicationStatus struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Colour    string
	CreatedAt pgtype.Timestamptz
}

type Job struct {
	ID              pgtype.UUID
	Title           string
	Location        string
	Url             string
	CompanySlug     string
	Source          string
	UpdatedAt       pgtype.Timestamptz
	ScrapedAt       pgtype.Timestamptz
	Description     string
	SalaryRaw       string
	WorkArrangement string
}

type JobScore struct {
	ID               pgtype.UUID
	JobID            pgtype.UUID
	UserID           pgtype.UUID
	RelevanceScore   pgtype.Int4
	SuitabilityScore pgtype.Int4
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type NotificationDigest struct {
	ID       pgtype.UUID
	SentAt   pgtype.Timestamptz
	JobCount int32
}

type SearchConfig struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Role              string
	Location          string
	Keywords          []string
	SuitabilityRubric string
	RelevanceCutoff   int32
	NotifyThreshold   int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type SourceTarget struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Source    string
	Value     string
	Enabled   bool
	Filters   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TrackedDoc struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	DocID   string
	AddedAt pgtype.Timestamptz
}

type TrackedDocTab struct {
	ID           pgtype.UUID
	TrackedDocID pgtype.UUID
	TabID        string
	Title        string
	Visible      bool
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
