// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastNotificationDigestSentAt = `-- name: GetLastNotificationDigestSentAt :one
SELECT sent_at FROM notification_digests ORDER BY sent_at DESC LIMIT 1
`

func (q *Queries) GetLastNotificationDigestSentAt(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastNotificationDigestSentAt)
	var sent_at pgtype.Timestamptz
	err := row.Scan(&sent_at)
	return sent_at, err
}

const insertNotificationDigest = `-- name: InsertNotificationDigest :one
INSERT INTO notification_digests (sent_at, job_count)
VALUES ($1, $2)
RETURNING id, sent_at, job_count
`

type InsertNotificationDigestParams struct {
	SentAt   pgtype.Timestamptz
	JobCount int32
}

func (q *Queries) InsertNotificationDigest(ctx context.Context, arg InsertNotificationDigestParams) (NotificationDigest, error) {
	row := q.db.QueryRow(ctx, insertNotificationDigest, arg.SentAt, arg.JobCount)
	var i NotificationDigest
	err := row.Scan(&i.ID, &i.SentAt, &i.JobCount)
	return i, err
}
