// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops_state.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const opsState = `-- name: OpsState :one
SELECT
    (SELECT count(*) FROM effect_outbox WHERE status IN ('pending', 'running')) AS outbox_pending,
    (SELECT MIN(created_at)::timestamptz FROM effect_outbox WHERE status IN ('pending', 'running')) AS oldest_pending_created_at,
    (SELECT count(*) FROM effect_outbox WHERE status = 'failed') AS outbox_failed
`

type OpsStateRow struct {
	OutboxPending          int64
	OldestPendingCreatedAt pgtype.Timestamptz
	OutboxFailed           int64
}

func (q *Queries) OpsState(ctx context.Context) (OpsStateRow, error) {
	row := q.db.QueryRow(ctx, opsState)
	var i OpsStateRow
	err := row.Scan(&i.OutboxPending, &i.OldestPendingCreatedAt, &i.OutboxFailed)
	return i, err
}
