// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scoring_options.sql

package pgsqlc

import (
	"context"
)

const listScoringOptions = `-- name: ListScoringOptions :many
SELECT id, dimension, label, question, retired_at FROM scoring_options ORDER BY dimension, id
`

func (q *Queries) ListScoringOptions(ctx context.Context) ([]ScoringOption, error) {
	rows, err := q.db.Query(ctx, listScoringOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoringOption
	for rows.Next() {
		var i ScoringOption
		if err := rows.Scan(
			&i.ID,
			&i.Dimension,
			&i.Label,
			&i.Question,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
