// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_config.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSearchConfig = `-- name: GetSearchConfig :one
SELECT id, user_id, excluded_companies, excluded_locations, notify_threshold, preferences, created_at, updated_at FROM search_config WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSearchConfig(ctx context.Context, userID pgtype.UUID) (SearchConfig, error) {
	row := q.db.QueryRow(ctx, getSearchConfig, userID)
	var i SearchConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExcludedCompanies,
		&i.ExcludedLocations,
		&i.NotifyThreshold,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSearchConfigs = `-- name: ListSearchConfigs :many
SELECT id, user_id, excluded_companies, excluded_locations, notify_threshold, preferences, created_at, updated_at FROM search_config ORDER BY user_id
`

func (q *Queries) ListSearchConfigs(ctx context.Context) ([]SearchConfig, error) {
	rows, err := q.db.Query(ctx, listSearchConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchConfig
	for rows.Next() {
		var i SearchConfig
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExcludedCompanies,
			&i.ExcludedLocations,
			&i.NotifyThreshold,
			&i.Preferences,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSearchConfig = `-- name: UpsertSearchConfig :one
INSERT INTO search_config (user_id, excluded_companies, excluded_locations, notify_threshold, preferences)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    excluded_companies      = EXCLUDED.excluded_companies,
    excluded_locations      = EXCLUDED.excluded_locations,
    notify_threshold        = EXCLUDED.notify_threshold,
    preferences             = EXCLUDED.preferences,
    updated_at              = NOW()
RETURNING id, user_id, excluded_companies, excluded_locations, notify_threshold, preferences, created_at, updated_at
`

type UpsertSearchConfigParams struct {
	UserID            pgtype.UUID
	ExcludedCompanies []string
	ExcludedLocations []string
	NotifyThreshold   int32
	Preferences       []byte
}

func (q *Queries) UpsertSearchConfig(ctx context.Context, arg UpsertSearchConfigParams) (SearchConfig, error) {
	row := q.db.QueryRow(ctx, upsertSearchConfig,
		arg.UserID,
		arg.ExcludedCompanies,
		arg.ExcludedLocations,
		arg.NotifyThreshold,
		arg.Preferences,
	)
	var i SearchConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExcludedCompanies,
		&i.ExcludedLocations,
		&i.NotifyThreshold,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
