// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_config.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSearchConfig = `-- name: GetSearchConfig :one
SELECT id, user_id, excluded_title_keywords, excluded_companies, excluded_seniority, excluded_locations, suitability_rubric, notify_threshold, created_at, updated_at FROM search_config WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSearchConfig(ctx context.Context, userID pgtype.UUID) (SearchConfig, error) {
	row := q.db.QueryRow(ctx, getSearchConfig, userID)
	var i SearchConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExcludedTitleKeywords,
		&i.ExcludedCompanies,
		&i.ExcludedSeniority,
		&i.ExcludedLocations,
		&i.SuitabilityRubric,
		&i.NotifyThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSearchConfigs = `-- name: ListSearchConfigs :many
SELECT id, user_id, excluded_title_keywords, excluded_companies, excluded_seniority, excluded_locations, suitability_rubric, notify_threshold, created_at, updated_at FROM search_config ORDER BY user_id
`

func (q *Queries) ListSearchConfigs(ctx context.Context) ([]SearchConfig, error) {
	rows, err := q.db.Query(ctx, listSearchConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchConfig
	for rows.Next() {
		var i SearchConfig
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExcludedTitleKeywords,
			&i.ExcludedCompanies,
			&i.ExcludedSeniority,
			&i.ExcludedLocations,
			&i.SuitabilityRubric,
			&i.NotifyThreshold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSearchConfig = `-- name: UpsertSearchConfig :one
INSERT INTO search_config (user_id, excluded_title_keywords, excluded_companies, excluded_seniority, excluded_locations, suitability_rubric, notify_threshold)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) DO UPDATE SET
    excluded_title_keywords = EXCLUDED.excluded_title_keywords,
    excluded_companies      = EXCLUDED.excluded_companies,
    excluded_seniority      = EXCLUDED.excluded_seniority,
    excluded_locations      = EXCLUDED.excluded_locations,
    suitability_rubric      = EXCLUDED.suitability_rubric,
    notify_threshold        = EXCLUDED.notify_threshold,
    updated_at              = NOW()
RETURNING id, user_id, excluded_title_keywords, excluded_companies, excluded_seniority, excluded_locations, suitability_rubric, notify_threshold, created_at, updated_at
`

type UpsertSearchConfigParams struct {
	UserID                pgtype.UUID
	ExcludedTitleKeywords []string
	ExcludedCompanies     []string
	ExcludedSeniority     []string
	ExcludedLocations     []string
	SuitabilityRubric     string
	NotifyThreshold       int32
}

func (q *Queries) UpsertSearchConfig(ctx context.Context, arg UpsertSearchConfigParams) (SearchConfig, error) {
	row := q.db.QueryRow(ctx, upsertSearchConfig,
		arg.UserID,
		arg.ExcludedTitleKeywords,
		arg.ExcludedCompanies,
		arg.ExcludedSeniority,
		arg.ExcludedLocations,
		arg.SuitabilityRubric,
		arg.NotifyThreshold,
	)
	var i SearchConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExcludedTitleKeywords,
		&i.ExcludedCompanies,
		&i.ExcludedSeniority,
		&i.ExcludedLocations,
		&i.SuitabilityRubric,
		&i.NotifyThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
