// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_config.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSearchConfig = `-- name: GetSearchConfig :one
SELECT id, user_id, role, location, keywords, suitability_rubric, relevance_cutoff, notify_threshold, created_at, updated_at FROM search_config WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSearchConfig(ctx context.Context, userID pgtype.UUID) (SearchConfig, error) {
	row := q.db.QueryRow(ctx, getSearchConfig, userID)
	var i SearchConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Location,
		&i.Keywords,
		&i.SuitabilityRubric,
		&i.RelevanceCutoff,
		&i.NotifyThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSearchConfig = `-- name: UpsertSearchConfig :one
INSERT INTO search_config (user_id, role, location, keywords, suitability_rubric, relevance_cutoff, notify_threshold)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) DO UPDATE SET
    role               = EXCLUDED.role,
    location           = EXCLUDED.location,
    keywords           = EXCLUDED.keywords,
    suitability_rubric = EXCLUDED.suitability_rubric,
    relevance_cutoff   = EXCLUDED.relevance_cutoff,
    notify_threshold   = EXCLUDED.notify_threshold,
    updated_at         = NOW()
RETURNING id, user_id, role, location, keywords, suitability_rubric, relevance_cutoff, notify_threshold, created_at, updated_at
`

type UpsertSearchConfigParams struct {
	UserID            pgtype.UUID
	Role              string
	Location          string
	Keywords          []string
	SuitabilityRubric string
	RelevanceCutoff   int32
	NotifyThreshold   int32
}

func (q *Queries) UpsertSearchConfig(ctx context.Context, arg UpsertSearchConfigParams) (SearchConfig, error) {
	row := q.db.QueryRow(ctx, upsertSearchConfig,
		arg.UserID,
		arg.Role,
		arg.Location,
		arg.Keywords,
		arg.SuitabilityRubric,
		arg.RelevanceCutoff,
		arg.NotifyThreshold,
	)
	var i SearchConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Location,
		&i.Keywords,
		&i.SuitabilityRubric,
		&i.RelevanceCutoff,
		&i.NotifyThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
