// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: source_targets.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSourceTarget = `-- name: CreateSourceTarget :one
INSERT INTO source_targets (user_id, source, value, enabled, filters)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, source, value, enabled, filters, created_at, updated_at
`

type CreateSourceTargetParams struct {
	UserID  pgtype.UUID
	Source  string
	Value   string
	Enabled bool
	Filters []byte
}

func (q *Queries) CreateSourceTarget(ctx context.Context, arg CreateSourceTargetParams) (SourceTarget, error) {
	row := q.db.QueryRow(ctx, createSourceTarget,
		arg.UserID,
		arg.Source,
		arg.Value,
		arg.Enabled,
		arg.Filters,
	)
	var i SourceTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Value,
		&i.Enabled,
		&i.Filters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSourceTarget = `-- name: DeleteSourceTarget :exec
DELETE FROM source_targets WHERE id = $1 AND user_id = $2
`

type DeleteSourceTargetParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteSourceTarget(ctx context.Context, arg DeleteSourceTargetParams) error {
	_, err := q.db.Exec(ctx, deleteSourceTarget, arg.ID, arg.UserID)
	return err
}

const listEnabledSourceTargets = `-- name: ListEnabledSourceTargets :many
SELECT id, user_id, source, value, enabled, filters, created_at, updated_at FROM source_targets WHERE enabled = TRUE ORDER BY source, value
`

func (q *Queries) ListEnabledSourceTargets(ctx context.Context) ([]SourceTarget, error) {
	rows, err := q.db.Query(ctx, listEnabledSourceTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceTarget
	for rows.Next() {
		var i SourceTarget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.Value,
			&i.Enabled,
			&i.Filters,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceTargetsByUser = `-- name: ListSourceTargetsByUser :many
SELECT id, user_id, source, value, enabled, filters, created_at, updated_at FROM source_targets WHERE user_id = $1 ORDER BY source, value
`

func (q *Queries) ListSourceTargetsByUser(ctx context.Context, userID pgtype.UUID) ([]SourceTarget, error) {
	rows, err := q.db.Query(ctx, listSourceTargetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceTarget
	for rows.Next() {
		var i SourceTarget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.Value,
			&i.Enabled,
			&i.Filters,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSourceTarget = `-- name: UpdateSourceTarget :one
UPDATE source_targets SET enabled = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, source, value, enabled, filters, created_at, updated_at
`

type UpdateSourceTargetParams struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	Enabled bool
}

func (q *Queries) UpdateSourceTarget(ctx context.Context, arg UpdateSourceTargetParams) (SourceTarget, error) {
	row := q.db.QueryRow(ctx, updateSourceTarget, arg.ID, arg.UserID, arg.Enabled)
	var i SourceTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Value,
		&i.Enabled,
		&i.Filters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
