// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_ai_prefs.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserAIPrefs = `-- name: GetUserAIPrefs :one
SELECT id, user_id, suitability_model, created_at, updated_at FROM user_ai_prefs WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserAIPrefs(ctx context.Context, userID pgtype.UUID) (UserAiPref, error) {
	row := q.db.QueryRow(ctx, getUserAIPrefs, userID)
	var i UserAiPref
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SuitabilityModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserAIPrefs = `-- name: UpsertUserAIPrefs :one
INSERT INTO user_ai_prefs (user_id, suitability_model)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET
    suitability_model = EXCLUDED.suitability_model,
    updated_at        = now()
RETURNING id, user_id, suitability_model, created_at, updated_at
`

type UpsertUserAIPrefsParams struct {
	UserID           pgtype.UUID
	SuitabilityModel string
}

func (q *Queries) UpsertUserAIPrefs(ctx context.Context, arg UpsertUserAIPrefsParams) (UserAiPref, error) {
	row := q.db.QueryRow(ctx, upsertUserAIPrefs, arg.UserID, arg.SuitabilityModel)
	var i UserAiPref
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SuitabilityModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
