// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, username, email FROM users WHERE id = $1
`

type GetUserProfileRow struct {
	ID       pgtype.UUID
	Username string
	Email    pgtype.Text
}

func (q *Queries) GetUserProfile(ctx context.Context, id pgtype.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users SET email = $2 WHERE id = $1 RETURNING id, username, email
`

type UpdateUserEmailParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

type UpdateUserEmailRow struct {
	ID       pgtype.UUID
	Username string
	Email    pgtype.Text
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i UpdateUserEmailRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}
