// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearApplicationChase = `-- name: ClearApplicationChase :exec
UPDATE applications
SET chase_by = NULL
WHERE id = $1 AND user_id = $2
`

type ClearApplicationChaseParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) ClearApplicationChase(ctx context.Context, arg ClearApplicationChaseParams) error {
	_, err := q.db.Exec(ctx, clearApplicationChase, arg.ID, arg.UserID)
	return err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (user_id, job_id, status_id, notes, applied_at, salary_info)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, job_id, status_id, notes, applied_at, salary_info, created_at, updated_at, chase_by
`

type CreateApplicationParams struct {
	UserID     pgtype.UUID
	JobID      pgtype.UUID
	StatusID   pgtype.UUID
	Notes      pgtype.Text
	AppliedAt  pgtype.Date
	SalaryInfo pgtype.Text
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.UserID,
		arg.JobID,
		arg.StatusID,
		arg.Notes,
		arg.AppliedAt,
		arg.SalaryInfo,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.StatusID,
		&i.Notes,
		&i.AppliedAt,
		&i.SalaryInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChaseBy,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = $1 AND user_id = $2
`

type DeleteApplicationParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteApplication(ctx context.Context, arg DeleteApplicationParams) error {
	_, err := q.db.Exec(ctx, deleteApplication, arg.ID, arg.UserID)
	return err
}

const getApplicationsForJobs = `-- name: GetApplicationsForJobs :many
SELECT
    a.job_id,
    a.id,
    a.status_id,
    s.name   AS status_name,
    s.colour AS status_colour
FROM applications a
LEFT JOIN application_statuses s ON a.status_id = s.id
WHERE a.user_id = $1 AND a.job_id = ANY($2::uuid[])
`

type GetApplicationsForJobsParams struct {
	UserID  pgtype.UUID
	Column2 []pgtype.UUID
}

type GetApplicationsForJobsRow struct {
	JobID        pgtype.UUID
	ID           pgtype.UUID
	StatusID     pgtype.UUID
	StatusName   pgtype.Text
	StatusColour pgtype.Text
}

func (q *Queries) GetApplicationsForJobs(ctx context.Context, arg GetApplicationsForJobsParams) ([]GetApplicationsForJobsRow, error) {
	rows, err := q.db.Query(ctx, getApplicationsForJobs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplicationsForJobsRow
	for rows.Next() {
		var i GetApplicationsForJobsRow
		if err := rows.Scan(
			&i.JobID,
			&i.ID,
			&i.StatusID,
			&i.StatusName,
			&i.StatusColour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplications = `-- name: ListApplications :many
SELECT
    a.id, a.user_id, a.job_id, a.status_id,
    a.notes, a.applied_at, a.salary_info, a.created_at, a.updated_at, a.chase_by,
    j.title        AS job_title,
    j.company_slug AS job_company_slug,
    j.location     AS job_location,
    j.url          AS job_url,
    j.closed_at    AS job_closed_at,
    s.name         AS status_name,
    s.colour       AS status_colour
FROM applications a
JOIN jobs j ON a.job_id = j.id
LEFT JOIN application_statuses s ON a.status_id = s.id
WHERE a.user_id = $1
  AND ($2::uuid IS NULL OR a.status_id = $2)
  AND (NOT $3::boolean OR a.chase_by IS NOT NULL)
ORDER BY
    CASE WHEN $3::boolean THEN a.chase_by END ASC,
    a.updated_at DESC
`

type ListApplicationsParams struct {
	UserID   pgtype.UUID
	StatusID pgtype.UUID
	Chase    bool
}

type ListApplicationsRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	JobID          pgtype.UUID
	StatusID       pgtype.UUID
	Notes          pgtype.Text
	AppliedAt      pgtype.Date
	SalaryInfo     pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ChaseBy        pgtype.Date
	JobTitle       string
	JobCompanySlug string
	JobLocation    string
	JobUrl         string
	JobClosedAt    pgtype.Timestamptz
	StatusName     pgtype.Text
	StatusColour   pgtype.Text
}

func (q *Queries) ListApplications(ctx context.Context, arg ListApplicationsParams) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications, arg.UserID, arg.StatusID, arg.Chase)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsRow
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.StatusID,
			&i.Notes,
			&i.AppliedAt,
			&i.SalaryInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChaseBy,
			&i.JobTitle,
			&i.JobCompanySlug,
			&i.JobLocation,
			&i.JobUrl,
			&i.JobClosedAt,
			&i.StatusName,
			&i.StatusColour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockApplication = `-- name: LockApplication :one
SELECT job_id, status_id FROM applications
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type LockApplicationParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type LockApplicationRow struct {
	JobID    pgtype.UUID
	StatusID pgtype.UUID
}

func (q *Queries) LockApplication(ctx context.Context, arg LockApplicationParams) (LockApplicationRow, error) {
	row := q.db.QueryRow(ctx, lockApplication, arg.ID, arg.UserID)
	var i LockApplicationRow
	err := row.Scan(&i.JobID, &i.StatusID)
	return i, err
}

const setApplicationChase = `-- name: SetApplicationChase :one
UPDATE applications
SET chase_by = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, job_id, status_id, notes, applied_at, salary_info, created_at, updated_at, chase_by
`

type SetApplicationChaseParams struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	ChaseBy pgtype.Date
}

func (q *Queries) SetApplicationChase(ctx context.Context, arg SetApplicationChaseParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationChase, arg.ID, arg.UserID, arg.ChaseBy)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.StatusID,
		&i.Notes,
		&i.AppliedAt,
		&i.SalaryInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChaseBy,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET status_id = $3, notes = $4, applied_at = $5, salary_info = $6, updated_at = NOW(),
    chase_by = CASE WHEN status_id IS DISTINCT FROM $3 THEN NULL ELSE chase_by END
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, job_id, status_id, notes, applied_at, salary_info, created_at, updated_at, chase_by
`

type UpdateApplicationParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	StatusID   pgtype.UUID
	Notes      pgtype.Text
	AppliedAt  pgtype.Date
	SalaryInfo pgtype.Text
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.UserID,
		arg.StatusID,
		arg.Notes,
		arg.AppliedAt,
		arg.SalaryInfo,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.StatusID,
		&i.Notes,
		&i.AppliedAt,
		&i.SalaryInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChaseBy,
	)
	return i, err
}
