// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_statuses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApplicationsUsingStatus = `-- name: CountApplicationsUsingStatus :one
SELECT COUNT(*) FROM applications
WHERE status_id = $1 AND user_id = $2
`

type CountApplicationsUsingStatusParams struct {
	StatusID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) CountApplicationsUsingStatus(ctx context.Context, arg CountApplicationsUsingStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsUsingStatus, arg.StatusID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplicationStatus = `-- name: CreateApplicationStatus :one
INSERT INTO application_statuses (user_id, name, colour, reply_window_days)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, colour, created_at, reply_window_days
`

type CreateApplicationStatusParams struct {
	UserID          pgtype.UUID
	Name            string
	Colour          string
	ReplyWindowDays pgtype.Int4
}

func (q *Queries) CreateApplicationStatus(ctx context.Context, arg CreateApplicationStatusParams) (ApplicationStatus, error) {
	row := q.db.QueryRow(ctx, createApplicationStatus,
		arg.UserID,
		arg.Name,
		arg.Colour,
		arg.ReplyWindowDays,
	)
	var i ApplicationStatus
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Colour,
		&i.CreatedAt,
		&i.ReplyWindowDays,
	)
	return i, err
}

const deleteApplicationStatus = `-- name: DeleteApplicationStatus :exec
DELETE FROM application_statuses
WHERE id = $1 AND user_id = $2
`

type DeleteApplicationStatusParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteApplicationStatus(ctx context.Context, arg DeleteApplicationStatusParams) error {
	_, err := q.db.Exec(ctx, deleteApplicationStatus, arg.ID, arg.UserID)
	return err
}

const listApplicationStatusesByUser = `-- name: ListApplicationStatusesByUser :many
SELECT id, user_id, name, colour, created_at, reply_window_days FROM application_statuses
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListApplicationStatusesByUser(ctx context.Context, userID pgtype.UUID) ([]ApplicationStatus, error) {
	rows, err := q.db.Query(ctx, listApplicationStatusesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationStatus
	for rows.Next() {
		var i ApplicationStatus
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Colour,
			&i.CreatedAt,
			&i.ReplyWindowDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedDefaultStatuses = `-- name: SeedDefaultStatuses :exec
INSERT INTO application_statuses (user_id, name, colour)
VALUES
    ($1, 'Draft',        '#64748b'),
    ($1, 'Applied',      '#6366f1'),
    ($1, 'Interviewing', '#f59e0b'),
    ($1, 'Rejected',     '#ef4444'),
    ($1, 'Offer',        '#22c55e')
`

func (q *Queries) SeedDefaultStatuses(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, seedDefaultStatuses, userID)
	return err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE application_statuses
SET name = $3, colour = $4, reply_window_days = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, colour, created_at, reply_window_days
`

type UpdateApplicationStatusParams struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Name            string
	Colour          string
	ReplyWindowDays pgtype.Int4
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (ApplicationStatus, error) {
	row := q.db.QueryRow(ctx, updateApplicationStatus,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Colour,
		arg.ReplyWindowDays,
	)
	var i ApplicationStatus
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Colour,
		&i.CreatedAt,
		&i.ReplyWindowDays,
	)
	return i, err
}
