// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_poll.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPollState = `-- name: ClaimPollState :one
UPDATE board_poll_state
SET lease_owner = $2, lease_until = NOW() + INTERVAL '30 minutes',
    last_started_at = NOW(), last_snapshot_version = last_snapshot_version + 1
WHERE board_id = $1 AND (lease_until IS NULL OR lease_until < NOW())
  AND ($3::boolean OR next_due_at <= NOW() AND (last_scheduled_at IS NULL OR last_scheduled_at + (
      SELECT MIN(tc.check_interval_minutes) * INTERVAL '1 minute'
      FROM company_boards b JOIN tracked_companies tc ON tc.company_id = b.company_id AND tc.enabled
      WHERE b.id = board_poll_state.board_id
  ) <= NOW()))
  AND EXISTS (
      SELECT 1 FROM company_boards b
      JOIN tracked_companies tc ON tc.company_id = b.company_id AND tc.enabled
      WHERE b.id = board_poll_state.board_id AND b.status = 'verified'
  )
RETURNING last_snapshot_version, last_started_at
`

type ClaimPollStateParams struct {
	BoardID    pgtype.UUID
	LeaseOwner pgtype.Text
	Manual     bool
}

type ClaimPollStateRow struct {
	LastSnapshotVersion int64
	LastStartedAt       pgtype.Timestamptz
}

func (q *Queries) ClaimPollState(ctx context.Context, arg ClaimPollStateParams) (ClaimPollStateRow, error) {
	row := q.db.QueryRow(ctx, claimPollState, arg.BoardID, arg.LeaseOwner, arg.Manual)
	var i ClaimPollStateRow
	err := row.Scan(&i.LastSnapshotVersion, &i.LastStartedAt)
	return i, err
}

const closeMissingBoardJobs = `-- name: CloseMissingBoardJobs :exec
WITH closed AS (
    UPDATE jobs SET closed_at = NOW()
    WHERE primary_board_id = $1 AND closed_at IS NULL
      AND id IN (SELECT job_id FROM board_job_observations WHERE board_id = $1 AND last_snapshot_version < $2)
    RETURNING id
)
DELETE FROM option_answers WHERE job_id IN (SELECT id FROM closed)
`

type CloseMissingBoardJobsParams struct {
	PrimaryBoardID      pgtype.UUID
	LastSnapshotVersion int64
}

// Writes scoring's option_answers table directly; documented exception
// (ADR 0011, issue #264) pending #267.
func (q *Queries) CloseMissingBoardJobs(ctx context.Context, arg CloseMissingBoardJobsParams) error {
	_, err := q.db.Exec(ctx, closeMissingBoardJobs, arg.PrimaryBoardID, arg.LastSnapshotVersion)
	return err
}

const completePollState = `-- name: CompletePollState :execrows
UPDATE board_poll_state
SET last_completed_at = NOW(),
    last_scheduled_at = CASE WHEN $1::boolean THEN last_scheduled_at ELSE NOW() END,
    next_due_at = CASE WHEN $1::boolean THEN next_due_at ELSE NOW() + $2::int * INTERVAL '1 minute' END,
    consecutive_complete_empty = CASE WHEN $3::boolean THEN consecutive_complete_empty + 1 ELSE 0 END,
    consecutive_failures = 0, lease_owner = NULL, lease_until = NULL,
    last_reported_total = $4::int, last_parsed = $5::int
WHERE board_id = $6::uuid AND lease_owner = $7::text
  AND last_snapshot_version = $8::bigint
`

type CompletePollStateParams struct {
	Manual          bool
	IntervalMinutes int32
	Empty           bool
	Reported        int32
	Parsed          int32
	BoardID         pgtype.UUID
	LeaseOwner      string
	Version         int64
}

func (q *Queries) CompletePollState(ctx context.Context, arg CompletePollStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, completePollState,
		arg.Manual,
		arg.IntervalMinutes,
		arg.Empty,
		arg.Reported,
		arg.Parsed,
		arg.BoardID,
		arg.LeaseOwner,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureBoardPollState = `-- name: EnsureBoardPollState :exec
INSERT INTO board_poll_state (board_id)
SELECT id FROM company_boards WHERE id = $1 AND status = 'verified'
ON CONFLICT (board_id) DO NOTHING
`

func (q *Queries) EnsureBoardPollState(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureBoardPollState, id)
	return err
}

const failPollState = `-- name: FailPollState :execrows
UPDATE board_poll_state
SET lease_owner = NULL, lease_until = NULL, consecutive_failures = consecutive_failures + 1
WHERE board_id = $1 AND lease_owner = $2 AND last_snapshot_version = $3
`

type FailPollStateParams struct {
	BoardID             pgtype.UUID
	LeaseOwner          pgtype.Text
	LastSnapshotVersion int64
}

func (q *Queries) FailPollState(ctx context.Context, arg FailPollStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, failPollState, arg.BoardID, arg.LeaseOwner, arg.LastSnapshotVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findBoardJobAliases = `-- name: FindBoardJobAliases :many
SELECT normalized_url, job_id FROM job_urls WHERE normalized_url = ANY($1::text[])
`

type FindBoardJobAliasesRow struct {
	NormalizedUrl string
	JobID         pgtype.UUID
}

func (q *Queries) FindBoardJobAliases(ctx context.Context, dollar_1 []string) ([]FindBoardJobAliasesRow, error) {
	rows, err := q.db.Query(ctx, findBoardJobAliases, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindBoardJobAliasesRow
	for rows.Next() {
		var i FindBoardJobAliasesRow
		if err := rows.Scan(&i.NormalizedUrl, &i.JobID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollBoard = `-- name: GetPollBoard :one
SELECT b.id, b.company_id, c.slug AS company_slug, b.source, b.board_token,
       MIN(tc.check_interval_minutes)::int AS interval_minutes, s.last_scheduled_at
FROM company_boards b
JOIN companies c ON c.id = b.company_id
JOIN tracked_companies tc ON tc.company_id = b.company_id AND tc.enabled
LEFT JOIN board_poll_state s ON s.board_id = b.id
WHERE b.id = $1 AND b.status = 'verified'
GROUP BY b.id, c.slug, s.last_scheduled_at
`

type GetPollBoardRow struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	CompanySlug     string
	Source          string
	BoardToken      string
	IntervalMinutes int32
	LastScheduledAt pgtype.Timestamptz
}

func (q *Queries) GetPollBoard(ctx context.Context, id pgtype.UUID) (GetPollBoardRow, error) {
	row := q.db.QueryRow(ctx, getPollBoard, id)
	var i GetPollBoardRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanySlug,
		&i.Source,
		&i.BoardToken,
		&i.IntervalMinutes,
		&i.LastScheduledAt,
	)
	return i, err
}

const listActiveBoards = `-- name: ListActiveBoards :many
SELECT b.id, b.company_id, c.slug AS company_slug, b.source, b.board_token,
       MIN(tc.check_interval_minutes)::int AS interval_minutes
FROM company_boards b
JOIN companies c ON c.id = b.company_id
JOIN tracked_companies tc ON tc.company_id = b.company_id AND tc.enabled
WHERE b.status = 'verified'
GROUP BY b.id, c.slug
ORDER BY b.id
`

type ListActiveBoardsRow struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	CompanySlug     string
	Source          string
	BoardToken      string
	IntervalMinutes int32
}

func (q *Queries) ListActiveBoards(ctx context.Context) ([]ListActiveBoardsRow, error) {
	rows, err := q.db.Query(ctx, listActiveBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveBoardsRow
	for rows.Next() {
		var i ListActiveBoardsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CompanySlug,
			&i.Source,
			&i.BoardToken,
			&i.IntervalMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueBoards = `-- name: ListDueBoards :many
SELECT b.id, b.company_id, c.slug AS company_slug, b.source, b.board_token,
       MIN(tc.check_interval_minutes)::int AS interval_minutes
FROM company_boards b
JOIN companies c ON c.id = b.company_id
JOIN tracked_companies tc ON tc.company_id = b.company_id AND tc.enabled
LEFT JOIN board_poll_state s ON s.board_id = b.id
WHERE b.status = 'verified'
GROUP BY b.id, c.slug, s.last_scheduled_at, s.lease_until, s.next_due_at
HAVING (s.last_scheduled_at IS NULL OR s.last_scheduled_at + MIN(tc.check_interval_minutes) * INTERVAL '1 minute' <= NOW())
   AND (s.lease_until IS NULL OR s.lease_until < NOW())
   AND (s.next_due_at IS NULL OR s.next_due_at <= NOW())
ORDER BY b.id
`

type ListDueBoardsRow struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	CompanySlug     string
	Source          string
	BoardToken      string
	IntervalMinutes int32
}

func (q *Queries) ListDueBoards(ctx context.Context) ([]ListDueBoardsRow, error) {
	rows, err := q.db.Query(ctx, listDueBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueBoardsRow
	for rows.Next() {
		var i ListDueBoardsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CompanySlug,
			&i.Source,
			&i.BoardToken,
			&i.IntervalMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPollState = `-- name: LockPollState :one
SELECT board_id, last_completed_at, last_scheduled_at, last_started_at, last_snapshot_version, consecutive_complete_empty, consecutive_failures, last_reported_total, last_parsed, lease_owner, lease_until, next_due_at FROM board_poll_state WHERE board_id = $1 FOR UPDATE
`

func (q *Queries) LockPollState(ctx context.Context, boardID pgtype.UUID) (BoardPollState, error) {
	row := q.db.QueryRow(ctx, lockPollState, boardID)
	var i BoardPollState
	err := row.Scan(
		&i.BoardID,
		&i.LastCompletedAt,
		&i.LastScheduledAt,
		&i.LastStartedAt,
		&i.LastSnapshotVersion,
		&i.ConsecutiveCompleteEmpty,
		&i.ConsecutiveFailures,
		&i.LastReportedTotal,
		&i.LastParsed,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.NextDueAt,
	)
	return i, err
}

const observeBoardJob = `-- name: ObserveBoardJob :exec
INSERT INTO board_job_observations (board_id, job_id, last_seen_at, last_snapshot_version)
VALUES ($1, $2, NOW(), $3)
ON CONFLICT (board_id, job_id) DO UPDATE
SET last_seen_at = EXCLUDED.last_seen_at, last_snapshot_version = EXCLUDED.last_snapshot_version
`

type ObserveBoardJobParams struct {
	BoardID             pgtype.UUID
	JobID               pgtype.UUID
	LastSnapshotVersion int64
}

func (q *Queries) ObserveBoardJob(ctx context.Context, arg ObserveBoardJobParams) error {
	_, err := q.db.Exec(ctx, observeBoardJob, arg.BoardID, arg.JobID, arg.LastSnapshotVersion)
	return err
}

const reopenObservedBoardJobs = `-- name: ReopenObservedBoardJobs :exec
UPDATE jobs SET closed_at = NULL
WHERE id IN (SELECT job_id FROM board_job_observations WHERE board_id = $1 AND last_snapshot_version = $2)
  AND closed_at IS NOT NULL
`

type ReopenObservedBoardJobsParams struct {
	BoardID             pgtype.UUID
	LastSnapshotVersion int64
}

func (q *Queries) ReopenObservedBoardJobs(ctx context.Context, arg ReopenObservedBoardJobsParams) error {
	_, err := q.db.Exec(ctx, reopenObservedBoardJobs, arg.BoardID, arg.LastSnapshotVersion)
	return err
}

const retireSupersededBoard = `-- name: RetireSupersededBoard :exec
UPDATE company_boards SET status = 'retired', retired_at = NOW()
WHERE id = $1 AND superseded_at IS NOT NULL AND status = 'verified'
`

func (q *Queries) RetireSupersededBoard(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, retireSupersededBoard, id)
	return err
}
