// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assessCandidate = `-- name: AssessCandidate :one
WITH assessment AS (
    INSERT INTO candidate_assessments (candidate_id, user_id, search_config_version, relevance)
    VALUES ($1, $2, $3, $4)
    ON CONFLICT (candidate_id, user_id) DO UPDATE SET
        search_config_version = EXCLUDED.search_config_version,
        relevance = EXCLUDED.relevance,
        evaluated_at = NOW()
    RETURNING candidate_id
), claimed AS (
    SELECT c.id FROM job_candidates c
    WHERE c.id = (SELECT candidate_id FROM assessment)
      AND $4::boolean AND c.detail_state = 'unrequested' AND c.expires_at > NOW()
      AND NOT EXISTS (SELECT 1 FROM jobs j WHERE j.url = c.normalized_url)
)
SELECT EXISTS (SELECT 1 FROM claimed)
`

type AssessCandidateParams struct {
	CandidateID         pgtype.UUID
	UserID              pgtype.UUID
	SearchConfigVersion pgtype.Timestamptz
	Relevance           bool
}

func (q *Queries) AssessCandidate(ctx context.Context, arg AssessCandidateParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCandidate,
		arg.CandidateID,
		arg.UserID,
		arg.SearchConfigVersion,
		arg.Relevance,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteExpiredCandidates = `-- name: DeleteExpiredCandidates :exec
DELETE FROM job_candidates WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredCandidates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredCandidates)
	return err
}

const listCandidatesForUser = `-- name: ListCandidatesForUser :many
SELECT c.id, c.normalized_url, c.card_title, c.card_company, c.card_location, c.card, c.source
FROM job_candidates c
WHERE c.id > $2 AND c.expires_at > NOW()
  AND EXISTS (
      SELECT 1 FROM candidate_discoveries d
      JOIN source_targets t ON t.id = d.source_target_id
      WHERE d.candidate_id = c.id AND t.user_id = $1 AND t.enabled
  )
ORDER BY c.id
LIMIT $3
`

type ListCandidatesForUserParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
	Limit  int32
}

type ListCandidatesForUserRow struct {
	ID            pgtype.UUID
	NormalizedUrl string
	CardTitle     string
	CardCompany   string
	CardLocation  string
	Card          []byte
	Source        string
}

func (q *Queries) ListCandidatesForUser(ctx context.Context, arg ListCandidatesForUserParams) ([]ListCandidatesForUserRow, error) {
	rows, err := q.db.Query(ctx, listCandidatesForUser, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesForUserRow
	for rows.Next() {
		var i ListCandidatesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.NormalizedUrl,
			&i.CardTitle,
			&i.CardCompany,
			&i.CardLocation,
			&i.Card,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCandidateDetailPending = `-- name: MarkCandidateDetailPending :exec
UPDATE job_candidates SET detail_state = 'pending' WHERE id = $1
`

func (q *Queries) MarkCandidateDetailPending(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCandidateDetailPending, id)
	return err
}

const recordCandidateDiscovery = `-- name: RecordCandidateDiscovery :exec
INSERT INTO candidate_discoveries (candidate_id, source_target_id)
VALUES ($1, $2)
ON CONFLICT (candidate_id, source_target_id) DO UPDATE SET last_seen_at = NOW()
`

type RecordCandidateDiscoveryParams struct {
	CandidateID    pgtype.UUID
	SourceTargetID pgtype.UUID
}

func (q *Queries) RecordCandidateDiscovery(ctx context.Context, arg RecordCandidateDiscoveryParams) error {
	_, err := q.db.Exec(ctx, recordCandidateDiscovery, arg.CandidateID, arg.SourceTargetID)
	return err
}

const upsertCandidate = `-- name: UpsertCandidate :one
INSERT INTO job_candidates (normalized_url, source, card_title, card_company, card_location, card)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (normalized_url) DO UPDATE SET
    source = EXCLUDED.source,
    card_title = EXCLUDED.card_title,
    card_company = EXCLUDED.card_company,
    card_location = EXCLUDED.card_location,
    card = EXCLUDED.card,
    last_seen_at = NOW(),
    expires_at = NOW() + INTERVAL '60 days'
RETURNING id
`

type UpsertCandidateParams struct {
	NormalizedUrl string
	Source        string
	CardTitle     string
	CardCompany   string
	CardLocation  string
	Card          []byte
}

func (q *Queries) UpsertCandidate(ctx context.Context, arg UpsertCandidateParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCandidate,
		arg.NormalizedUrl,
		arg.Source,
		arg.CardTitle,
		arg.CardCompany,
		arg.CardLocation,
		arg.Card,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
