// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canonical_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backfillCompanyJobFingerprints = `-- name: BackfillCompanyJobFingerprints :exec
UPDATE jobs j SET content_fingerprint = encode(sha256(convert_to(
    replace(replace(replace(replace(replace(to_json(ARRAY[
        j.title, j.description, j.location, j.salary_raw, j.work_arrangement
    ])::text,
    '&', chr(92) || 'u0026'), '<', chr(92) || 'u003c'),
    '>', chr(92) || 'u003e'), chr(8232), chr(92) || 'u2028'),
    chr(8233), chr(92) || 'u2029'), 'UTF8')), 'hex')
FROM companies c
WHERE c.id = $1::uuid AND (j.company_id = c.id OR j.company_slug = c.slug)
    AND j.closed_at IS NULL AND j.content_fingerprint IS NULL
`

func (q *Queries) BackfillCompanyJobFingerprints(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, backfillCompanyJobFingerprints, dollar_1)
	return err
}

const findCanonicalJob = `-- name: FindCanonicalJob :one
SELECT j.id, j.url, COALESCE(j.content_fingerprint, '') AS content_fingerprint,
    j.title, j.description, j.location, j.salary_raw, j.work_arrangement,
    j.primary_board_id, j.provider_posting_id
FROM jobs j
LEFT JOIN job_urls u ON u.job_id = j.id AND u.normalized_url = $1
WHERE (j.primary_board_id = $2::uuid AND j.provider_posting_id = $3)
    OR u.normalized_url IS NOT NULL OR j.url = $1
ORDER BY CASE WHEN j.primary_board_id = $2::uuid
    AND j.provider_posting_id = $3 THEN 0
    WHEN u.normalized_url IS NOT NULL THEN 1 ELSE 2 END
LIMIT 1 FOR UPDATE OF j
`

type FindCanonicalJobParams struct {
	Url       string
	BoardID   pgtype.UUID
	PostingID pgtype.Text
}

type FindCanonicalJobRow struct {
	ID                 pgtype.UUID
	Url                string
	ContentFingerprint string
	Title              string
	Description        string
	Location           string
	SalaryRaw          string
	WorkArrangement    string
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
}

func (q *Queries) FindCanonicalJob(ctx context.Context, arg FindCanonicalJobParams) (FindCanonicalJobRow, error) {
	row := q.db.QueryRow(ctx, findCanonicalJob, arg.Url, arg.BoardID, arg.PostingID)
	var i FindCanonicalJobRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.ContentFingerprint,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.SalaryRaw,
		&i.WorkArrangement,
		&i.PrimaryBoardID,
		&i.ProviderPostingID,
	)
	return i, err
}

const insertCanonicalJob = `-- name: InsertCanonicalJob :one
INSERT INTO jobs (title, location, url, company_slug, source, updated_at, description,
    salary_raw, work_arrangement, company_id, primary_board_id, provider_posting_id,
    content_fingerprint, content_changed_at)
VALUES ($1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, COALESCE($10::uuid, (SELECT id FROM companies WHERE slug = $4)),
    $11::uuid, $12,
    $13, NOW())
RETURNING id
`

type InsertCanonicalJobParams struct {
	Title           string
	Location        string
	Url             string
	CompanySlug     string
	Source          string
	UpdatedAt       pgtype.Timestamptz
	Description     string
	SalaryRaw       string
	WorkArrangement string
	CompanyID       pgtype.UUID
	BoardID         pgtype.UUID
	PostingID       pgtype.Text
	Fingerprint     pgtype.Text
}

func (q *Queries) InsertCanonicalJob(ctx context.Context, arg InsertCanonicalJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCanonicalJob,
		arg.Title,
		arg.Location,
		arg.Url,
		arg.CompanySlug,
		arg.Source,
		arg.UpdatedAt,
		arg.Description,
		arg.SalaryRaw,
		arg.WorkArrangement,
		arg.CompanyID,
		arg.BoardID,
		arg.PostingID,
		arg.Fingerprint,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockCanonicalJob = `-- name: LockCanonicalJob :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockCanonicalJob(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockCanonicalJob, hashtextextended)
	return err
}

const saveCanonicalJobAlias = `-- name: SaveCanonicalJobAlias :execrows
INSERT INTO job_urls (job_id, normalized_url, source)
VALUES ($1::uuid, $2, $3)
ON CONFLICT (normalized_url) DO UPDATE SET last_seen_at = NOW()
WHERE job_urls.job_id = EXCLUDED.job_id
`

type SaveCanonicalJobAliasParams struct {
	Column1       pgtype.UUID
	NormalizedUrl string
	Source        string
}

func (q *Queries) SaveCanonicalJobAlias(ctx context.Context, arg SaveCanonicalJobAliasParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveCanonicalJobAlias, arg.Column1, arg.NormalizedUrl, arg.Source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChangedCanonicalJob = `-- name: UpdateChangedCanonicalJob :exec
UPDATE jobs SET title = $1, location = $2,
    updated_at = $3, description = $4,
    salary_raw = $5, work_arrangement = $6,
    content_fingerprint = $7, content_changed_at = NOW(),
    company_id = COALESCE($8::uuid, company_id, (SELECT id FROM companies WHERE slug = $9)),
    primary_board_id = COALESCE($10::uuid, primary_board_id),
    provider_posting_id = COALESCE($11, provider_posting_id),
    scraped_at = NOW()
WHERE id = $12::uuid
`

type UpdateChangedCanonicalJobParams struct {
	Title           string
	Location        string
	UpdatedAt       pgtype.Timestamptz
	Description     string
	SalaryRaw       string
	WorkArrangement string
	Fingerprint     pgtype.Text
	CompanyID       pgtype.UUID
	CompanySlug     string
	BoardID         pgtype.UUID
	PostingID       pgtype.Text
	ID              pgtype.UUID
}

func (q *Queries) UpdateChangedCanonicalJob(ctx context.Context, arg UpdateChangedCanonicalJobParams) error {
	_, err := q.db.Exec(ctx, updateChangedCanonicalJob,
		arg.Title,
		arg.Location,
		arg.UpdatedAt,
		arg.Description,
		arg.SalaryRaw,
		arg.WorkArrangement,
		arg.Fingerprint,
		arg.CompanyID,
		arg.CompanySlug,
		arg.BoardID,
		arg.PostingID,
		arg.ID,
	)
	return err
}

const updateUnchangedCanonicalJob = `-- name: UpdateUnchangedCanonicalJob :exec
UPDATE jobs SET company_id = COALESCE($1::uuid, company_id, (SELECT id FROM companies WHERE slug = $2)),
    primary_board_id = COALESCE($3::uuid, primary_board_id),
    provider_posting_id = COALESCE($4, provider_posting_id),
    content_fingerprint = COALESCE(content_fingerprint, $5)
WHERE id = $6::uuid
`

type UpdateUnchangedCanonicalJobParams struct {
	CompanyID   pgtype.UUID
	CompanySlug string
	BoardID     pgtype.UUID
	PostingID   pgtype.Text
	Fingerprint pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateUnchangedCanonicalJob(ctx context.Context, arg UpdateUnchangedCanonicalJobParams) error {
	_, err := q.db.Exec(ctx, updateUnchangedCanonicalJob,
		arg.CompanyID,
		arg.CompanySlug,
		arg.BoardID,
		arg.PostingID,
		arg.Fingerprint,
		arg.ID,
	)
	return err
}
