// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listNewCompanyProfiles = `-- name: ListNewCompanyProfiles :many
SELECT DISTINCT ON (cp.company_id) cp.company_id, cp.data
FROM tracked_companies tc
JOIN company_profiles cp ON cp.company_id = tc.company_id
WHERE tc.user_id = $1 AND tc.review_state = 'new'
ORDER BY cp.company_id, cp.fetched_at DESC
`

type ListNewCompanyProfilesRow struct {
	CompanyID pgtype.UUID
	Data      []byte
}

func (q *Queries) ListNewCompanyProfiles(ctx context.Context, userID pgtype.UUID) ([]ListNewCompanyProfilesRow, error) {
	rows, err := q.db.Query(ctx, listNewCompanyProfiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewCompanyProfilesRow
	for rows.Next() {
		var i ListNewCompanyProfilesRow
		if err := rows.Scan(&i.CompanyID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompanyProfile = `-- name: UpsertCompanyProfile :exec
INSERT INTO company_profiles (company_id, source, data) VALUES ($1, $2, $3)
ON CONFLICT (company_id, source) DO UPDATE SET data = EXCLUDED.data, fetched_at = NOW()
`

type UpsertCompanyProfileParams struct {
	CompanyID pgtype.UUID
	Source    string
	Data      []byte
}

func (q *Queries) UpsertCompanyProfile(ctx context.Context, arg UpsertCompanyProfileParams) error {
	_, err := q.db.Exec(ctx, upsertCompanyProfile, arg.CompanyID, arg.Source, arg.Data)
	return err
}
