// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCompanyTracking = `-- name: DeleteCompanyTracking :execrows
DELETE FROM tracked_companies WHERE user_id = $1 AND company_id = $2
`

type DeleteCompanyTrackingParams struct {
	UserID    pgtype.UUID
	CompanyID pgtype.UUID
}

func (q *Queries) DeleteCompanyTracking(ctx context.Context, arg DeleteCompanyTrackingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompanyTracking, arg.UserID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompany = `-- name: GetCompany :one
SELECT id, slug, name, ats_source, ats_token, domain, linkedin_company_id, last_crawled_at, first_seen_at, created_at, updated_at FROM companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.AtsSource,
		&i.AtsToken,
		&i.Domain,
		&i.LinkedinCompanyID,
		&i.LastCrawledAt,
		&i.FirstSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompaniesForUser = `-- name: ListCompaniesForUser :many
SELECT c.id, c.slug, c.name, c.ats_source, c.ats_token, c.domain, c.linkedin_company_id,
    c.last_crawled_at, c.first_seen_at,
    (SELECT COUNT(*) FROM jobs j WHERE j.company_slug = c.slug) AS job_count,
    COALESCE(tc.enabled, FALSE) AS tracked,
    COALESCE(tc.review_state, '')::text AS review_state,
    tc.check_interval_minutes,
    (SELECT MAX(bps.last_completed_at)::timestamptz FROM company_boards cb
     JOIN board_poll_state bps ON bps.board_id = cb.id
     WHERE cb.company_id = c.id AND cb.status = 'verified') AS last_checked_at
FROM companies c
LEFT JOIN tracked_companies tc ON tc.user_id = $1 AND tc.company_id = c.id
ORDER BY c.name
`

type ListCompaniesForUserRow struct {
	ID                   pgtype.UUID
	Slug                 string
	Name                 string
	AtsSource            pgtype.Text
	AtsToken             pgtype.Text
	Domain               pgtype.Text
	LinkedinCompanyID    pgtype.Text
	LastCrawledAt        pgtype.Timestamptz
	FirstSeenAt          pgtype.Timestamptz
	JobCount             int64
	Tracked              bool
	ReviewState          string
	CheckIntervalMinutes pgtype.Int4
	LastCheckedAt        pgtype.Timestamptz
}

func (q *Queries) ListCompaniesForUser(ctx context.Context, userID pgtype.UUID) ([]ListCompaniesForUserRow, error) {
	rows, err := q.db.Query(ctx, listCompaniesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesForUserRow
	for rows.Next() {
		var i ListCompaniesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.AtsSource,
			&i.AtsToken,
			&i.Domain,
			&i.LinkedinCompanyID,
			&i.LastCrawledAt,
			&i.FirstSeenAt,
			&i.JobCount,
			&i.Tracked,
			&i.ReviewState,
			&i.CheckIntervalMinutes,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesToCrawl = `-- name: ListCompaniesToCrawl :many
SELECT id, slug, name, ats_source, ats_token, domain, linkedin_company_id, last_crawled_at, first_seen_at, created_at, updated_at FROM companies
WHERE domain IS NOT NULL AND ats_source IS NULL
  AND (last_crawled_at IS NULL OR last_crawled_at < NOW() - make_interval(days => 30))
ORDER BY last_crawled_at NULLS FIRST LIMIT $1
`

func (q *Queries) ListCompaniesToCrawl(ctx context.Context, limit int32) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompaniesToCrawl, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.AtsSource,
			&i.AtsToken,
			&i.Domain,
			&i.LinkedinCompanyID,
			&i.LastCrawledAt,
			&i.FirstSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewCompaniesForUser = `-- name: ListNewCompaniesForUser :many
SELECT c.id, c.name, c.slug, tc.created_at AS added_at
FROM tracked_companies tc
JOIN companies c ON c.id = tc.company_id
WHERE tc.user_id = $1 AND tc.review_state = 'new'
ORDER BY tc.created_at DESC, c.id
`

type ListNewCompaniesForUserRow struct {
	ID      pgtype.UUID
	Name    string
	Slug    string
	AddedAt pgtype.Timestamptz
}

func (q *Queries) ListNewCompaniesForUser(ctx context.Context, userID pgtype.UUID) ([]ListNewCompaniesForUserRow, error) {
	rows, err := q.db.Query(ctx, listNewCompaniesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewCompaniesForUserRow
	for rows.Next() {
		var i ListNewCompaniesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewCompanyJobs = `-- name: ListNewCompanyJobs :many
SELECT j.company_id, j.company_slug, j.title, j.location, js.suitability_score
FROM tracked_companies tc
JOIN jobs j ON j.company_id = tc.company_id AND j.closed_at IS NULL
LEFT JOIN job_scores js ON js.job_id = j.id AND js.user_id = tc.user_id
WHERE tc.user_id = $1 AND tc.review_state = 'new'
`

type ListNewCompanyJobsRow struct {
	CompanyID        pgtype.UUID
	CompanySlug      string
	Title            string
	Location         string
	SuitabilityScore pgtype.Int4
}

func (q *Queries) ListNewCompanyJobs(ctx context.Context, userID pgtype.UUID) ([]ListNewCompanyJobsRow, error) {
	rows, err := q.db.Query(ctx, listNewCompanyJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewCompanyJobsRow
	for rows.Next() {
		var i ListNewCompanyJobsRow
		if err := rows.Scan(
			&i.CompanyID,
			&i.CompanySlug,
			&i.Title,
			&i.Location,
			&i.SuitabilityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedCompaniesForUser = `-- name: ListTrackedCompaniesForUser :many
SELECT c.id, c.name, c.slug, tc.enabled, tc.review_state, tc.check_interval_minutes,
    (SELECT COUNT(*) FROM jobs j WHERE j.company_id = c.id AND j.closed_at IS NULL) AS open_jobs,
    (SELECT COUNT(*) FROM jobs j JOIN job_scores js ON js.job_id = j.id AND js.user_id = tc.user_id
     WHERE j.company_id = c.id AND j.closed_at IS NULL
       AND NOT js.breakdown @> '[{"effect":"blocked"}]'::jsonb) AS relevant_jobs,
    (SELECT MAX(bps.last_completed_at)::timestamptz FROM company_boards cb
     JOIN board_poll_state bps ON bps.board_id = cb.id
     WHERE cb.company_id = c.id AND cb.status = 'verified') AS last_checked_at
FROM tracked_companies tc
JOIN companies c ON c.id = tc.company_id
WHERE tc.user_id = $1
ORDER BY c.name, c.id
`

type ListTrackedCompaniesForUserRow struct {
	ID                   pgtype.UUID
	Name                 string
	Slug                 string
	Enabled              bool
	ReviewState          string
	CheckIntervalMinutes int32
	OpenJobs             int64
	RelevantJobs         int64
	LastCheckedAt        pgtype.Timestamptz
}

func (q *Queries) ListTrackedCompaniesForUser(ctx context.Context, userID pgtype.UUID) ([]ListTrackedCompaniesForUserRow, error) {
	rows, err := q.db.Query(ctx, listTrackedCompaniesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrackedCompaniesForUserRow
	for rows.Next() {
		var i ListTrackedCompaniesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Enabled,
			&i.ReviewState,
			&i.CheckIntervalMinutes,
			&i.OpenJobs,
			&i.RelevantJobs,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCompany = `-- name: RenameCompany :exec
UPDATE companies SET name = $2, updated_at = NOW() WHERE id = $1
`

type RenameCompanyParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameCompany(ctx context.Context, arg RenameCompanyParams) error {
	_, err := q.db.Exec(ctx, renameCompany, arg.ID, arg.Name)
	return err
}

const setCompanyReviewState = `-- name: SetCompanyReviewState :one
UPDATE tracked_companies
SET review_state = $3::text,
    enabled = $3::text <> 'dismissed',
    updated_at = NOW()
WHERE user_id = $1 AND company_id = $2
RETURNING user_id, company_id, enabled, review_state, check_interval_minutes
`

type SetCompanyReviewStateParams struct {
	UserID      pgtype.UUID
	CompanyID   pgtype.UUID
	ReviewState string
}

type SetCompanyReviewStateRow struct {
	UserID               pgtype.UUID
	CompanyID            pgtype.UUID
	Enabled              bool
	ReviewState          string
	CheckIntervalMinutes int32
}

func (q *Queries) SetCompanyReviewState(ctx context.Context, arg SetCompanyReviewStateParams) (SetCompanyReviewStateRow, error) {
	row := q.db.QueryRow(ctx, setCompanyReviewState, arg.UserID, arg.CompanyID, arg.ReviewState)
	var i SetCompanyReviewStateRow
	err := row.Scan(
		&i.UserID,
		&i.CompanyID,
		&i.Enabled,
		&i.ReviewState,
		&i.CheckIntervalMinutes,
	)
	return i, err
}

const setCompanyTracking = `-- name: SetCompanyTracking :one
INSERT INTO tracked_companies (user_id, company_id, enabled, check_interval_minutes)
VALUES ($1, $2, $3, COALESCE(NULLIF($4::int, 0), 360))
ON CONFLICT (user_id, company_id) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    check_interval_minutes = COALESCE(NULLIF($4::int, 0), tracked_companies.check_interval_minutes),
    updated_at = NOW()
RETURNING user_id, company_id, enabled, review_state, check_interval_minutes
`

type SetCompanyTrackingParams struct {
	UserID               pgtype.UUID
	CompanyID            pgtype.UUID
	Enabled              bool
	CheckIntervalMinutes int32
}

type SetCompanyTrackingRow struct {
	UserID               pgtype.UUID
	CompanyID            pgtype.UUID
	Enabled              bool
	ReviewState          string
	CheckIntervalMinutes int32
}

func (q *Queries) SetCompanyTracking(ctx context.Context, arg SetCompanyTrackingParams) (SetCompanyTrackingRow, error) {
	row := q.db.QueryRow(ctx, setCompanyTracking,
		arg.UserID,
		arg.CompanyID,
		arg.Enabled,
		arg.CheckIntervalMinutes,
	)
	var i SetCompanyTrackingRow
	err := row.Scan(
		&i.UserID,
		&i.CompanyID,
		&i.Enabled,
		&i.ReviewState,
		&i.CheckIntervalMinutes,
	)
	return i, err
}

const touchCompanyCrawled = `-- name: TouchCompanyCrawled :exec
UPDATE companies SET last_crawled_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) TouchCompanyCrawled(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchCompanyCrawled, id)
	return err
}

const trackDiscoveredCompany = `-- name: TrackDiscoveredCompany :execrows
INSERT INTO tracked_companies (user_id, company_id, review_state)
VALUES ($1, $2, 'new')
ON CONFLICT (user_id, company_id) DO NOTHING
`

type TrackDiscoveredCompanyParams struct {
	UserID    pgtype.UUID
	CompanyID pgtype.UUID
}

func (q *Queries) TrackDiscoveredCompany(ctx context.Context, arg TrackDiscoveredCompanyParams) (int64, error) {
	result, err := q.db.Exec(ctx, trackDiscoveredCompany, arg.UserID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCompany = `-- name: UpsertCompany :one
INSERT INTO companies (slug, name, ats_source, ats_token, domain, linkedin_company_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (slug) DO UPDATE SET
    ats_source          = COALESCE(companies.ats_source, EXCLUDED.ats_source),
    ats_token           = COALESCE(companies.ats_token,  EXCLUDED.ats_token),
    domain              = COALESCE(companies.domain, EXCLUDED.domain),
    linkedin_company_id = COALESCE(companies.linkedin_company_id, EXCLUDED.linkedin_company_id),
    updated_at = NOW()
RETURNING id, slug, name, ats_source, ats_token, domain, linkedin_company_id, last_crawled_at, first_seen_at, created_at, updated_at
`

type UpsertCompanyParams struct {
	Slug              string
	Name              string
	AtsSource         pgtype.Text
	AtsToken          pgtype.Text
	Domain            pgtype.Text
	LinkedinCompanyID pgtype.Text
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, upsertCompany,
		arg.Slug,
		arg.Name,
		arg.AtsSource,
		arg.AtsToken,
		arg.Domain,
		arg.LinkedinCompanyID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.AtsSource,
		&i.AtsToken,
		&i.Domain,
		&i.LinkedinCompanyID,
		&i.LastCrawledAt,
		&i.FirstSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
