// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_boards.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBoardCompanyID = `-- name: GetBoardCompanyID :one
SELECT company_id FROM company_boards WHERE source = $1 AND board_token = $2
`

type GetBoardCompanyIDParams struct {
	Source     string
	BoardToken string
}

func (q *Queries) GetBoardCompanyID(ctx context.Context, arg GetBoardCompanyIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getBoardCompanyID, arg.Source, arg.BoardToken)
	var company_id pgtype.UUID
	err := row.Scan(&company_id)
	return company_id, err
}

const getVerifiedBoardID = `-- name: GetVerifiedBoardID :one
SELECT id FROM company_boards WHERE source = $1 AND board_token = $2 AND status = 'verified'
`

type GetVerifiedBoardIDParams struct {
	Source     string
	BoardToken string
}

func (q *Queries) GetVerifiedBoardID(ctx context.Context, arg GetVerifiedBoardIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getVerifiedBoardID, arg.Source, arg.BoardToken)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listBoardChecks = `-- name: ListBoardChecks :many
SELECT b.id, s.last_completed_at, COALESCE(s.last_reported_total, 0)::int AS last_reported_total, COALESCE(s.last_parsed, 0)::int AS last_parsed FROM company_boards b
LEFT JOIN board_poll_state s ON s.board_id = b.id
WHERE b.company_id = $1
`

type ListBoardChecksRow struct {
	ID                pgtype.UUID
	LastCompletedAt   pgtype.Timestamptz
	LastReportedTotal int32
	LastParsed        int32
}

func (q *Queries) ListBoardChecks(ctx context.Context, companyID pgtype.UUID) ([]ListBoardChecksRow, error) {
	rows, err := q.db.Query(ctx, listBoardChecks, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardChecksRow
	for rows.Next() {
		var i ListBoardChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.LastCompletedAt,
			&i.LastReportedTotal,
			&i.LastParsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyBoards = `-- name: ListCompanyBoards :many
SELECT id, company_id, source, board_token, status, verification_method, verified_at, last_linked_at, retired_at, superseded_at, discovered_via, created_at FROM company_boards WHERE company_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListCompanyBoards(ctx context.Context, companyID pgtype.UUID) ([]CompanyBoard, error) {
	rows, err := q.db.Query(ctx, listCompanyBoards, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyBoard
	for rows.Next() {
		var i CompanyBoard
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Source,
			&i.BoardToken,
			&i.Status,
			&i.VerificationMethod,
			&i.VerifiedAt,
			&i.LastLinkedAt,
			&i.RetiredAt,
			&i.SupersededAt,
			&i.DiscoveredVia,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedCompanyBoards = `-- name: ListTrackedCompanyBoards :many
SELECT cb.id, cb.company_id, cb.source, cb.board_token, cb.status
FROM company_boards cb
JOIN tracked_companies tc ON tc.company_id = cb.company_id
WHERE tc.user_id = $1
ORDER BY cb.created_at, cb.id
`

type ListTrackedCompanyBoardsRow struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	Source     string
	BoardToken string
	Status     string
}

func (q *Queries) ListTrackedCompanyBoards(ctx context.Context, userID pgtype.UUID) ([]ListTrackedCompanyBoardsRow, error) {
	rows, err := q.db.Query(ctx, listTrackedCompanyBoards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrackedCompanyBoardsRow
	for rows.Next() {
		var i ListTrackedCompanyBoardsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Source,
			&i.BoardToken,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUntrackedDiscoveredBoards = `-- name: ListUntrackedDiscoveredBoards :many
SELECT cb.id, cb.company_id, cb.source, cb.board_token, cb.status, cb.verification_method, cb.verified_at, cb.last_linked_at, cb.retired_at, cb.superseded_at, cb.discovered_via, cb.created_at FROM company_boards cb
WHERE cb.status = 'verified' AND cb.verification_method = 'discovered'
  AND NOT EXISTS (SELECT 1 FROM tracked_companies tc WHERE tc.company_id = cb.company_id)
ORDER BY cb.created_at, cb.id
`

func (q *Queries) ListUntrackedDiscoveredBoards(ctx context.Context) ([]CompanyBoard, error) {
	rows, err := q.db.Query(ctx, listUntrackedDiscoveredBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyBoard
	for rows.Next() {
		var i CompanyBoard
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Source,
			&i.BoardToken,
			&i.Status,
			&i.VerificationMethod,
			&i.VerifiedAt,
			&i.LastLinkedAt,
			&i.RetiredAt,
			&i.SupersededAt,
			&i.DiscoveredVia,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedBoardsBySlug = `-- name: ListVerifiedBoardsBySlug :many
SELECT c.slug, cb.source, cb.board_token,
  EXISTS (SELECT 1 FROM tracked_companies tc WHERE tc.company_id = c.id AND tc.enabled) AS tracked
FROM companies c
JOIN company_boards cb ON cb.company_id = c.id AND cb.status = 'verified'
WHERE c.slug = ANY($1::text[])
ORDER BY c.slug, cb.created_at, cb.id
`

type ListVerifiedBoardsBySlugRow struct {
	Slug       string
	Source     string
	BoardToken string
	Tracked    bool
}

func (q *Queries) ListVerifiedBoardsBySlug(ctx context.Context, dollar_1 []string) ([]ListVerifiedBoardsBySlugRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedBoardsBySlug, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedBoardsBySlugRow
	for rows.Next() {
		var i ListVerifiedBoardsBySlugRow
		if err := rows.Scan(
			&i.Slug,
			&i.Source,
			&i.BoardToken,
			&i.Tracked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedCompanySlugs = `-- name: ListVerifiedCompanySlugs :many
SELECT DISTINCT c.slug
FROM companies c
JOIN company_boards cb ON cb.company_id = c.id AND cb.status = 'verified'
WHERE c.slug = ANY($1::text[])
`

func (q *Queries) ListVerifiedCompanySlugs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listVerifiedCompanySlugs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCandidateBoard = `-- name: UpsertCandidateBoard :one
INSERT INTO company_boards (company_id, source, board_token)
VALUES ($1, $2, $3)
ON CONFLICT (source, board_token) DO UPDATE SET source = EXCLUDED.source
WHERE company_boards.company_id = EXCLUDED.company_id
RETURNING id, company_id, source, board_token, status, verification_method, verified_at, last_linked_at, retired_at, superseded_at, discovered_via, created_at
`

type UpsertCandidateBoardParams struct {
	CompanyID  pgtype.UUID
	Source     string
	BoardToken string
}

func (q *Queries) UpsertCandidateBoard(ctx context.Context, arg UpsertCandidateBoardParams) (CompanyBoard, error) {
	row := q.db.QueryRow(ctx, upsertCandidateBoard, arg.CompanyID, arg.Source, arg.BoardToken)
	var i CompanyBoard
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.BoardToken,
		&i.Status,
		&i.VerificationMethod,
		&i.VerifiedAt,
		&i.LastLinkedAt,
		&i.RetiredAt,
		&i.SupersededAt,
		&i.DiscoveredVia,
		&i.CreatedAt,
	)
	return i, err
}

const verifyCompanyBoard = `-- name: VerifyCompanyBoard :one
UPDATE company_boards
SET status = 'verified', verification_method = $4, verified_at = NOW(), discovered_via = NULLIF($5::text, '')
WHERE company_id = $1 AND source = $2 AND board_token = $3 AND status = 'candidate'
RETURNING id, company_id, source, board_token, status, verification_method, verified_at, last_linked_at, retired_at, superseded_at, discovered_via, created_at
`

type VerifyCompanyBoardParams struct {
	CompanyID          pgtype.UUID
	Source             string
	BoardToken         string
	VerificationMethod pgtype.Text
	Via                string
}

func (q *Queries) VerifyCompanyBoard(ctx context.Context, arg VerifyCompanyBoardParams) (CompanyBoard, error) {
	row := q.db.QueryRow(ctx, verifyCompanyBoard,
		arg.CompanyID,
		arg.Source,
		arg.BoardToken,
		arg.VerificationMethod,
		arg.Via,
	)
	var i CompanyBoard
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.BoardToken,
		&i.Status,
		&i.VerificationMethod,
		&i.VerifiedAt,
		&i.LastLinkedAt,
		&i.RetiredAt,
		&i.SupersededAt,
		&i.DiscoveredVia,
		&i.CreatedAt,
	)
	return i, err
}
