// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompany = `-- name: GetCompany :one
SELECT id, slug, name, ats_source, ats_token, domain, linkedin_company_id, last_crawled_at, first_seen_at, created_at, updated_at FROM companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.AtsSource,
		&i.AtsToken,
		&i.Domain,
		&i.LinkedinCompanyID,
		&i.LastCrawledAt,
		&i.FirstSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompaniesForUser = `-- name: ListCompaniesForUser :many
SELECT c.id, c.slug, c.name, c.ats_source, c.ats_token, c.domain, c.linkedin_company_id,
    c.last_crawled_at, c.first_seen_at,
    (SELECT COUNT(*) FROM jobs j WHERE j.company_slug = c.slug) AS job_count,
    COALESCE(tc.enabled, FALSE) AS tracked,
    tc.check_interval_minutes,
    (SELECT MAX(bps.last_completed_at)::timestamptz FROM company_boards cb
     JOIN board_poll_state bps ON bps.board_id = cb.id
     WHERE cb.company_id = c.id AND cb.status = 'verified') AS last_checked_at
FROM companies c
LEFT JOIN tracked_companies tc ON tc.user_id = $1 AND tc.company_id = c.id
ORDER BY c.name
`

type ListCompaniesForUserRow struct {
	ID                   pgtype.UUID
	Slug                 string
	Name                 string
	AtsSource            pgtype.Text
	AtsToken             pgtype.Text
	Domain               pgtype.Text
	LinkedinCompanyID    pgtype.Text
	LastCrawledAt        pgtype.Timestamptz
	FirstSeenAt          pgtype.Timestamptz
	JobCount             int64
	Tracked              bool
	CheckIntervalMinutes pgtype.Int4
	LastCheckedAt        pgtype.Timestamptz
}

func (q *Queries) ListCompaniesForUser(ctx context.Context, userID pgtype.UUID) ([]ListCompaniesForUserRow, error) {
	rows, err := q.db.Query(ctx, listCompaniesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesForUserRow
	for rows.Next() {
		var i ListCompaniesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.AtsSource,
			&i.AtsToken,
			&i.Domain,
			&i.LinkedinCompanyID,
			&i.LastCrawledAt,
			&i.FirstSeenAt,
			&i.JobCount,
			&i.Tracked,
			&i.CheckIntervalMinutes,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesToCrawl = `-- name: ListCompaniesToCrawl :many
SELECT id, slug, name, ats_source, ats_token, domain, linkedin_company_id, last_crawled_at, first_seen_at, created_at, updated_at FROM companies
WHERE domain IS NOT NULL AND ats_source IS NULL
  AND (last_crawled_at IS NULL OR last_crawled_at < NOW() - make_interval(days => 30))
ORDER BY last_crawled_at NULLS FIRST LIMIT $1
`

func (q *Queries) ListCompaniesToCrawl(ctx context.Context, limit int32) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompaniesToCrawl, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.AtsSource,
			&i.AtsToken,
			&i.Domain,
			&i.LinkedinCompanyID,
			&i.LastCrawledAt,
			&i.FirstSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCompanyTracking = `-- name: SetCompanyTracking :one
INSERT INTO tracked_companies (user_id, company_id, enabled, check_interval_minutes)
VALUES ($1, $2, $3, COALESCE(NULLIF($4::int, 0), 360))
ON CONFLICT (user_id, company_id) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    check_interval_minutes = COALESCE(NULLIF($4::int, 0), tracked_companies.check_interval_minutes),
    updated_at = NOW()
RETURNING user_id, company_id, enabled, check_interval_minutes
`

type SetCompanyTrackingParams struct {
	UserID               pgtype.UUID
	CompanyID            pgtype.UUID
	Enabled              bool
	CheckIntervalMinutes int32
}

type SetCompanyTrackingRow struct {
	UserID               pgtype.UUID
	CompanyID            pgtype.UUID
	Enabled              bool
	CheckIntervalMinutes int32
}

func (q *Queries) SetCompanyTracking(ctx context.Context, arg SetCompanyTrackingParams) (SetCompanyTrackingRow, error) {
	row := q.db.QueryRow(ctx, setCompanyTracking,
		arg.UserID,
		arg.CompanyID,
		arg.Enabled,
		arg.CheckIntervalMinutes,
	)
	var i SetCompanyTrackingRow
	err := row.Scan(
		&i.UserID,
		&i.CompanyID,
		&i.Enabled,
		&i.CheckIntervalMinutes,
	)
	return i, err
}

const touchCompanyCrawled = `-- name: TouchCompanyCrawled :exec
UPDATE companies SET last_crawled_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) TouchCompanyCrawled(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchCompanyCrawled, id)
	return err
}

const upsertCompany = `-- name: UpsertCompany :one
INSERT INTO companies (slug, name, ats_source, ats_token, domain, linkedin_company_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (slug) DO UPDATE SET
    ats_source          = COALESCE(companies.ats_source, EXCLUDED.ats_source),
    ats_token           = COALESCE(companies.ats_token,  EXCLUDED.ats_token),
    domain              = COALESCE(companies.domain, EXCLUDED.domain),
    linkedin_company_id = COALESCE(companies.linkedin_company_id, EXCLUDED.linkedin_company_id),
    updated_at = NOW()
RETURNING id, slug, name, ats_source, ats_token, domain, linkedin_company_id, last_crawled_at, first_seen_at, created_at, updated_at
`

type UpsertCompanyParams struct {
	Slug              string
	Name              string
	AtsSource         pgtype.Text
	AtsToken          pgtype.Text
	Domain            pgtype.Text
	LinkedinCompanyID pgtype.Text
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, upsertCompany,
		arg.Slug,
		arg.Name,
		arg.AtsSource,
		arg.AtsToken,
		arg.Domain,
		arg.LinkedinCompanyID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.AtsSource,
		&i.AtsToken,
		&i.Domain,
		&i.LinkedinCompanyID,
		&i.LastCrawledAt,
		&i.FirstSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
