// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fetch_cache.sql

package sqlc

import (
	"context"
)

const deleteFetchCacheURLs = `-- name: DeleteFetchCacheURLs :exec
DELETE FROM fetch_cache WHERE url = ANY($1::text[])
`

func (q *Queries) DeleteFetchCacheURLs(ctx context.Context, urls []string) error {
	_, err := q.db.Exec(ctx, deleteFetchCacheURLs, urls)
	return err
}

const getFetchCache = `-- name: GetFetchCache :one
SELECT url, status, header, body FROM fetch_cache WHERE url = $1
`

type GetFetchCacheRow struct {
	Url    string
	Status int32
	Header []byte
	Body   []byte
}

func (q *Queries) GetFetchCache(ctx context.Context, url string) (GetFetchCacheRow, error) {
	row := q.db.QueryRow(ctx, getFetchCache, url)
	var i GetFetchCacheRow
	err := row.Scan(
		&i.Url,
		&i.Status,
		&i.Header,
		&i.Body,
	)
	return i, err
}

const upsertFetchCache = `-- name: UpsertFetchCache :exec
INSERT INTO fetch_cache (url, status, header, body) VALUES ($1, $2, $3, $4)
ON CONFLICT (url) DO UPDATE SET status = EXCLUDED.status, header = EXCLUDED.header, body = EXCLUDED.body, fetched_at = NOW()
`

type UpsertFetchCacheParams struct {
	Url    string
	Status int32
	Header []byte
	Body   []byte
}

func (q *Queries) UpsertFetchCache(ctx context.Context, arg UpsertFetchCacheParams) error {
	_, err := q.db.Exec(ctx, upsertFetchCache,
		arg.Url,
		arg.Status,
		arg.Header,
		arg.Body,
	)
	return err
}
