// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: harvest_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHarvestRun = `-- name: GetHarvestRun :one
SELECT last_succeeded_at FROM harvest_runs WHERE harvester = $1
`

func (q *Queries) GetHarvestRun(ctx context.Context, harvester string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getHarvestRun, harvester)
	var last_succeeded_at pgtype.Timestamptz
	err := row.Scan(&last_succeeded_at)
	return last_succeeded_at, err
}

const setHarvestRun = `-- name: SetHarvestRun :exec
INSERT INTO harvest_runs (harvester, last_succeeded_at) VALUES ($1, NOW())
ON CONFLICT (harvester) DO UPDATE SET last_succeeded_at = NOW()
`

func (q *Queries) SetHarvestRun(ctx context.Context, harvester string) error {
	_, err := q.db.Exec(ctx, setHarvestRun, harvester)
	return err
}
