// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const existingURLs = `-- name: ExistingURLs :many
SELECT url FROM jobs WHERE url = ANY($1::text[])
UNION
SELECT normalized_url FROM job_candidates WHERE normalized_url = ANY($1::text[])
`

func (q *Queries) ExistingURLs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, existingURLs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at, j.description, j.salary_raw, j.work_arrangement, j.company_id, j.primary_board_id, j.provider_posting_id, j.content_fingerprint, js.suitability_score, js.band, js.breakdown
FROM jobs j
LEFT JOIN job_scores js ON js.job_id = j.id AND js.user_id = $2
WHERE j.id = $1
LIMIT 1
`

type GetJobParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetJobRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	Description        string
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	SuitabilityScore   pgtype.Int4
	Band               pgtype.Text
	Breakdown          []byte
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (GetJobRow, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.UserID)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.CompanySlug,
		&i.Source,
		&i.UpdatedAt,
		&i.ScrapedAt,
		&i.Description,
		&i.SalaryRaw,
		&i.WorkArrangement,
		&i.CompanyID,
		&i.PrimaryBoardID,
		&i.ProviderPostingID,
		&i.ContentFingerprint,
		&i.SuitabilityScore,
		&i.Band,
		&i.Breakdown,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at, j.salary_raw, j.work_arrangement, j.company_id, j.primary_board_id, j.provider_posting_id, j.content_fingerprint, js.suitability_score, js.band, js.breakdown, COALESCE(jg.grade, '')::text AS grade
FROM jobs j
JOIN job_scores js ON js.job_id = j.id AND js.user_id = $1
LEFT JOIN job_grades jg ON jg.job_id = j.id AND jg.user_id = $1
WHERE j.closed_at IS NULL
  AND j.updated_at > now() - interval '90 days'
  AND NOT js.breakdown @> '[{"effect":"blocked"}]'::jsonb
  AND NOT EXISTS (SELECT 1 FROM job_grades g WHERE g.job_id = j.id AND g.user_id = $1 AND g.grade = 'no')
ORDER BY js.suitability_score DESC, j.scraped_at DESC
`

type ListJobsRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	SuitabilityScore   pgtype.Int4
	Band               pgtype.Text
	Breakdown          []byte
	Grade              string
}

func (q *Queries) ListJobs(ctx context.Context, userID pgtype.UUID) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
			&i.SalaryRaw,
			&i.WorkArrangement,
			&i.CompanyID,
			&i.PrimaryBoardID,
			&i.ProviderPostingID,
			&i.ContentFingerprint,
			&i.SuitabilityScore,
			&i.Band,
			&i.Breakdown,
			&i.Grade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageJobs = `-- name: PageJobs :many
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at, j.salary_raw, j.work_arrangement, j.company_id, j.primary_board_id, j.provider_posting_id, j.content_fingerprint, js.suitability_score, js.band, js.breakdown, COALESCE(jg.grade, '')::text AS grade
FROM jobs j
LEFT JOIN job_scores js ON js.job_id = j.id AND js.user_id = $1::uuid
LEFT JOIN job_grades jg ON jg.job_id = j.id AND jg.user_id = $1::uuid
WHERE ($2::timestamptz IS NULL OR (j.scraped_at, j.id) < ($2::timestamptz, $3::uuid))
  AND ($4::uuid IS NULL OR j.company_id = $4::uuid OR (j.company_id IS NULL AND j.company_slug = (SELECT slug FROM companies WHERE id = $4::uuid)))
  AND ($5::text = 'all' OR ($5::text = 'open' AND j.closed_at IS NULL) OR ($5::text = 'closed' AND j.closed_at IS NOT NULL))
  AND (NOT $6::bool OR EXISTS (SELECT 1 FROM job_scores s WHERE s.job_id = j.id AND s.user_id = $1::uuid))
  AND ($7::int = 0 OR j.updated_at >= now() - make_interval(days => $7::int))
  AND NOT COALESCE(js.breakdown @> '[{"effect":"blocked"}]'::jsonb, false)
  AND NOT EXISTS (SELECT 1 FROM job_grades g WHERE g.job_id = j.id AND g.user_id = $1::uuid AND g.grade = 'no')
ORDER BY j.scraped_at DESC, j.id DESC
LIMIT $8::int
`

type PageJobsParams struct {
	UserID       pgtype.UUID
	CursorTime   pgtype.Timestamptz
	CursorID     pgtype.UUID
	CompanyID    pgtype.UUID
	Availability string
	ScoredOnly   bool
	SinceDays    int32
	PageLimit    int32
}

type PageJobsRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	SuitabilityScore   pgtype.Int4
	Band               pgtype.Text
	Breakdown          []byte
	Grade              string
}

func (q *Queries) PageJobs(ctx context.Context, arg PageJobsParams) ([]PageJobsRow, error) {
	rows, err := q.db.Query(ctx, pageJobs,
		arg.UserID,
		arg.CursorTime,
		arg.CursorID,
		arg.CompanyID,
		arg.Availability,
		arg.ScoredOnly,
		arg.SinceDays,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageJobsRow
	for rows.Next() {
		var i PageJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
			&i.SalaryRaw,
			&i.WorkArrangement,
			&i.CompanyID,
			&i.PrimaryBoardID,
			&i.ProviderPostingID,
			&i.ContentFingerprint,
			&i.SuitabilityScore,
			&i.Band,
			&i.Breakdown,
			&i.Grade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
