// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const existingURLs = `-- name: ExistingURLs :many
SELECT url FROM jobs WHERE url = ANY($1::text[])
UNION
SELECT normalized_url FROM job_candidates WHERE normalized_url = ANY($1::text[])
`

func (q *Queries) ExistingURLs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, existingURLs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at, j.first_discovered_at, j.description, j.salary_raw, j.work_arrangement, j.company_id, j.primary_board_id, j.provider_posting_id, j.content_fingerprint, js.suitability_score, js.band, js.breakdown, (jv.job_id IS NOT NULL)::bool AS seen, EXISTS (SELECT 1 FROM company_favourites cf JOIN companies fc ON fc.id = cf.company_id WHERE cf.user_id = $2 AND (fc.id = j.company_id OR fc.slug = j.company_slug)) AS company_favourite
FROM jobs j
LEFT JOIN job_scores js ON js.job_id = j.id AND js.user_id = $2
LEFT JOIN job_views jv ON jv.job_id = j.id AND jv.user_id = $2
WHERE j.id = $1
LIMIT 1
`

type GetJobParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetJobRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	FirstDiscoveredAt  pgtype.Timestamptz
	Description        string
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	SuitabilityScore   pgtype.Int4
	Band               pgtype.Text
	Breakdown          []byte
	Seen               bool
	CompanyFavourite   bool
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (GetJobRow, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.UserID)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.CompanySlug,
		&i.Source,
		&i.UpdatedAt,
		&i.ScrapedAt,
		&i.FirstDiscoveredAt,
		&i.Description,
		&i.SalaryRaw,
		&i.WorkArrangement,
		&i.CompanyID,
		&i.PrimaryBoardID,
		&i.ProviderPostingID,
		&i.ContentFingerprint,
		&i.SuitabilityScore,
		&i.Band,
		&i.Breakdown,
		&i.Seen,
		&i.CompanyFavourite,
	)
	return i, err
}

const listJobListings = `-- name: ListJobListings :many
SELECT source, normalized_url, first_seen_at
FROM job_urls
WHERE job_id = $1
ORDER BY first_seen_at, normalized_url
`

type ListJobListingsRow struct {
	Source        string
	NormalizedUrl string
	FirstSeenAt   pgtype.Timestamptz
}

func (q *Queries) ListJobListings(ctx context.Context, jobID pgtype.UUID) ([]ListJobListingsRow, error) {
	rows, err := q.db.Query(ctx, listJobListings, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobListingsRow
	for rows.Next() {
		var i ListJobListingsRow
		if err := rows.Scan(&i.Source, &i.NormalizedUrl, &i.FirstSeenAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at, j.first_discovered_at, j.salary_raw, j.work_arrangement, j.company_id, j.primary_board_id, j.provider_posting_id, j.content_fingerprint, js.suitability_score, js.band, js.breakdown, COALESCE(jg.grade, '')::text AS grade, (jv.job_id IS NOT NULL)::bool AS seen, EXISTS (SELECT 1 FROM company_favourites cf JOIN companies fc ON fc.id = cf.company_id WHERE cf.user_id = $1::uuid AND (fc.id = j.company_id OR fc.slug = j.company_slug)) AS company_favourite
FROM jobs j
JOIN job_scores js ON js.job_id = j.id AND js.user_id = $1::uuid
LEFT JOIN job_grades jg ON jg.job_id = j.id AND jg.user_id = $1::uuid
LEFT JOIN job_views jv ON jv.job_id = j.id AND jv.user_id = $1::uuid
WHERE j.closed_at IS NULL
  AND j.updated_at > now() - interval '90 days'
  AND COALESCE(j.company_slug, '') <> ALL($2::text[])
  AND NOT js.breakdown @> '[{"effect":"blocked"}]'::jsonb
  AND NOT EXISTS (SELECT 1 FROM job_grades g WHERE g.job_id = j.id AND g.user_id = $1::uuid AND g.grade = 'no')
ORDER BY js.suitability_score DESC, j.scraped_at DESC
`

type ListJobsParams struct {
	UserID               pgtype.UUID
	ExcludedCompanySlugs []string
}

type ListJobsRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	FirstDiscoveredAt  pgtype.Timestamptz
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	SuitabilityScore   pgtype.Int4
	Band               pgtype.Text
	Breakdown          []byte
	Grade              string
	Seen               bool
	CompanyFavourite   bool
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.UserID, arg.ExcludedCompanySlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
			&i.FirstDiscoveredAt,
			&i.SalaryRaw,
			&i.WorkArrangement,
			&i.CompanyID,
			&i.PrimaryBoardID,
			&i.ProviderPostingID,
			&i.ContentFingerprint,
			&i.SuitabilityScore,
			&i.Band,
			&i.Breakdown,
			&i.Grade,
			&i.Seen,
			&i.CompanyFavourite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobsSeen = `-- name: MarkJobsSeen :exec
INSERT INTO job_views (user_id, job_id)
SELECT $1::uuid, j.id
FROM jobs j
WHERE j.id = ANY($2::uuid[])
ON CONFLICT DO NOTHING
`

type MarkJobsSeenParams struct {
	UserID pgtype.UUID
	JobIds []pgtype.UUID
}

func (q *Queries) MarkJobsSeen(ctx context.Context, arg MarkJobsSeenParams) error {
	_, err := q.db.Exec(ctx, markJobsSeen, arg.UserID, arg.JobIds)
	return err
}

const markJobsUnseen = `-- name: MarkJobsUnseen :exec
DELETE FROM job_views
WHERE user_id = $1::uuid AND job_id = ANY($2::uuid[])
`

type MarkJobsUnseenParams struct {
	UserID pgtype.UUID
	JobIds []pgtype.UUID
}

func (q *Queries) MarkJobsUnseen(ctx context.Context, arg MarkJobsUnseenParams) error {
	_, err := q.db.Exec(ctx, markJobsUnseen, arg.UserID, arg.JobIds)
	return err
}

const pageJobs = `-- name: PageJobs :many
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at, j.first_discovered_at, j.salary_raw, j.work_arrangement, j.company_id, j.primary_board_id, j.provider_posting_id, j.content_fingerprint, js.suitability_score, js.band, js.breakdown, COALESCE(jg.grade, '')::text AS grade, (jv.job_id IS NOT NULL)::bool AS seen, EXISTS (SELECT 1 FROM company_favourites cf JOIN companies fc ON fc.id = cf.company_id WHERE cf.user_id = $1::uuid AND (fc.id = j.company_id OR fc.slug = j.company_slug)) AS company_favourite
FROM jobs j
LEFT JOIN job_scores js ON js.job_id = j.id AND js.user_id = $1::uuid
LEFT JOIN job_grades jg ON jg.job_id = j.id AND jg.user_id = $1::uuid
LEFT JOIN job_views jv ON jv.job_id = j.id AND jv.user_id = $1::uuid
WHERE ($2::timestamptz IS NULL OR (j.scraped_at, j.id) < ($2::timestamptz, $3::uuid))
  AND ($4::uuid IS NULL OR j.company_id = $4::uuid OR (j.company_id IS NULL AND j.company_slug = (SELECT slug FROM companies WHERE id = $4::uuid)))
  AND ($5::text = 'all' OR ($5::text = 'open' AND j.closed_at IS NULL) OR ($5::text = 'closed' AND j.closed_at IS NOT NULL))
  AND (NOT $6::bool OR EXISTS (SELECT 1 FROM job_scores s WHERE s.job_id = j.id AND s.user_id = $1::uuid))
  AND ($7::int = 0 OR j.updated_at >= now() - make_interval(days => $7::int))
  AND COALESCE(j.company_slug, '') <> ALL($8::text[])
  AND NOT COALESCE(js.breakdown @> '[{"effect":"blocked"}]'::jsonb, false)
  AND NOT EXISTS (SELECT 1 FROM job_grades g WHERE g.job_id = j.id AND g.user_id = $1::uuid AND g.grade = 'no')
ORDER BY j.scraped_at DESC, j.id DESC
LIMIT $9::int
`

type PageJobsParams struct {
	UserID               pgtype.UUID
	CursorTime           pgtype.Timestamptz
	CursorID             pgtype.UUID
	CompanyID            pgtype.UUID
	Availability         string
	ScoredOnly           bool
	SinceDays            int32
	ExcludedCompanySlugs []string
	PageLimit            int32
}

type PageJobsRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	FirstDiscoveredAt  pgtype.Timestamptz
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	SuitabilityScore   pgtype.Int4
	Band               pgtype.Text
	Breakdown          []byte
	Grade              string
	Seen               bool
	CompanyFavourite   bool
}

func (q *Queries) PageJobs(ctx context.Context, arg PageJobsParams) ([]PageJobsRow, error) {
	rows, err := q.db.Query(ctx, pageJobs,
		arg.UserID,
		arg.CursorTime,
		arg.CursorID,
		arg.CompanyID,
		arg.Availability,
		arg.ScoredOnly,
		arg.SinceDays,
		arg.ExcludedCompanySlugs,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageJobsRow
	for rows.Next() {
		var i PageJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
			&i.FirstDiscoveredAt,
			&i.SalaryRaw,
			&i.WorkArrangement,
			&i.CompanyID,
			&i.PrimaryBoardID,
			&i.ProviderPostingID,
			&i.ContentFingerprint,
			&i.SuitabilityScore,
			&i.Band,
			&i.Breakdown,
			&i.Grade,
			&i.Seen,
			&i.CompanyFavourite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
