// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source_targets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimRecoverableSourceTarget = `-- name: ClaimRecoverableSourceTarget :one
UPDATE source_targets SET updated_at = NOW()
WHERE id = $1 AND run_id = $2 AND enabled = TRUE
  AND (run_status = 'queued' AND updated_at < NOW() - INTERVAL '1 minute'
       OR run_status = 'running' AND updated_at < NOW() - INTERVAL '30 minutes')
RETURNING id, user_id, source, value, enabled, filters, company_id, check_interval_minutes, last_checked_at, run_status, run_id, last_run_at, last_succeeded_at, last_run_error, created_at, updated_at
`

type ClaimRecoverableSourceTargetParams struct {
	ID    pgtype.UUID
	RunID pgtype.UUID
}

func (q *Queries) ClaimRecoverableSourceTarget(ctx context.Context, arg ClaimRecoverableSourceTargetParams) (SourceTarget, error) {
	row := q.db.QueryRow(ctx, claimRecoverableSourceTarget, arg.ID, arg.RunID)
	var i SourceTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Value,
		&i.Enabled,
		&i.Filters,
		&i.CompanyID,
		&i.CheckIntervalMinutes,
		&i.LastCheckedAt,
		&i.RunStatus,
		&i.RunID,
		&i.LastRunAt,
		&i.LastSucceededAt,
		&i.LastRunError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSourceTarget = `-- name: CreateSourceTarget :one
INSERT INTO source_targets (user_id, source, value, enabled, filters)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, source, value, enabled, filters, company_id, check_interval_minutes, last_checked_at, run_status, run_id, last_run_at, last_succeeded_at, last_run_error, created_at, updated_at
`

type CreateSourceTargetParams struct {
	UserID  pgtype.UUID
	Source  string
	Value   string
	Enabled bool
	Filters []byte
}

func (q *Queries) CreateSourceTarget(ctx context.Context, arg CreateSourceTargetParams) (SourceTarget, error) {
	row := q.db.QueryRow(ctx, createSourceTarget,
		arg.UserID,
		arg.Source,
		arg.Value,
		arg.Enabled,
		arg.Filters,
	)
	var i SourceTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Value,
		&i.Enabled,
		&i.Filters,
		&i.CompanyID,
		&i.CheckIntervalMinutes,
		&i.LastCheckedAt,
		&i.RunStatus,
		&i.RunID,
		&i.LastRunAt,
		&i.LastSucceededAt,
		&i.LastRunError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSourceTargetWithRun = `-- name: CreateSourceTargetWithRun :one
INSERT INTO source_targets (user_id, source, value, enabled, filters, run_id, run_status)
VALUES ($1, $2, $3, $4, $5, gen_random_uuid(), 'queued')
RETURNING id, user_id, source, value, enabled, filters, company_id, check_interval_minutes, last_checked_at, run_status, run_id, last_run_at, last_succeeded_at, last_run_error, created_at, updated_at
`

type CreateSourceTargetWithRunParams struct {
	UserID  pgtype.UUID
	Source  string
	Value   string
	Enabled bool
	Filters []byte
}

func (q *Queries) CreateSourceTargetWithRun(ctx context.Context, arg CreateSourceTargetWithRunParams) (SourceTarget, error) {
	row := q.db.QueryRow(ctx, createSourceTargetWithRun,
		arg.UserID,
		arg.Source,
		arg.Value,
		arg.Enabled,
		arg.Filters,
	)
	var i SourceTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Value,
		&i.Enabled,
		&i.Filters,
		&i.CompanyID,
		&i.CheckIntervalMinutes,
		&i.LastCheckedAt,
		&i.RunStatus,
		&i.RunID,
		&i.LastRunAt,
		&i.LastSucceededAt,
		&i.LastRunError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSourceTarget = `-- name: DeleteSourceTarget :exec
DELETE FROM source_targets WHERE id = $1 AND user_id = $2
`

type DeleteSourceTargetParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteSourceTarget(ctx context.Context, arg DeleteSourceTargetParams) error {
	_, err := q.db.Exec(ctx, deleteSourceTarget, arg.ID, arg.UserID)
	return err
}

const getSourceTarget = `-- name: GetSourceTarget :one
SELECT id, user_id, source, value, enabled, filters, company_id, check_interval_minutes, last_checked_at, run_status, run_id, last_run_at, last_succeeded_at, last_run_error, created_at, updated_at FROM source_targets WHERE id = $1
`

func (q *Queries) GetSourceTarget(ctx context.Context, id pgtype.UUID) (SourceTarget, error) {
	row := q.db.QueryRow(ctx, getSourceTarget, id)
	var i SourceTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Value,
		&i.Enabled,
		&i.Filters,
		&i.CompanyID,
		&i.CheckIntervalMinutes,
		&i.LastCheckedAt,
		&i.RunStatus,
		&i.RunID,
		&i.LastRunAt,
		&i.LastSucceededAt,
		&i.LastRunError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecoverableSourceTargets = `-- name: ListRecoverableSourceTargets :many
SELECT id, user_id, source, value, enabled, filters, company_id, check_interval_minutes, last_checked_at, run_status, run_id, last_run_at, last_succeeded_at, last_run_error, created_at, updated_at FROM source_targets
WHERE run_id IS NOT NULL AND enabled = TRUE
  AND (run_status = 'queued' AND updated_at < NOW() - INTERVAL '1 minute'
       OR run_status = 'running' AND updated_at < NOW() - INTERVAL '30 minutes')
ORDER BY updated_at
`

func (q *Queries) ListRecoverableSourceTargets(ctx context.Context) ([]SourceTarget, error) {
	rows, err := q.db.Query(ctx, listRecoverableSourceTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceTarget
	for rows.Next() {
		var i SourceTarget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.Value,
			&i.Enabled,
			&i.Filters,
			&i.CompanyID,
			&i.CheckIntervalMinutes,
			&i.LastCheckedAt,
			&i.RunStatus,
			&i.RunID,
			&i.LastRunAt,
			&i.LastSucceededAt,
			&i.LastRunError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceTargetsByUser = `-- name: ListSourceTargetsByUser :many
SELECT id, user_id, source, value, enabled, filters, company_id, check_interval_minutes, last_checked_at, run_status, run_id, last_run_at, last_succeeded_at, last_run_error, created_at, updated_at FROM source_targets WHERE user_id = $1 ORDER BY source, value
`

func (q *Queries) ListSourceTargetsByUser(ctx context.Context, userID pgtype.UUID) ([]SourceTarget, error) {
	rows, err := q.db.Query(ctx, listSourceTargetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceTarget
	for rows.Next() {
		var i SourceTarget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.Value,
			&i.Enabled,
			&i.Filters,
			&i.CompanyID,
			&i.CheckIntervalMinutes,
			&i.LastCheckedAt,
			&i.RunStatus,
			&i.RunID,
			&i.LastRunAt,
			&i.LastSucceededAt,
			&i.LastRunError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startSourceTargetRun = `-- name: StartSourceTargetRun :one
UPDATE source_targets SET run_id = gen_random_uuid(), run_status = 'queued',
    enabled = TRUE, last_run_error = '', updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, source, value, enabled, filters, company_id, check_interval_minutes, last_checked_at, run_status, run_id, last_run_at, last_succeeded_at, last_run_error, created_at, updated_at
`

func (q *Queries) StartSourceTargetRun(ctx context.Context, id pgtype.UUID) (SourceTarget, error) {
	row := q.db.QueryRow(ctx, startSourceTargetRun, id)
	var i SourceTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Value,
		&i.Enabled,
		&i.Filters,
		&i.CompanyID,
		&i.CheckIntervalMinutes,
		&i.LastCheckedAt,
		&i.RunStatus,
		&i.RunID,
		&i.LastRunAt,
		&i.LastSucceededAt,
		&i.LastRunError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionSourceTargetRun = `-- name: TransitionSourceTargetRun :one
UPDATE source_targets SET run_status = $3, last_run_error = $4,
    last_run_at = CASE WHEN $3 IN ('succeeded', 'failed') THEN NOW() ELSE last_run_at END,
    last_succeeded_at = CASE WHEN $3 = 'succeeded' THEN NOW() ELSE last_succeeded_at END,
    updated_at = NOW()
WHERE id = $1 AND run_id = $2
RETURNING id, user_id, source, value, enabled, filters, company_id, check_interval_minutes, last_checked_at, run_status, run_id, last_run_at, last_succeeded_at, last_run_error, created_at, updated_at
`

type TransitionSourceTargetRunParams struct {
	ID           pgtype.UUID
	RunID        pgtype.UUID
	RunStatus    string
	LastRunError string
}

func (q *Queries) TransitionSourceTargetRun(ctx context.Context, arg TransitionSourceTargetRunParams) (SourceTarget, error) {
	row := q.db.QueryRow(ctx, transitionSourceTargetRun,
		arg.ID,
		arg.RunID,
		arg.RunStatus,
		arg.LastRunError,
	)
	var i SourceTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Value,
		&i.Enabled,
		&i.Filters,
		&i.CompanyID,
		&i.CheckIntervalMinutes,
		&i.LastCheckedAt,
		&i.RunStatus,
		&i.RunID,
		&i.LastRunAt,
		&i.LastSucceededAt,
		&i.LastRunError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSourceTarget = `-- name: UpdateSourceTarget :one
UPDATE source_targets SET
    enabled                = COALESCE($3, enabled),
    check_interval_minutes = COALESCE($4, check_interval_minutes),
    updated_at             = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, source, value, enabled, filters, company_id, check_interval_minutes, last_checked_at, run_status, run_id, last_run_at, last_succeeded_at, last_run_error, created_at, updated_at
`

type UpdateSourceTargetParams struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	Enabled              pgtype.Bool
	CheckIntervalMinutes pgtype.Int4
}

func (q *Queries) UpdateSourceTarget(ctx context.Context, arg UpdateSourceTargetParams) (SourceTarget, error) {
	row := q.db.QueryRow(ctx, updateSourceTarget,
		arg.ID,
		arg.UserID,
		arg.Enabled,
		arg.CheckIntervalMinutes,
	)
	var i SourceTarget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Value,
		&i.Enabled,
		&i.Filters,
		&i.CompanyID,
		&i.CheckIntervalMinutes,
		&i.LastCheckedAt,
		&i.RunStatus,
		&i.RunID,
		&i.LastRunAt,
		&i.LastSucceededAt,
		&i.LastRunError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
