// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wttj.sql

package sqlc

import (
	"context"
)

const countLiveWTTJJobs = `-- name: CountLiveWTTJJobs :one
SELECT count(*) FROM wttj_jobs WHERE gone_at IS NULL
`

func (q *Queries) CountLiveWTTJJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveWTTJJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertWTTJCompanies = `-- name: InsertWTTJCompanies :many
INSERT INTO wttj_companies (url_safe_name)
SELECT DISTINCT unnest($1::text[])
ON CONFLICT (url_safe_name) DO NOTHING
RETURNING url_safe_name
`

func (q *Queries) InsertWTTJCompanies(ctx context.Context, names []string) ([]string, error) {
	rows, err := q.db.Query(ctx, insertWTTJCompanies, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url_safe_name string
		if err := rows.Scan(&url_safe_name); err != nil {
			return nil, err
		}
		items = append(items, url_safe_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWTTJJobsGone = `-- name: MarkWTTJJobsGone :many
UPDATE wttj_jobs SET gone_at = NOW()
WHERE gone_at IS NULL AND NOT (job_id = ANY($1::text[]))
RETURNING job_id
`

func (q *Queries) MarkWTTJJobsGone(ctx context.Context, ids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, markWTTJJobsGone, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var job_id string
		if err := rows.Scan(&job_id); err != nil {
			return nil, err
		}
		items = append(items, job_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWTTJJobs = `-- name: UpsertWTTJJobs :many
INSERT INTO wttj_jobs (job_id)
SELECT DISTINCT unnest($1::text[])
ON CONFLICT (job_id) DO UPDATE SET last_seen_at = NOW(), gone_at = NULL
RETURNING job_id, (xmax = 0)::bool AS inserted
`

type UpsertWTTJJobsRow struct {
	JobID    string
	Inserted bool
}

func (q *Queries) UpsertWTTJJobs(ctx context.Context, ids []string) ([]UpsertWTTJJobsRow, error) {
	rows, err := q.db.Query(ctx, upsertWTTJJobs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertWTTJJobsRow
	for rows.Next() {
		var i UpsertWTTJJobsRow
		if err := rows.Scan(&i.JobID, &i.Inserted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
