-- +goose Up
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_raw TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE jobs DROP COLUMN IF EXISTS salary_raw;
ALTER TABLE jobs DROP COLUMN IF EXISTS description;
