// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tabs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureTabs = `-- name: EnsureTabs :exec
INSERT INTO tracked_doc_tabs (tracked_doc_id, tab_id, title)
SELECT $1, unnest($2::text[]), unnest($3::text[])
ON CONFLICT (tracked_doc_id, tab_id) DO UPDATE SET title = EXCLUDED.title
`

type EnsureTabsParams struct {
	TrackedDocID pgtype.UUID
	Column2      []string
	Column3      []string
}

func (q *Queries) EnsureTabs(ctx context.Context, arg EnsureTabsParams) error {
	_, err := q.db.Exec(ctx, ensureTabs, arg.TrackedDocID, arg.Column2, arg.Column3)
	return err
}

const listTabs = `-- name: ListTabs :many
SELECT id, tracked_doc_id, tab_id, title, visible, created_at
FROM tracked_doc_tabs
WHERE tracked_doc_id = $1
ORDER BY created_at
`

func (q *Queries) ListTabs(ctx context.Context, trackedDocID pgtype.UUID) ([]TrackedDocTab, error) {
	rows, err := q.db.Query(ctx, listTabs, trackedDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackedDocTab
	for rows.Next() {
		var i TrackedDocTab
		if err := rows.Scan(
			&i.ID,
			&i.TrackedDocID,
			&i.TabID,
			&i.Title,
			&i.Visible,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTabVisible = `-- name: SetTabVisible :execrows
UPDATE tracked_doc_tabs t
SET visible = $4
FROM tracked_docs d
WHERE t.tracked_doc_id = d.id
  AND d.user_id = $1 AND d.doc_id = $2 AND t.tab_id = $3
`

type SetTabVisibleParams struct {
	UserID  pgtype.UUID
	DocID   string
	TabID   string
	Visible bool
}

func (q *Queries) SetTabVisible(ctx context.Context, arg SetTabVisibleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTabVisible,
		arg.UserID,
		arg.DocID,
		arg.TabID,
		arg.Visible,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
