// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracked_docs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTrackedDoc = `-- name: AddTrackedDoc :exec
INSERT INTO tracked_docs (user_id, doc_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTrackedDocParams struct {
	UserID pgtype.UUID
	DocID  string
}

func (q *Queries) AddTrackedDoc(ctx context.Context, arg AddTrackedDocParams) error {
	_, err := q.db.Exec(ctx, addTrackedDoc, arg.UserID, arg.DocID)
	return err
}

const listTrackedDocs = `-- name: ListTrackedDocs :many
SELECT id, user_id, doc_id, added_at
FROM tracked_docs
WHERE user_id = $1
ORDER BY added_at
`

func (q *Queries) ListTrackedDocs(ctx context.Context, userID pgtype.UUID) ([]TrackedDoc, error) {
	rows, err := q.db.Query(ctx, listTrackedDocs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackedDoc
	for rows.Next() {
		var i TrackedDoc
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocID,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTrackedDoc = `-- name: RemoveTrackedDoc :execrows
DELETE FROM tracked_docs WHERE user_id = $1 AND doc_id = $2
`

type RemoveTrackedDocParams struct {
	UserID pgtype.UUID
	DocID  string
}

func (q *Queries) RemoveTrackedDoc(ctx context.Context, arg RemoveTrackedDocParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTrackedDoc, arg.UserID, arg.DocID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
