// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (user_id, type, subject_id, props)
VALUES ($1, $2, $3, $4)
`

type InsertEventParams struct {
	UserID    pgtype.UUID
	Type      EventType
	SubjectID pgtype.UUID
	Props     []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.UserID,
		arg.Type,
		arg.SubjectID,
		arg.Props,
	)
	return err
}

const listEventsByUser = `-- name: ListEventsByUser :many
SELECT id, type, subject_id, props, created_at
FROM events
WHERE user_id = $1
  AND ($2::event_type IS NULL OR type = $2)
ORDER BY created_at, id
`

type ListEventsByUserParams struct {
	UserID pgtype.UUID
	Type   NullEventType
}

type ListEventsByUserRow struct {
	ID        pgtype.UUID
	Type      EventType
	SubjectID pgtype.UUID
	Props     []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListEventsByUser(ctx context.Context, arg ListEventsByUserParams) ([]ListEventsByUserRow, error) {
	rows, err := q.db.Query(ctx, listEventsByUser, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsByUserRow
	for rows.Next() {
		var i ListEventsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.SubjectID,
			&i.Props,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
