// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: google_oauth_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGoogleOAuthToken = `-- name: DeleteGoogleOAuthToken :exec
DELETE FROM google_oauth_tokens WHERE user_id = $1
`

func (q *Queries) DeleteGoogleOAuthToken(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGoogleOAuthToken, userID)
	return err
}

const getGoogleOAuthToken = `-- name: GetGoogleOAuthToken :one
SELECT access_token_enc, refresh_token_enc, token_type, expiry, scope
FROM google_oauth_tokens
WHERE user_id = $1
`

type GetGoogleOAuthTokenRow struct {
	AccessTokenEnc  string
	RefreshTokenEnc string
	TokenType       string
	Expiry          pgtype.Timestamptz
	Scope           string
}

func (q *Queries) GetGoogleOAuthToken(ctx context.Context, userID pgtype.UUID) (GetGoogleOAuthTokenRow, error) {
	row := q.db.QueryRow(ctx, getGoogleOAuthToken, userID)
	var i GetGoogleOAuthTokenRow
	err := row.Scan(
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenType,
		&i.Expiry,
		&i.Scope,
	)
	return i, err
}

const upsertGoogleOAuthToken = `-- name: UpsertGoogleOAuthToken :exec
INSERT INTO google_oauth_tokens
    (user_id, access_token_enc, refresh_token_enc, token_type, expiry, scope, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    access_token_enc  = EXCLUDED.access_token_enc,
    refresh_token_enc = EXCLUDED.refresh_token_enc,
    token_type        = EXCLUDED.token_type,
    expiry            = EXCLUDED.expiry,
    scope             = EXCLUDED.scope,
    updated_at        = NOW()
`

type UpsertGoogleOAuthTokenParams struct {
	UserID          pgtype.UUID
	AccessTokenEnc  string
	RefreshTokenEnc string
	TokenType       string
	Expiry          pgtype.Timestamptz
	Scope           string
}

func (q *Queries) UpsertGoogleOAuthToken(ctx context.Context, arg UpsertGoogleOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, upsertGoogleOAuthToken,
		arg.UserID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.TokenType,
		arg.Expiry,
		arg.Scope,
	)
	return err
}
