// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answer_corrections.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAnswerCorrection = `-- name: DeleteAnswerCorrection :exec
DELETE FROM answer_corrections
WHERE user_id = $1::uuid AND job_id = $2::uuid AND option_id = $3::text
`

type DeleteAnswerCorrectionParams struct {
	UserID   pgtype.UUID
	JobID    pgtype.UUID
	OptionID string
}

func (q *Queries) DeleteAnswerCorrection(ctx context.Context, arg DeleteAnswerCorrectionParams) error {
	_, err := q.db.Exec(ctx, deleteAnswerCorrection, arg.UserID, arg.JobID, arg.OptionID)
	return err
}

const listAnswerCorrectionsForJob = `-- name: ListAnswerCorrectionsForJob :many
SELECT user_id, option_id, value FROM answer_corrections WHERE job_id = $1::uuid
`

type ListAnswerCorrectionsForJobRow struct {
	UserID   pgtype.UUID
	OptionID string
	Value    string
}

func (q *Queries) ListAnswerCorrectionsForJob(ctx context.Context, jobID pgtype.UUID) ([]ListAnswerCorrectionsForJobRow, error) {
	rows, err := q.db.Query(ctx, listAnswerCorrectionsForJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnswerCorrectionsForJobRow
	for rows.Next() {
		var i ListAnswerCorrectionsForJobRow
		if err := rows.Scan(&i.UserID, &i.OptionID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswerCorrectionsForUser = `-- name: ListAnswerCorrectionsForUser :many
SELECT job_id, option_id, value FROM answer_corrections WHERE user_id = $1::uuid
`

type ListAnswerCorrectionsForUserRow struct {
	JobID    pgtype.UUID
	OptionID string
	Value    string
}

func (q *Queries) ListAnswerCorrectionsForUser(ctx context.Context, userID pgtype.UUID) ([]ListAnswerCorrectionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAnswerCorrectionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnswerCorrectionsForUserRow
	for rows.Next() {
		var i ListAnswerCorrectionsForUserRow
		if err := rows.Scan(&i.JobID, &i.OptionID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnswerCorrection = `-- name: UpsertAnswerCorrection :exec
INSERT INTO answer_corrections (user_id, job_id, option_id, value)
VALUES ($1::uuid, $2::uuid, $3::text, $4::text)
ON CONFLICT (user_id, job_id, option_id) DO UPDATE SET value = EXCLUDED.value
`

type UpsertAnswerCorrectionParams struct {
	UserID   pgtype.UUID
	JobID    pgtype.UUID
	OptionID string
	Value    string
}

func (q *Queries) UpsertAnswerCorrection(ctx context.Context, arg UpsertAnswerCorrectionParams) error {
	_, err := q.db.Exec(ctx, upsertAnswerCorrection,
		arg.UserID,
		arg.JobID,
		arg.OptionID,
		arg.Value,
	)
	return err
}
