// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompanyProfile = `-- name: GetCompanyProfile :one
SELECT data FROM company_profiles WHERE company_id = $1 ORDER BY fetched_at DESC LIMIT 1
`

func (q *Queries) GetCompanyProfile(ctx context.Context, companyID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCompanyProfile, companyID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}
