// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: effect_outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAnswerEffect = `-- name: ClaimAnswerEffect :one
WITH next AS (
    SELECT id FROM effect_outbox
    WHERE (status = 'pending' AND due_at <= NOW())
       OR (status = 'running' AND lease_until <= NOW())
    ORDER BY due_at, id LIMIT 1 FOR UPDATE SKIP LOCKED
)
UPDATE effect_outbox e SET status = 'running', attempts = attempts + 1,
    lease_until = NOW() + interval '5 minutes'
FROM next WHERE e.id = next.id
RETURNING e.id, e.job_id, e.fingerprint, e.model, e.attempts, e.first_discovery
`

type ClaimAnswerEffectRow struct {
	ID             pgtype.UUID
	JobID          pgtype.UUID
	Fingerprint    string
	Model          string
	Attempts       int32
	FirstDiscovery bool
}

func (q *Queries) ClaimAnswerEffect(ctx context.Context) (ClaimAnswerEffectRow, error) {
	row := q.db.QueryRow(ctx, claimAnswerEffect)
	var i ClaimAnswerEffectRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Fingerprint,
		&i.Model,
		&i.Attempts,
		&i.FirstDiscovery,
	)
	return i, err
}

const completeAnswerEffect = `-- name: CompleteAnswerEffect :execrows
UPDATE effect_outbox SET status = 'done', lease_until = NULL, last_error = ''
WHERE id = $1::uuid AND attempts = $2::int AND status = 'running'
`

type CompleteAnswerEffectParams struct {
	ID       pgtype.UUID
	Attempts int32
}

func (q *Queries) CompleteAnswerEffect(ctx context.Context, arg CompleteAnswerEffectParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAnswerEffect, arg.ID, arg.Attempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failAnswerEffect = `-- name: FailAnswerEffect :exec
UPDATE effect_outbox SET
    status = CASE WHEN $1::bool OR attempts >= 8 THEN 'failed' ELSE 'pending' END,
    due_at = NOW() + make_interval(secs =>
        COALESCE($2::int, LEAST(3600, 30 * power(2, attempts)::int))),
    lease_until = NULL,
    last_error = $3::text
WHERE id = $4::uuid AND attempts = $5::int AND status = 'running'
`

type FailAnswerEffectParams struct {
	Terminal       bool
	RetryAfterSecs pgtype.Int4
	LastError      string
	ID             pgtype.UUID
	Attempts       int32
}

func (q *Queries) FailAnswerEffect(ctx context.Context, arg FailAnswerEffectParams) error {
	_, err := q.db.Exec(ctx, failAnswerEffect,
		arg.Terminal,
		arg.RetryAfterSecs,
		arg.LastError,
		arg.ID,
		arg.Attempts,
	)
	return err
}

const queueOptionBackfill = `-- name: QueueOptionBackfill :exec
INSERT INTO effect_outbox (job_id, fingerprint)
SELECT DISTINCT j.id, j.content_fingerprint
FROM jobs j JOIN job_scores s ON s.job_id = j.id
WHERE j.closed_at IS NULL AND j.content_fingerprint IS NOT NULL
ON CONFLICT (job_id, fingerprint, model) WHERE status IN ('pending', 'running') DO NOTHING
`

func (q *Queries) QueueOptionBackfill(ctx context.Context) error {
	_, err := q.db.Exec(ctx, queueOptionBackfill)
	return err
}
