// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: effect_outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAnswerEffect = `-- name: ClaimAnswerEffect :one
WITH next AS (
    SELECT id FROM effect_outbox
    WHERE (status = 'pending' AND due_at <= NOW())
       OR (status = 'running' AND lease_until <= NOW())
    ORDER BY due_at, id LIMIT 1 FOR UPDATE SKIP LOCKED
)
UPDATE effect_outbox e SET status = 'running', attempts = attempts + 1,
    lease_until = NOW() + interval '5 minutes'
FROM next WHERE e.id = next.id
RETURNING e.id, e.job_id, e.fingerprint, e.model, e.attempts, e.first_discovery
`

type ClaimAnswerEffectRow struct {
	ID             pgtype.UUID
	JobID          pgtype.UUID
	Fingerprint    string
	Model          string
	Attempts       int32
	FirstDiscovery bool
}

func (q *Queries) ClaimAnswerEffect(ctx context.Context) (ClaimAnswerEffectRow, error) {
	row := q.db.QueryRow(ctx, claimAnswerEffect)
	var i ClaimAnswerEffectRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Fingerprint,
		&i.Model,
		&i.Attempts,
		&i.FirstDiscovery,
	)
	return i, err
}

const completeAnswerEffect = `-- name: CompleteAnswerEffect :execrows
UPDATE effect_outbox SET status = 'done', lease_until = NULL, last_error = ''
WHERE id = $1::uuid AND attempts = $2::int AND status = 'running'
`

type CompleteAnswerEffectParams struct {
	ID       pgtype.UUID
	Attempts int32
}

func (q *Queries) CompleteAnswerEffect(ctx context.Context, arg CompleteAnswerEffectParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAnswerEffect, arg.ID, arg.Attempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failAnswerEffect = `-- name: FailAnswerEffect :exec
UPDATE effect_outbox SET
    status = CASE WHEN $1::bool OR attempts >= 8 THEN 'failed' ELSE 'pending' END,
    due_at = NOW() + make_interval(secs =>
        COALESCE($2::int, LEAST(3600, 30 * power(2, attempts)::int))),
    lease_until = NULL,
    last_error = $3::text
WHERE id = $4::uuid AND attempts = $5::int AND status = 'running'
`

type FailAnswerEffectParams struct {
	Terminal       bool
	RetryAfterSecs pgtype.Int4
	LastError      string
	ID             pgtype.UUID
	Attempts       int32
}

func (q *Queries) FailAnswerEffect(ctx context.Context, arg FailAnswerEffectParams) error {
	_, err := q.db.Exec(ctx, failAnswerEffect,
		arg.Terminal,
		arg.RetryAfterSecs,
		arg.LastError,
		arg.ID,
		arg.Attempts,
	)
	return err
}

const queueAnswerEffect = `-- name: QueueAnswerEffect :exec
INSERT INTO effect_outbox (job_id, fingerprint, first_discovery)
SELECT $1::uuid, $2::text, $3::boolean
FROM jobs j
WHERE j.id = $1::uuid
    AND (
        EXISTS (
            SELECT 1 FROM tracked_companies tc JOIN companies c ON c.id = tc.company_id
            WHERE tc.enabled AND (c.id = j.company_id OR c.slug = j.company_slug)
        )
        OR EXISTS (
            SELECT 1 FROM source_targets st
            WHERE st.enabled AND st.source = j.source
                AND ($4::boolean OR st.value = j.company_slug)
        )
    )
ON CONFLICT (job_id, fingerprint, model) WHERE status IN ('pending', 'running') DO NOTHING
`

type QueueAnswerEffectParams struct {
	JobID          pgtype.UUID
	Fingerprint    string
	FirstDiscovery bool
	Discovery      bool
}

func (q *Queries) QueueAnswerEffect(ctx context.Context, arg QueueAnswerEffectParams) error {
	_, err := q.db.Exec(ctx, queueAnswerEffect,
		arg.JobID,
		arg.Fingerprint,
		arg.FirstDiscovery,
		arg.Discovery,
	)
	return err
}

const queueMissingAnswers = `-- name: QueueMissingAnswers :execrows
INSERT INTO effect_outbox (job_id, fingerprint, model, first_discovery)
SELECT DISTINCT j.id, j.content_fingerprint, $1::text, FALSE
FROM job_scores s
JOIN jobs j ON j.id = s.job_id
WHERE s.user_id = $2::uuid
    AND j.closed_at IS NULL
    AND j.content_fingerprint IS NOT NULL
    AND EXISTS (
        SELECT 1 FROM unnest($3::text[]) AS missing(hash)
        WHERE NOT EXISTS (
            SELECT 1 FROM option_answers a
            WHERE a.job_id = j.id AND a.fingerprint = j.content_fingerprint
                AND a.model = $1::text AND a.question_hash = missing.hash
        )
    )
ON CONFLICT (job_id, fingerprint, model) WHERE status IN ('pending', 'running') DO NOTHING
`

type QueueMissingAnswersParams struct {
	Model          string
	UserID         pgtype.UUID
	QuestionHashes []string
}

func (q *Queries) QueueMissingAnswers(ctx context.Context, arg QueueMissingAnswersParams) (int64, error) {
	result, err := q.db.Exec(ctx, queueMissingAnswers, arg.Model, arg.UserID, arg.QuestionHashes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queueTrackingScores = `-- name: QueueTrackingScores :exec
INSERT INTO effect_outbox (job_id, fingerprint)
SELECT j.id, j.content_fingerprint
FROM jobs j JOIN companies c ON c.id = $1::uuid
WHERE j.closed_at IS NULL AND j.content_fingerprint IS NOT NULL
    AND (j.company_id = c.id OR j.company_slug = c.slug)
ON CONFLICT (job_id, fingerprint, model) WHERE status IN ('pending', 'running') DO NOTHING
`

func (q *Queries) QueueTrackingScores(ctx context.Context, companyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, queueTrackingScores, companyID)
	return err
}
