// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_grades.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGrade = `-- name: DeleteGrade :execrows
DELETE FROM job_grades WHERE user_id = $1 AND job_id = $2
`

type DeleteGradeParams struct {
	UserID pgtype.UUID
	JobID  pgtype.UUID
}

func (q *Queries) DeleteGrade(ctx context.Context, arg DeleteGradeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrade, arg.UserID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGrade = `-- name: GetGrade :one
SELECT user_id, job_id, grade, reasons, score_at_grade, score_model, created_at, updated_at FROM job_grades WHERE user_id = $1 AND job_id = $2
`

type GetGradeParams struct {
	UserID pgtype.UUID
	JobID  pgtype.UUID
}

func (q *Queries) GetGrade(ctx context.Context, arg GetGradeParams) (JobGrade, error) {
	row := q.db.QueryRow(ctx, getGrade, arg.UserID, arg.JobID)
	var i JobGrade
	err := row.Scan(
		&i.UserID,
		&i.JobID,
		&i.Grade,
		&i.Reasons,
		&i.ScoreAtGrade,
		&i.ScoreModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGrades = `-- name: ListGrades :many
SELECT user_id, job_id, grade, reasons, score_at_grade, score_model, created_at, updated_at FROM job_grades WHERE user_id = $1 ORDER BY updated_at DESC, job_id
`

func (q *Queries) ListGrades(ctx context.Context, userID pgtype.UUID) ([]JobGrade, error) {
	rows, err := q.db.Query(ctx, listGrades, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobGrade
	for rows.Next() {
		var i JobGrade
		if err := rows.Scan(
			&i.UserID,
			&i.JobID,
			&i.Grade,
			&i.Reasons,
			&i.ScoreAtGrade,
			&i.ScoreModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImpliedPositives = `-- name: ListImpliedPositives :many
SELECT job_id, 'application'::text AS source FROM applications WHERE applications.user_id = $1
UNION ALL
SELECT job_id, 'kept_cv'::text AS source FROM tailored_cvs WHERE tailored_cvs.user_id = $1 AND outcome = 'kept'
ORDER BY source, job_id
`

type ListImpliedPositivesRow struct {
	JobID  pgtype.UUID
	Source string
}

func (q *Queries) ListImpliedPositives(ctx context.Context, userID pgtype.UUID) ([]ListImpliedPositivesRow, error) {
	rows, err := q.db.Query(ctx, listImpliedPositives, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImpliedPositivesRow
	for rows.Next() {
		var i ListImpliedPositivesRow
		if err := rows.Scan(&i.JobID, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGrade = `-- name: UpsertGrade :one
INSERT INTO job_grades (user_id, job_id, grade, reasons, score_at_grade, score_model)
VALUES ($1, $2, $3::text, $4::text[], $5, $6)
ON CONFLICT (user_id, job_id) DO UPDATE
SET grade = EXCLUDED.grade, reasons = EXCLUDED.reasons, score_at_grade = EXCLUDED.score_at_grade,
    score_model = EXCLUDED.score_model, updated_at = NOW()
RETURNING user_id, job_id, grade, reasons, score_at_grade, score_model, created_at, updated_at
`

type UpsertGradeParams struct {
	UserID       pgtype.UUID
	JobID        pgtype.UUID
	Grade        string
	Reasons      []string
	ScoreAtGrade pgtype.Int4
	ScoreModel   pgtype.Text
}

func (q *Queries) UpsertGrade(ctx context.Context, arg UpsertGradeParams) (JobGrade, error) {
	row := q.db.QueryRow(ctx, upsertGrade,
		arg.UserID,
		arg.JobID,
		arg.Grade,
		arg.Reasons,
		arg.ScoreAtGrade,
		arg.ScoreModel,
	)
	var i JobGrade
	err := row.Scan(
		&i.UserID,
		&i.JobID,
		&i.Grade,
		&i.Reasons,
		&i.ScoreAtGrade,
		&i.ScoreModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
