// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ScoringDimension string

const (
	ScoringDimensionTech      ScoringDimension = "tech"
	ScoringDimensionRole      ScoringDimension = "role"
	ScoringDimensionDomain    ScoringDimension = "domain"
	ScoringDimensionSeniority ScoringDimension = "seniority"
	ScoringDimensionWork      ScoringDimension = "work"
	ScoringDimensionStage     ScoringDimension = "stage"
)

func (e *ScoringDimension) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScoringDimension(s)
	case string:
		*e = ScoringDimension(s)
	default:
		return fmt.Errorf("unsupported scan type for ScoringDimension: %T", src)
	}
	return nil
}

type NullScoringDimension struct {
	ScoringDimension ScoringDimension
	Valid            bool // Valid is true if ScoringDimension is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScoringDimension) Scan(value interface{}) error {
	if value == nil {
		ns.ScoringDimension, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScoringDimension.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScoringDimension) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScoringDimension), nil
}

type Achievement struct {
	ID         pgtype.UUID
	PositionID pgtype.UUID
	UserID     pgtype.UUID
	Text       string
	SortOrder  int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Application struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	JobID      pgtype.UUID
	StatusID   pgtype.UUID
	Notes      pgtype.Text
	AppliedAt  pgtype.Date
	SalaryInfo pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ApplicationStatus struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Colour    string
	CreatedAt pgtype.Timestamptz
}

type BoardJobObservation struct {
	BoardID             pgtype.UUID
	JobID               pgtype.UUID
	LastSeenAt          pgtype.Timestamptz
	LastSnapshotVersion int64
}

type BoardPollState struct {
	BoardID                  pgtype.UUID
	LastCompletedAt          pgtype.Timestamptz
	LastScheduledAt          pgtype.Timestamptz
	LastStartedAt            pgtype.Timestamptz
	LastSnapshotVersion      int64
	ConsecutiveCompleteEmpty int32
	ConsecutiveFailures      int32
	LeaseOwner               pgtype.Text
	LeaseUntil               pgtype.Timestamptz
	NextDueAt                pgtype.Timestamptz
}

type CandidateAssessment struct {
	CandidateID         pgtype.UUID
	UserID              pgtype.UUID
	SearchConfigVersion pgtype.Timestamptz
	Relevance           bool
	EvaluatedAt         pgtype.Timestamptz
}

type CandidateDiscovery struct {
	CandidateID    pgtype.UUID
	SourceTargetID pgtype.UUID
	LastSeenAt     pgtype.Timestamptz
}

type Company struct {
	ID                pgtype.UUID
	Slug              string
	Name              string
	AtsSource         pgtype.Text
	AtsToken          pgtype.Text
	Domain            pgtype.Text
	LinkedinCompanyID pgtype.Text
	LastCrawledAt     pgtype.Timestamptz
	FirstSeenAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type CompanyBoard struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	Source             string
	BoardToken         string
	Status             string
	VerificationMethod pgtype.Text
	VerifiedAt         pgtype.Timestamptz
	LastLinkedAt       pgtype.Timestamptz
	RetiredAt          pgtype.Timestamptz
	SupersededAt       pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type CvHeadingMapping struct {
	UserID      pgtype.UUID
	DocID       string
	TabID       string
	HeadingText string
	PositionID  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type EffectOutbox struct {
	ID             pgtype.UUID
	JobID          pgtype.UUID
	Fingerprint    string
	Model          string
	FirstDiscovery bool
	Status         string
	Attempts       int32
	DueAt          pgtype.Timestamptz
	LeaseUntil     pgtype.Timestamptz
	LastError      string
	CreatedAt      pgtype.Timestamptz
}

type FetchCache struct {
	Url       string
	Status    int32
	Header    []byte
	Body      []byte
	FetchedAt pgtype.Timestamptz
}

type GoogleOauthToken struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	AccessTokenEnc  string
	RefreshTokenEnc string
	TokenType       string
	Expiry          pgtype.Timestamptz
	Scope           string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type HarvestRun struct {
	Harvester       string
	LastSucceededAt pgtype.Timestamptz
}

type Job struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	Description        string
	SalaryRaw          string
	WorkArrangement    string
	ClosedAt           pgtype.Timestamptz
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
	ContentChangedAt   pgtype.Timestamptz
	FirstDiscoveredAt  pgtype.Timestamptz
}

type JobCandidate struct {
	ID            pgtype.UUID
	NormalizedUrl string
	Source        string
	CardTitle     string
	CardCompany   string
	CardLocation  string
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	DetailState   string
}

type JobScore struct {
	ID               pgtype.UUID
	JobID            pgtype.UUID
	UserID           pgtype.UUID
	SuitabilityScore pgtype.Int4
	Breakdown        []byte
	Cost             pgtype.Numeric
	ScoreFingerprint pgtype.Text
	ScoreModel       pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type JobUrl struct {
	JobID         pgtype.UUID
	NormalizedUrl string
	Source        string
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
}

type NotificationDigest struct {
	ID       pgtype.UUID
	SentAt   pgtype.Timestamptz
	JobCount int32
}

type OptionAnswer struct {
	JobID        pgtype.UUID
	Fingerprint  string
	QuestionHash string
	Model        string
	PYes         float32
	PNo          float32
	PNotStated   float32
	Confidence   float32
	AnsweredAt   pgtype.Timestamptz
}

type Position struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Employer  string
	Title     string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ScoringOption struct {
	ID        string
	Dimension ScoringDimension
	Label     string
	Question  string
	RetiredAt pgtype.Timestamptz
}

type SearchConfig struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	ExcludedTitleKeywords []string
	ExcludedCompanies     []string
	ExcludedLocations     []string
	RequiredLocations     []string
	RequiredTitleKeywords []string
	NotifyThreshold       int32
	Preferences           []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type SourceTarget struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	Source               string
	Value                string
	Enabled              bool
	Filters              []byte
	CompanyID            pgtype.UUID
	CheckIntervalMinutes int32
	LastCheckedAt        pgtype.Timestamptz
	RunStatus            string
	RunID                pgtype.UUID
	LastRunAt            pgtype.Timestamptz
	LastRunError         string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type TailoredCv struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	JobID          pgtype.UUID
	BaseDocID      string
	BaseTabID      string
	AchievementIds []pgtype.UUID
	EditSet        []byte
	Findings       []byte
	RawOutput      string
	Model          string
	PromptVersion  string
	JobFingerprint string
	Cost           float32
	DraftDocID     pgtype.Text
	Status         string
	Outcome        pgtype.Text
	Attempts       int32
	DueAt          pgtype.Timestamptz
	LeaseUntil     pgtype.Timestamptz
	LastError      string
	CreatedAt      pgtype.Timestamptz
}

type TrackedCompany struct {
	UserID               pgtype.UUID
	CompanyID            pgtype.UUID
	Enabled              bool
	CheckIntervalMinutes int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type TrackedDoc struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	DocID   string
	AddedAt pgtype.Timestamptz
}

type TrackedDocTab struct {
	ID           pgtype.UUID
	TrackedDocID pgtype.UUID
	TabID        string
	Title        string
	Visible      bool
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	Email        pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type UserAiCredential struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Provider  string
	ApiKeyEnc string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
