// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE endpoint = $1::text AND user_id = $2::uuid
`

type DeletePushSubscriptionParams struct {
	Endpoint string
	UserID   pgtype.UUID
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, arg.Endpoint, arg.UserID)
	return err
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT endpoint, p256dh, auth FROM push_subscriptions
WHERE user_id = $1
ORDER BY created_at, id
`

type ListPushSubscriptionsRow struct {
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) ListPushSubscriptions(ctx context.Context, userID pgtype.UUID) ([]ListPushSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPushSubscriptionsRow
	for rows.Next() {
		var i ListPushSubscriptionsRow
		if err := rows.Scan(&i.Endpoint, &i.P256dh, &i.Auth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1::uuid, $2::text, $3::text, $4::text)
ON CONFLICT (endpoint) DO UPDATE
SET user_id = EXCLUDED.user_id, p256dh = EXCLUDED.p256dh, auth = EXCLUDED.auth
`

type UpsertPushSubscriptionParams struct {
	UserID   pgtype.UUID
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}
