// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: score_feedback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearScoreFeedback = `-- name: ClearScoreFeedback :execrows
DELETE FROM score_feedback WHERE user_id = $1
`

func (q *Queries) ClearScoreFeedback(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearScoreFeedback, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countScoreFeedback = `-- name: CountScoreFeedback :one
SELECT count(*) FROM score_feedback
WHERE user_id = $1
  AND ($2::text = '' OR kind = $2::text)
`

type CountScoreFeedbackParams struct {
	UserID pgtype.UUID
	Kind   string
}

func (q *Queries) CountScoreFeedback(ctx context.Context, arg CountScoreFeedbackParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScoreFeedback, arg.UserID, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteScoreFeedback = `-- name: DeleteScoreFeedback :execrows
DELETE FROM score_feedback WHERE id = $1 AND user_id = $2
`

type DeleteScoreFeedbackParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteScoreFeedback(ctx context.Context, arg DeleteScoreFeedbackParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScoreFeedback, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJobScoreForFeedback = `-- name: GetJobScoreForFeedback :one
SELECT suitability_score::int AS score, breakdown, COALESCE(score_fingerprint, '')::text AS score_fingerprint,
    COALESCE(score_model, '')::text AS score_model
FROM job_scores
WHERE user_id = $1 AND job_id = $2 AND suitability_score IS NOT NULL
`

type GetJobScoreForFeedbackParams struct {
	UserID pgtype.UUID
	JobID  pgtype.UUID
}

type GetJobScoreForFeedbackRow struct {
	Score            int32
	Breakdown        []byte
	ScoreFingerprint string
	ScoreModel       string
}

func (q *Queries) GetJobScoreForFeedback(ctx context.Context, arg GetJobScoreForFeedbackParams) (GetJobScoreForFeedbackRow, error) {
	row := q.db.QueryRow(ctx, getJobScoreForFeedback, arg.UserID, arg.JobID)
	var i GetJobScoreForFeedbackRow
	err := row.Scan(
		&i.Score,
		&i.Breakdown,
		&i.ScoreFingerprint,
		&i.ScoreModel,
	)
	return i, err
}

const insertScoreFeedback = `-- name: InsertScoreFeedback :one
INSERT INTO score_feedback (user_id, job_id, kind, direction, reason, picks, model, snapshot)
VALUES ($1, $2, $3::text, $4::text, $5::text, $6, $7::text, $8)
RETURNING id, user_id, job_id, kind, direction, reason, picks, model, snapshot, created_at
`

type InsertScoreFeedbackParams struct {
	UserID    pgtype.UUID
	JobID     pgtype.UUID
	Kind      string
	Direction pgtype.Text
	Reason    string
	Picks     []byte
	Model     string
	Snapshot  []byte
}

func (q *Queries) InsertScoreFeedback(ctx context.Context, arg InsertScoreFeedbackParams) (ScoreFeedback, error) {
	row := q.db.QueryRow(ctx, insertScoreFeedback,
		arg.UserID,
		arg.JobID,
		arg.Kind,
		arg.Direction,
		arg.Reason,
		arg.Picks,
		arg.Model,
		arg.Snapshot,
	)
	var i ScoreFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Kind,
		&i.Direction,
		&i.Reason,
		&i.Picks,
		&i.Model,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}

const listJobScoresForCollection = `-- name: ListJobScoresForCollection :many
SELECT j.id, j.title, j.company_slug, js.suitability_score AS score, COALESCE(js.breakdown, '[]'::jsonb) AS breakdown
FROM jobs j
LEFT JOIN job_scores js ON js.job_id = j.id AND js.user_id = $1
WHERE j.id = ANY($2::uuid[])
`

type ListJobScoresForCollectionParams struct {
	UserID pgtype.UUID
	JobIds []pgtype.UUID
}

type ListJobScoresForCollectionRow struct {
	ID          pgtype.UUID
	Title       string
	CompanySlug string
	Score       pgtype.Int4
	Breakdown   []byte
}

func (q *Queries) ListJobScoresForCollection(ctx context.Context, arg ListJobScoresForCollectionParams) ([]ListJobScoresForCollectionRow, error) {
	rows, err := q.db.Query(ctx, listJobScoresForCollection, arg.UserID, arg.JobIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobScoresForCollectionRow
	for rows.Next() {
		var i ListJobScoresForCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompanySlug,
			&i.Score,
			&i.Breakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoreFeedback = `-- name: ListScoreFeedback :many
SELECT id, user_id, job_id, kind, direction, reason, picks, model, snapshot, created_at FROM score_feedback
WHERE user_id = $1
  AND ($2::text = '' OR kind = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4::int OFFSET $3::int
`

type ListScoreFeedbackParams struct {
	UserID    pgtype.UUID
	Kind      string
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListScoreFeedback(ctx context.Context, arg ListScoreFeedbackParams) ([]ScoreFeedback, error) {
	rows, err := q.db.Query(ctx, listScoreFeedback,
		arg.UserID,
		arg.Kind,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoreFeedback
	for rows.Next() {
		var i ScoreFeedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Kind,
			&i.Direction,
			&i.Reason,
			&i.Picks,
			&i.Model,
			&i.Snapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
