// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: score_feedback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearScoreFeedback = `-- name: ClearScoreFeedback :execrows
DELETE FROM score_feedback WHERE user_id = $1
`

func (q *Queries) ClearScoreFeedback(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearScoreFeedback, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countScoreFeedback = `-- name: CountScoreFeedback :one
SELECT count(*) FILTER (WHERE NOT (d.picks_changed OR d.model_changed))::bigint AS current,
       count(*) FILTER (WHERE d.picks_changed OR d.model_changed)::bigint AS outdated
FROM score_feedback sf
CROSS JOIN LATERAL (
    SELECT sf.picks IS DISTINCT FROM COALESCE((SELECT preferences->'picks' FROM search_config WHERE user_id = sf.user_id), '[]'::jsonb) AS picks_changed,
           sf.model <> $1::text AS model_changed
) d
WHERE sf.user_id = $2
  AND ($3::text = '' OR sf.kind = $3::text)
`

type CountScoreFeedbackParams struct {
	Model  string
	UserID pgtype.UUID
	Kind   string
}

type CountScoreFeedbackRow struct {
	Current  int64
	Outdated int64
}

func (q *Queries) CountScoreFeedback(ctx context.Context, arg CountScoreFeedbackParams) (CountScoreFeedbackRow, error) {
	row := q.db.QueryRow(ctx, countScoreFeedback, arg.Model, arg.UserID, arg.Kind)
	var i CountScoreFeedbackRow
	err := row.Scan(&i.Current, &i.Outdated)
	return i, err
}

const deleteScoreFeedback = `-- name: DeleteScoreFeedback :execrows
DELETE FROM score_feedback WHERE id = $1 AND user_id = $2
`

type DeleteScoreFeedbackParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteScoreFeedback(ctx context.Context, arg DeleteScoreFeedbackParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScoreFeedback, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJobScoreForFeedback = `-- name: GetJobScoreForFeedback :one
SELECT suitability_score::int AS score, breakdown, COALESCE(score_fingerprint, '')::text AS score_fingerprint,
    COALESCE(score_model, '')::text AS score_model
FROM job_scores
WHERE user_id = $1 AND job_id = $2 AND suitability_score IS NOT NULL
`

type GetJobScoreForFeedbackParams struct {
	UserID pgtype.UUID
	JobID  pgtype.UUID
}

type GetJobScoreForFeedbackRow struct {
	Score            int32
	Breakdown        []byte
	ScoreFingerprint string
	ScoreModel       string
}

func (q *Queries) GetJobScoreForFeedback(ctx context.Context, arg GetJobScoreForFeedbackParams) (GetJobScoreForFeedbackRow, error) {
	row := q.db.QueryRow(ctx, getJobScoreForFeedback, arg.UserID, arg.JobID)
	var i GetJobScoreForFeedbackRow
	err := row.Scan(
		&i.Score,
		&i.Breakdown,
		&i.ScoreFingerprint,
		&i.ScoreModel,
	)
	return i, err
}

const insertScoreFeedback = `-- name: InsertScoreFeedback :one
INSERT INTO score_feedback (user_id, job_id, kind, direction, reason, picks, model, snapshot)
VALUES ($1, $2, $3::text, $4::text, $5::text, $6, $7::text, $8)
RETURNING id, user_id, job_id, kind, direction, reason, picks, model, snapshot, created_at
`

type InsertScoreFeedbackParams struct {
	UserID    pgtype.UUID
	JobID     pgtype.UUID
	Kind      string
	Direction pgtype.Text
	Reason    string
	Picks     []byte
	Model     string
	Snapshot  []byte
}

func (q *Queries) InsertScoreFeedback(ctx context.Context, arg InsertScoreFeedbackParams) (ScoreFeedback, error) {
	row := q.db.QueryRow(ctx, insertScoreFeedback,
		arg.UserID,
		arg.JobID,
		arg.Kind,
		arg.Direction,
		arg.Reason,
		arg.Picks,
		arg.Model,
		arg.Snapshot,
	)
	var i ScoreFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Kind,
		&i.Direction,
		&i.Reason,
		&i.Picks,
		&i.Model,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}

const listScoreFeedback = `-- name: ListScoreFeedback :many
SELECT sf.id, sf.user_id, sf.job_id, sf.kind, sf.direction, sf.reason, sf.picks, sf.model, sf.snapshot, sf.created_at, d.picks_changed, d.model_changed
FROM score_feedback sf
CROSS JOIN LATERAL (
    SELECT sf.picks IS DISTINCT FROM COALESCE((SELECT preferences->'picks' FROM search_config WHERE user_id = sf.user_id), '[]'::jsonb) AS picks_changed,
           sf.model <> $1::text AS model_changed
) d
WHERE sf.user_id = $2
  AND ($3::text = '' OR sf.kind = $3::text)
  AND ($4::bool OR NOT (d.picks_changed OR d.model_changed))
ORDER BY sf.created_at DESC, sf.id DESC
LIMIT $6::int OFFSET $5::int
`

type ListScoreFeedbackParams struct {
	Model           string
	UserID          pgtype.UUID
	Kind            string
	IncludeOutdated bool
	RowOffset       int32
	RowLimit        int32
}

type ListScoreFeedbackRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	JobID        pgtype.UUID
	Kind         string
	Direction    pgtype.Text
	Reason       string
	Picks        []byte
	Model        string
	Snapshot     []byte
	CreatedAt    pgtype.Timestamptz
	PicksChanged bool
	ModelChanged bool
}

func (q *Queries) ListScoreFeedback(ctx context.Context, arg ListScoreFeedbackParams) ([]ListScoreFeedbackRow, error) {
	rows, err := q.db.Query(ctx, listScoreFeedback,
		arg.Model,
		arg.UserID,
		arg.Kind,
		arg.IncludeOutdated,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScoreFeedbackRow
	for rows.Next() {
		var i ListScoreFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Kind,
			&i.Direction,
			&i.Reason,
			&i.Picks,
			&i.Model,
			&i.Snapshot,
			&i.CreatedAt,
			&i.PicksChanged,
			&i.ModelChanged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
