// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scoring_options.sql

package sqlc

import (
	"context"
)

const insertScoringOption = `-- name: InsertScoringOption :exec
INSERT INTO scoring_options (id, dimension, label, question)
VALUES ($1::text, $2::scoring_dimension, $3::text, $4::text)
`

type InsertScoringOptionParams struct {
	ID        string
	Dimension ScoringDimension
	Label     string
	Question  string
}

func (q *Queries) InsertScoringOption(ctx context.Context, arg InsertScoringOptionParams) error {
	_, err := q.db.Exec(ctx, insertScoringOption,
		arg.ID,
		arg.Dimension,
		arg.Label,
		arg.Question,
	)
	return err
}

const listScoringOptions = `-- name: ListScoringOptions :many
SELECT id, dimension, label, question, retired_at FROM scoring_options ORDER BY dimension, id
`

func (q *Queries) ListScoringOptions(ctx context.Context) ([]ScoringOption, error) {
	rows, err := q.db.Query(ctx, listScoringOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoringOption
	for rows.Next() {
		var i ScoringOption
		if err := rows.Scan(
			&i.ID,
			&i.Dimension,
			&i.Label,
			&i.Question,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireScoringOption = `-- name: RetireScoringOption :execrows
UPDATE scoring_options SET retired_at = NOW() WHERE id = $1 AND retired_at IS NULL
`

func (q *Queries) RetireScoringOption(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, retireScoringOption, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rewordScoringOption = `-- name: RewordScoringOption :execrows
UPDATE scoring_options SET question = $1::text WHERE id = $2::text
`

type RewordScoringOptionParams struct {
	Question string
	ID       string
}

func (q *Queries) RewordScoringOption(ctx context.Context, arg RewordScoringOptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rewordScoringOption, arg.Question, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
