// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: score_feedback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearScoreFeedback = `-- name: ClearScoreFeedback :execrows
DELETE FROM score_feedback WHERE user_id = $1
`

func (q *Queries) ClearScoreFeedback(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearScoreFeedback, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertScoreFeedback = `-- name: InsertScoreFeedback :one
INSERT INTO score_feedback (user_id, kind, reason, picks, model, snapshot)
VALUES ($1, $2::text, $3::text, $4, $5::text, $6)
RETURNING id, user_id, job_id, kind, direction, reason, picks, model, snapshot, created_at
`

type InsertScoreFeedbackParams struct {
	UserID   pgtype.UUID
	Kind     string
	Reason   string
	Picks    []byte
	Model    string
	Snapshot []byte
}

func (q *Queries) InsertScoreFeedback(ctx context.Context, arg InsertScoreFeedbackParams) (ScoreFeedback, error) {
	row := q.db.QueryRow(ctx, insertScoreFeedback,
		arg.UserID,
		arg.Kind,
		arg.Reason,
		arg.Picks,
		arg.Model,
		arg.Snapshot,
	)
	var i ScoreFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Kind,
		&i.Direction,
		&i.Reason,
		&i.Picks,
		&i.Model,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}

const listScoreFeedback = `-- name: ListScoreFeedback :many
SELECT id, user_id, job_id, kind, direction, reason, picks, model, snapshot, created_at FROM score_feedback
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2::int
`

type ListScoreFeedbackParams struct {
	UserID   pgtype.UUID
	RowLimit int32
}

func (q *Queries) ListScoreFeedback(ctx context.Context, arg ListScoreFeedbackParams) ([]ScoreFeedback, error) {
	rows, err := q.db.Query(ctx, listScoreFeedback, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoreFeedback
	for rows.Next() {
		var i ScoreFeedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Kind,
			&i.Direction,
			&i.Reason,
			&i.Picks,
			&i.Model,
			&i.Snapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
