// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_config.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSearchConfig = `-- name: GetSearchConfig :one
SELECT id, user_id, excluded_title_keywords, excluded_companies, excluded_locations, required_locations, required_title_keywords, notify_threshold, preferences, created_at, updated_at FROM search_config WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSearchConfig(ctx context.Context, userID pgtype.UUID) (SearchConfig, error) {
	row := q.db.QueryRow(ctx, getSearchConfig, userID)
	var i SearchConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExcludedTitleKeywords,
		&i.ExcludedCompanies,
		&i.ExcludedLocations,
		&i.RequiredLocations,
		&i.RequiredTitleKeywords,
		&i.NotifyThreshold,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSearchConfig = `-- name: UpsertSearchConfig :one
INSERT INTO search_config (user_id, excluded_title_keywords, excluded_companies, excluded_locations, required_locations, required_title_keywords, notify_threshold, preferences)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE SET
    excluded_title_keywords = EXCLUDED.excluded_title_keywords,
    excluded_companies      = EXCLUDED.excluded_companies,
    excluded_locations      = EXCLUDED.excluded_locations,
    required_locations      = EXCLUDED.required_locations,
    required_title_keywords = EXCLUDED.required_title_keywords,
    notify_threshold        = EXCLUDED.notify_threshold,
    preferences             = EXCLUDED.preferences,
    updated_at              = NOW()
RETURNING id, user_id, excluded_title_keywords, excluded_companies, excluded_locations, required_locations, required_title_keywords, notify_threshold, preferences, created_at, updated_at
`

type UpsertSearchConfigParams struct {
	UserID                pgtype.UUID
	ExcludedTitleKeywords []string
	ExcludedCompanies     []string
	ExcludedLocations     []string
	RequiredLocations     []string
	RequiredTitleKeywords []string
	NotifyThreshold       int32
	Preferences           []byte
}

func (q *Queries) UpsertSearchConfig(ctx context.Context, arg UpsertSearchConfigParams) (SearchConfig, error) {
	row := q.db.QueryRow(ctx, upsertSearchConfig,
		arg.UserID,
		arg.ExcludedTitleKeywords,
		arg.ExcludedCompanies,
		arg.ExcludedLocations,
		arg.RequiredLocations,
		arg.RequiredTitleKeywords,
		arg.NotifyThreshold,
		arg.Preferences,
	)
	var i SearchConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExcludedTitleKeywords,
		&i.ExcludedCompanies,
		&i.ExcludedLocations,
		&i.RequiredLocations,
		&i.RequiredTitleKeywords,
		&i.NotifyThreshold,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
