// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_config.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addExcludedCompany = `-- name: AddExcludedCompany :one
INSERT INTO search_config (user_id, excluded_companies)
VALUES ($1, ARRAY[$2::text])
ON CONFLICT (user_id) DO UPDATE SET
    excluded_companies = array_append(search_config.excluded_companies, $2::text),
    updated_at         = NOW()
WHERE NOT ($2::text = ANY(search_config.excluded_companies))
RETURNING user_id
`

type AddExcludedCompanyParams struct {
	UserID pgtype.UUID
	Name   string
}

func (q *Queries) AddExcludedCompany(ctx context.Context, arg AddExcludedCompanyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, addExcludedCompany, arg.UserID, arg.Name)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getSearchConfig = `-- name: GetSearchConfig :one
SELECT id, user_id, excluded_title_keywords, excluded_companies, excluded_locations, required_locations, required_title_keywords, notify_threshold, preferences, created_at, updated_at FROM search_config WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSearchConfig(ctx context.Context, userID pgtype.UUID) (SearchConfig, error) {
	row := q.db.QueryRow(ctx, getSearchConfig, userID)
	var i SearchConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExcludedTitleKeywords,
		&i.ExcludedCompanies,
		&i.ExcludedLocations,
		&i.RequiredLocations,
		&i.RequiredTitleKeywords,
		&i.NotifyThreshold,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncludeFilterConfigs = `-- name: ListIncludeFilterConfigs :many
SELECT id, user_id, excluded_title_keywords, excluded_companies, excluded_locations, required_locations, required_title_keywords, notify_threshold, preferences, created_at, updated_at FROM search_config
WHERE cardinality(required_locations) > 0 OR cardinality(required_title_keywords) > 0
`

func (q *Queries) ListIncludeFilterConfigs(ctx context.Context) ([]SearchConfig, error) {
	rows, err := q.db.Query(ctx, listIncludeFilterConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchConfig
	for rows.Next() {
		var i SearchConfig
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExcludedTitleKeywords,
			&i.ExcludedCompanies,
			&i.ExcludedLocations,
			&i.RequiredLocations,
			&i.RequiredTitleKeywords,
			&i.NotifyThreshold,
			&i.Preferences,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeExcludedCompany = `-- name: RemoveExcludedCompany :exec
UPDATE search_config
SET excluded_companies = array_remove(excluded_companies, $1::text),
    updated_at         = NOW()
WHERE user_id = $2 AND $1::text = ANY(excluded_companies)
`

type RemoveExcludedCompanyParams struct {
	Name   string
	UserID pgtype.UUID
}

func (q *Queries) RemoveExcludedCompany(ctx context.Context, arg RemoveExcludedCompanyParams) error {
	_, err := q.db.Exec(ctx, removeExcludedCompany, arg.Name, arg.UserID)
	return err
}

const upsertSearchConfig = `-- name: UpsertSearchConfig :one
INSERT INTO search_config (user_id, excluded_title_keywords, excluded_companies, excluded_locations, required_locations, required_title_keywords, notify_threshold, preferences)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE SET
    excluded_title_keywords = EXCLUDED.excluded_title_keywords,
    excluded_companies      = EXCLUDED.excluded_companies,
    excluded_locations      = EXCLUDED.excluded_locations,
    required_locations      = EXCLUDED.required_locations,
    required_title_keywords = EXCLUDED.required_title_keywords,
    notify_threshold        = EXCLUDED.notify_threshold,
    preferences             = EXCLUDED.preferences,
    updated_at              = NOW()
RETURNING id, user_id, excluded_title_keywords, excluded_companies, excluded_locations, required_locations, required_title_keywords, notify_threshold, preferences, created_at, updated_at
`

type UpsertSearchConfigParams struct {
	UserID                pgtype.UUID
	ExcludedTitleKeywords []string
	ExcludedCompanies     []string
	ExcludedLocations     []string
	RequiredLocations     []string
	RequiredTitleKeywords []string
	NotifyThreshold       int32
	Preferences           []byte
}

func (q *Queries) UpsertSearchConfig(ctx context.Context, arg UpsertSearchConfigParams) (SearchConfig, error) {
	row := q.db.QueryRow(ctx, upsertSearchConfig,
		arg.UserID,
		arg.ExcludedTitleKeywords,
		arg.ExcludedCompanies,
		arg.ExcludedLocations,
		arg.RequiredLocations,
		arg.RequiredTitleKeywords,
		arg.NotifyThreshold,
		arg.Preferences,
	)
	var i SearchConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExcludedTitleKeywords,
		&i.ExcludedCompanies,
		&i.ExcludedLocations,
		&i.RequiredLocations,
		&i.RequiredTitleKeywords,
		&i.NotifyThreshold,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
