// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suitability.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAnswersForJobs = `-- name: DeleteAnswersForJobs :exec
DELETE FROM option_answers WHERE job_id = ANY($1::uuid[])
`

func (q *Queries) DeleteAnswersForJobs(ctx context.Context, jobIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnswersForJobs, jobIds)
	return err
}

const dropStaleAnswers = `-- name: DropStaleAnswers :exec
DELETE FROM option_answers
USING jobs j
WHERE option_answers.job_id = j.id
    AND option_answers.job_id = ANY($1::uuid[])
    AND option_answers.fingerprint != j.content_fingerprint
`

func (q *Queries) DropStaleAnswers(ctx context.Context, jobIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, dropStaleAnswers, jobIds)
	return err
}

const getJobForScoring = `-- name: GetJobForScoring :one
SELECT id, title, location, url, company_slug, source, updated_at, scraped_at, description,
    salary_raw, work_arrangement, company_id, primary_board_id, provider_posting_id, content_fingerprint
FROM jobs WHERE id = $1
`

type GetJobForScoringRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	Description        string
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
}

func (q *Queries) GetJobForScoring(ctx context.Context, id pgtype.UUID) (GetJobForScoringRow, error) {
	row := q.db.QueryRow(ctx, getJobForScoring, id)
	var i GetJobForScoringRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.CompanySlug,
		&i.Source,
		&i.UpdatedAt,
		&i.ScrapedAt,
		&i.Description,
		&i.SalaryRaw,
		&i.WorkArrangement,
		&i.CompanyID,
		&i.PrimaryBoardID,
		&i.ProviderPostingID,
		&i.ContentFingerprint,
	)
	return i, err
}

const getScoringStatus = `-- name: GetScoringStatus :one
SELECT count(*) AS pending
FROM effect_outbox e
JOIN job_scores s ON s.job_id = e.job_id AND s.user_id = $1::uuid
WHERE e.status IN ('pending', 'running')
`

func (q *Queries) GetScoringStatus(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getScoringStatus, userID)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const insertOptionAnswer = `-- name: InsertOptionAnswer :exec
INSERT INTO option_answers (job_id, fingerprint, question_hash, model, p_yes, p_no, p_not_stated, confidence)
VALUES ($1::uuid, $2::text, $3::text, $4::text,
    $5::real, $6::real, $7::real, $8::real)
ON CONFLICT (job_id, fingerprint, question_hash, model) DO NOTHING
`

type InsertOptionAnswerParams struct {
	JobID        pgtype.UUID
	Fingerprint  string
	QuestionHash string
	Model        string
	PYes         float32
	PNo          float32
	PNotStated   float32
	Confidence   float32
}

func (q *Queries) InsertOptionAnswer(ctx context.Context, arg InsertOptionAnswerParams) error {
	_, err := q.db.Exec(ctx, insertOptionAnswer,
		arg.JobID,
		arg.Fingerprint,
		arg.QuestionHash,
		arg.Model,
		arg.PYes,
		arg.PNo,
		arg.PNotStated,
		arg.Confidence,
	)
	return err
}

const listCompanyJobAnswers = `-- name: ListCompanyJobAnswers :many
SELECT j.id AS job_id, a.question_hash, a.p_yes, a.p_no, a.p_not_stated, a.confidence
FROM jobs j
JOIN option_answers a ON a.job_id = j.id AND a.fingerprint = j.content_fingerprint
WHERE j.company_id = ANY($1::uuid[]) AND j.closed_at IS NULL AND a.model = $2::text
`

type ListCompanyJobAnswersParams struct {
	CompanyIds []pgtype.UUID
	Model      string
}

type ListCompanyJobAnswersRow struct {
	JobID        pgtype.UUID
	QuestionHash string
	PYes         float32
	PNo          float32
	PNotStated   float32
	Confidence   float32
}

func (q *Queries) ListCompanyJobAnswers(ctx context.Context, arg ListCompanyJobAnswersParams) ([]ListCompanyJobAnswersRow, error) {
	rows, err := q.db.Query(ctx, listCompanyJobAnswers, arg.CompanyIds, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyJobAnswersRow
	for rows.Next() {
		var i ListCompanyJobAnswersRow
		if err := rows.Scan(
			&i.JobID,
			&i.QuestionHash,
			&i.PYes,
			&i.PNo,
			&i.PNotStated,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterestedConfigs = `-- name: ListInterestedConfigs :many
SELECT u.id AS user_id,
    COALESCE(sc.excluded_title_keywords, '{}')::text[] AS excluded_title_keywords,
    COALESCE(sc.excluded_companies, '{}')::text[] AS excluded_companies,
    COALESCE(sc.excluded_locations, '{}')::text[] AS excluded_locations,
    COALESCE(sc.required_locations, '{}')::text[] AS required_locations,
    COALESCE(sc.required_title_keywords, '{}')::text[] AS required_title_keywords,
    COALESCE(sc.notify_threshold, 70) AS notify_threshold,
    COALESCE(sc.preferences, '{}'::jsonb) AS preferences,
    EXISTS (
        SELECT 1 FROM tracked_companies tc JOIN companies c ON c.id = tc.company_id
        WHERE tc.user_id = u.id AND tc.enabled AND tc.review_state = 'new'
          AND (c.id = j.company_id OR c.slug = j.company_slug)
    ) AS company_is_new
FROM users u
LEFT JOIN search_config sc ON sc.user_id = u.id
JOIN jobs j ON j.id = $1::uuid
WHERE EXISTS (
    SELECT 1 FROM tracked_companies tc JOIN companies c ON c.id = tc.company_id
    WHERE tc.user_id = u.id AND tc.enabled AND (c.id = j.company_id OR c.slug = j.company_slug)
) OR EXISTS (
    SELECT 1 FROM source_targets st WHERE st.user_id = u.id AND st.enabled AND st.source = j.source
)
`

type ListInterestedConfigsRow struct {
	UserID                pgtype.UUID
	ExcludedTitleKeywords []string
	ExcludedCompanies     []string
	ExcludedLocations     []string
	RequiredLocations     []string
	RequiredTitleKeywords []string
	NotifyThreshold       int32
	Preferences           []byte
	CompanyIsNew          bool
}

func (q *Queries) ListInterestedConfigs(ctx context.Context, jobID pgtype.UUID) ([]ListInterestedConfigsRow, error) {
	rows, err := q.db.Query(ctx, listInterestedConfigs, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInterestedConfigsRow
	for rows.Next() {
		var i ListInterestedConfigsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ExcludedTitleKeywords,
			&i.ExcludedCompanies,
			&i.ExcludedLocations,
			&i.RequiredLocations,
			&i.RequiredTitleKeywords,
			&i.NotifyThreshold,
			&i.Preferences,
			&i.CompanyIsNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCompanyJobs = `-- name: ListOpenCompanyJobs :many
SELECT id, company_id FROM jobs
WHERE company_id = ANY($1::uuid[]) AND closed_at IS NULL
`

type ListOpenCompanyJobsRow struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
}

func (q *Queries) ListOpenCompanyJobs(ctx context.Context, companyIds []pgtype.UUID) ([]ListOpenCompanyJobsRow, error) {
	rows, err := q.db.Query(ctx, listOpenCompanyJobs, companyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenCompanyJobsRow
	for rows.Next() {
		var i ListOpenCompanyJobsRow
		if err := rows.Scan(&i.ID, &i.CompanyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionAnswers = `-- name: ListOptionAnswers :many
SELECT question_hash, p_yes, p_no, p_not_stated, confidence
FROM option_answers
WHERE job_id = $1::uuid AND fingerprint = $2::text AND model = $3::text
`

type ListOptionAnswersParams struct {
	JobID       pgtype.UUID
	Fingerprint string
	Model       string
}

type ListOptionAnswersRow struct {
	QuestionHash string
	PYes         float32
	PNo          float32
	PNotStated   float32
	Confidence   float32
}

func (q *Queries) ListOptionAnswers(ctx context.Context, arg ListOptionAnswersParams) ([]ListOptionAnswersRow, error) {
	rows, err := q.db.Query(ctx, listOptionAnswers, arg.JobID, arg.Fingerprint, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOptionAnswersRow
	for rows.Next() {
		var i ListOptionAnswersRow
		if err := rows.Scan(
			&i.QuestionHash,
			&i.PYes,
			&i.PNo,
			&i.PNotStated,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoringAnswersForUser = `-- name: ListScoringAnswersForUser :many
SELECT j.id AS job_id, a.question_hash, a.p_yes, a.p_no, a.p_not_stated, a.confidence
FROM job_scores s
JOIN jobs j ON j.id = s.job_id
JOIN option_answers a ON a.job_id = j.id AND a.fingerprint = j.content_fingerprint
WHERE s.user_id = $1::uuid AND a.model = $2::text
`

type ListScoringAnswersForUserParams struct {
	UserID pgtype.UUID
	Model  string
}

type ListScoringAnswersForUserRow struct {
	JobID        pgtype.UUID
	QuestionHash string
	PYes         float32
	PNo          float32
	PNotStated   float32
	Confidence   float32
}

func (q *Queries) ListScoringAnswersForUser(ctx context.Context, arg ListScoringAnswersForUserParams) ([]ListScoringAnswersForUserRow, error) {
	rows, err := q.db.Query(ctx, listScoringAnswersForUser, arg.UserID, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScoringAnswersForUserRow
	for rows.Next() {
		var i ListScoringAnswersForUserRow
		if err := rows.Scan(
			&i.JobID,
			&i.QuestionHash,
			&i.PYes,
			&i.PNo,
			&i.PNotStated,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoringInputJobs = `-- name: ListScoringInputJobs :many
SELECT j.id, j.title, j.location, j.url, j.company_slug, j.source, j.updated_at, j.scraped_at,
    j.description, j.salary_raw, j.work_arrangement, j.company_id, j.primary_board_id,
    j.provider_posting_id, j.content_fingerprint
FROM job_scores s JOIN jobs j ON j.id = s.job_id
WHERE s.user_id = $1::uuid
`

type ListScoringInputJobsRow struct {
	ID                 pgtype.UUID
	Title              string
	Location           string
	Url                string
	CompanySlug        string
	Source             string
	UpdatedAt          pgtype.Timestamptz
	ScrapedAt          pgtype.Timestamptz
	Description        string
	SalaryRaw          string
	WorkArrangement    string
	CompanyID          pgtype.UUID
	PrimaryBoardID     pgtype.UUID
	ProviderPostingID  pgtype.Text
	ContentFingerprint pgtype.Text
}

func (q *Queries) ListScoringInputJobs(ctx context.Context, userID pgtype.UUID) ([]ListScoringInputJobsRow, error) {
	rows, err := q.db.Query(ctx, listScoringInputJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScoringInputJobsRow
	for rows.Next() {
		var i ListScoringInputJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.CompanySlug,
			&i.Source,
			&i.UpdatedAt,
			&i.ScrapedAt,
			&i.Description,
			&i.SalaryRaw,
			&i.WorkArrangement,
			&i.CompanyID,
			&i.PrimaryBoardID,
			&i.ProviderPostingID,
			&i.ContentFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobScoreBreakdown = `-- name: UpdateJobScoreBreakdown :exec
UPDATE job_scores SET suitability_score = $1::int, breakdown = $2::jsonb, updated_at = NOW()
WHERE job_id = $3::uuid AND user_id = $4::uuid
`

type UpdateJobScoreBreakdownParams struct {
	Score     int32
	Breakdown []byte
	JobID     pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) UpdateJobScoreBreakdown(ctx context.Context, arg UpdateJobScoreBreakdownParams) error {
	_, err := q.db.Exec(ctx, updateJobScoreBreakdown,
		arg.Score,
		arg.Breakdown,
		arg.JobID,
		arg.UserID,
	)
	return err
}

const upsertJobScore = `-- name: UpsertJobScore :exec
INSERT INTO job_scores (job_id, user_id, suitability_score, breakdown, cost, score_fingerprint, score_model)
VALUES ($1::uuid, $2::uuid, $3::int, $4::jsonb,
    $5::numeric, $6::text, $7::text)
ON CONFLICT (job_id, user_id) DO UPDATE SET
    suitability_score = EXCLUDED.suitability_score, breakdown = EXCLUDED.breakdown, cost = EXCLUDED.cost,
    score_fingerprint = EXCLUDED.score_fingerprint, score_model = EXCLUDED.score_model, updated_at = NOW()
`

type UpsertJobScoreParams struct {
	JobID       pgtype.UUID
	UserID      pgtype.UUID
	Score       int32
	Breakdown   []byte
	Cost        pgtype.Numeric
	Fingerprint string
	Model       string
}

func (q *Queries) UpsertJobScore(ctx context.Context, arg UpsertJobScoreParams) error {
	_, err := q.db.Exec(ctx, upsertJobScore,
		arg.JobID,
		arg.UserID,
		arg.Score,
		arg.Breakdown,
		arg.Cost,
		arg.Fingerprint,
		arg.Model,
	)
	return err
}
