// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank_skills.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBankSkill = `-- name: CreateBankSkill :one
INSERT INTO bank_skills (user_id, name, category, sort_order)
VALUES (
    $1, $2, $3,
    (SELECT COALESCE(MAX(s.sort_order), 0) + 1 FROM bank_skills s WHERE s.user_id = $1)
)
RETURNING id, user_id, name, category, sort_order, created_at, updated_at
`

type CreateBankSkillParams struct {
	UserID   pgtype.UUID
	Name     string
	Category string
}

func (q *Queries) CreateBankSkill(ctx context.Context, arg CreateBankSkillParams) (BankSkill, error) {
	row := q.db.QueryRow(ctx, createBankSkill, arg.UserID, arg.Name, arg.Category)
	var i BankSkill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBankSkill = `-- name: DeleteBankSkill :execrows
DELETE FROM bank_skills WHERE user_id = $1 AND id = $2
`

type DeleteBankSkillParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) DeleteBankSkill(ctx context.Context, arg DeleteBankSkillParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBankSkill, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBankSkills = `-- name: ListBankSkills :many
SELECT id, user_id, name, category, sort_order, created_at, updated_at FROM bank_skills
WHERE user_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListBankSkills(ctx context.Context, userID pgtype.UUID) ([]BankSkill, error) {
	rows, err := q.db.Query(ctx, listBankSkills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankSkill
	for rows.Next() {
		var i BankSkill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Category,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderBankSkills = `-- name: ReorderBankSkills :execrows
UPDATE bank_skills s
SET sort_order = o.ord::int
FROM unnest($2::uuid[]) WITH ORDINALITY AS o(id, ord)
WHERE s.user_id = $1 AND s.id = o.id
`

type ReorderBankSkillsParams struct {
	UserID pgtype.UUID
	Ids    []pgtype.UUID
}

func (q *Queries) ReorderBankSkills(ctx context.Context, arg ReorderBankSkillsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderBankSkills, arg.UserID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBankSkill = `-- name: UpdateBankSkill :one
UPDATE bank_skills
SET name = $1, category = $2, updated_at = NOW()
WHERE user_id = $3 AND id = $4
RETURNING id, user_id, name, category, sort_order, created_at, updated_at
`

type UpdateBankSkillParams struct {
	Name     string
	Category string
	UserID   pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) UpdateBankSkill(ctx context.Context, arg UpdateBankSkillParams) (BankSkill, error) {
	row := q.db.QueryRow(ctx, updateBankSkill,
		arg.Name,
		arg.Category,
		arg.UserID,
		arg.ID,
	)
	var i BankSkill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
