// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertBulletLabels implements pgx.CopyFromSource.
type iteratorForInsertBulletLabels struct {
	rows                 []InsertBulletLabelsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertBulletLabels) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertBulletLabels) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].JobID,
		r.rows[0].DraftID,
		r.rows[0].Kind,
		r.rows[0].AchievementID,
		r.rows[0].PYes,
		r.rows[0].PNo,
		r.rows[0].PNotStated,
		r.rows[0].Confidence,
		r.rows[0].Preselected,
		r.rows[0].Kept,
	}, nil
}

func (r iteratorForInsertBulletLabels) Err() error {
	return nil
}

func (q *Queries) InsertBulletLabels(ctx context.Context, arg []InsertBulletLabelsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"preference_labels"}, []string{"user_id", "job_id", "draft_id", "kind", "achievement_id", "p_yes", "p_no", "p_not_stated", "confidence", "preselected", "kept"}, &iteratorForInsertBulletLabels{rows: arg})
}
