// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drafts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDraft = `-- name: ClaimDraft :one
WITH next AS (
    SELECT id FROM tailored_cvs
    WHERE (status = 'pending' AND due_at <= NOW())
       OR (status = 'running' AND lease_until <= NOW())
       OR (status = 'keeping' AND due_at <= NOW() AND (lease_until IS NULL OR lease_until <= NOW()))
    ORDER BY due_at, id LIMIT 1 FOR UPDATE SKIP LOCKED
)
UPDATE tailored_cvs t SET status = CASE WHEN t.status = 'keeping' THEN 'keeping' ELSE 'running' END, attempts = t.attempts + 1,
    lease_until = NOW() + interval '5 minutes'
FROM next, jobs j
LEFT JOIN companies c ON c.id = j.company_id
WHERE t.id = next.id AND j.id = t.job_id
RETURNING t.id, t.user_id, t.job_id, t.base_doc_id, t.base_tab_id, t.achievement_ids, t.attempts,
    COALESCE(t.draft_doc_id, '')::text AS draft_doc_id,
    t.status = 'keeping' AS keeping,
    j.title AS job_title,
    COALESCE(c.name, j.company_slug)::text AS company_name,
    j.description AS job_description,
    COALESCE(j.content_fingerprint, '')::text AS job_fingerprint
`

type ClaimDraftRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	JobID          pgtype.UUID
	BaseDocID      string
	BaseTabID      string
	AchievementIds []pgtype.UUID
	Attempts       int32
	DraftDocID     string
	Keeping        bool
	JobTitle       string
	CompanyName    string
	JobDescription string
	JobFingerprint string
}

func (q *Queries) ClaimDraft(ctx context.Context) (ClaimDraftRow, error) {
	row := q.db.QueryRow(ctx, claimDraft)
	var i ClaimDraftRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.BaseDocID,
		&i.BaseTabID,
		&i.AchievementIds,
		&i.Attempts,
		&i.DraftDocID,
		&i.Keeping,
		&i.JobTitle,
		&i.CompanyName,
		&i.JobDescription,
		&i.JobFingerprint,
	)
	return i, err
}

const completeDraft = `-- name: CompleteDraft :execrows
UPDATE tailored_cvs SET status = 'ready', lease_until = NULL, last_error = '',
    edit_set = $1::jsonb, base_content = $2::jsonb, raw_output = $3::text,
    model = $4::text, prompt_version = $5::text,
    job_fingerprint = $6::text, cost = $7::real,
    draft_doc_id = $8::text, findings = $9::jsonb
WHERE id = $10::uuid AND attempts = $11::int AND status = 'running'
`

type CompleteDraftParams struct {
	EditSet        []byte
	BaseContent    []byte
	RawOutput      string
	Model          string
	PromptVersion  string
	JobFingerprint string
	Cost           float32
	DraftDocID     string
	Findings       []byte
	ID             pgtype.UUID
	Attempts       int32
}

func (q *Queries) CompleteDraft(ctx context.Context, arg CompleteDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeDraft,
		arg.EditSet,
		arg.BaseContent,
		arg.RawOutput,
		arg.Model,
		arg.PromptVersion,
		arg.JobFingerprint,
		arg.Cost,
		arg.DraftDocID,
		arg.Findings,
		arg.ID,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeKeep = `-- name: CompleteKeep :execrows
UPDATE tailored_cvs SET status = 'ready', outcome = 'kept', kept_as = 'doc', lease_until = NULL, last_error = ''
WHERE id = $1::uuid AND attempts = $2::int AND status = 'keeping'
`

type CompleteKeepParams struct {
	ID       pgtype.UUID
	Attempts int32
}

func (q *Queries) CompleteKeep(ctx context.Context, arg CompleteKeepParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeKeep, arg.ID, arg.Attempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failDraft = `-- name: FailDraft :execrows
UPDATE tailored_cvs SET
    status = CASE WHEN $1::bool OR attempts >= $2::int THEN 'failed' ELSE 'pending' END,
    due_at = NOW() + make_interval(secs => LEAST(3600, 30 * power(2, attempts)::int)),
    lease_until = NULL,
    last_error = $3::text,
    draft_doc_id = CASE WHEN $4::bool THEN NULL ELSE draft_doc_id END
WHERE id = $5::uuid AND attempts = $6::int AND status = 'running'
`

type FailDraftParams struct {
	Terminal    bool
	MaxAttempts int32
	LastError   string
	ClearDoc    bool
	ID          pgtype.UUID
	Attempts    int32
}

func (q *Queries) FailDraft(ctx context.Context, arg FailDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, failDraft,
		arg.Terminal,
		arg.MaxAttempts,
		arg.LastError,
		arg.ClearDoc,
		arg.ID,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failKeep = `-- name: FailKeep :execrows
UPDATE tailored_cvs SET
    status = CASE WHEN $1::bool OR attempts >= $2::int THEN 'ready' ELSE 'keeping' END,
    due_at = NOW() + make_interval(secs => LEAST(3600, 30 * power(2, attempts)::int)),
    lease_until = NULL,
    last_error = $3::text
WHERE id = $4::uuid AND attempts = $5::int AND status = 'keeping'
`

type FailKeepParams struct {
	Terminal    bool
	MaxAttempts int32
	LastError   string
	ID          pgtype.UUID
	Attempts    int32
}

func (q *Queries) FailKeep(ctx context.Context, arg FailKeepParams) (int64, error) {
	result, err := q.db.Exec(ctx, failKeep,
		arg.Terminal,
		arg.MaxAttempts,
		arg.LastError,
		arg.ID,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDraft = `-- name: GetDraft :one
SELECT id, user_id, job_id, base_doc_id, base_tab_id, achievement_ids, edit_set, base_content, findings, raw_output, model, prompt_version, job_fingerprint, cost, draft_doc_id, status, outcome, kept_as, keep_note, attempts, due_at, lease_until, last_error, created_at FROM tailored_cvs WHERE id = $1 AND user_id = $2
`

type GetDraftParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetDraft(ctx context.Context, arg GetDraftParams) (TailoredCv, error) {
	row := q.db.QueryRow(ctx, getDraft, arg.ID, arg.UserID)
	var i TailoredCv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.BaseDocID,
		&i.BaseTabID,
		&i.AchievementIds,
		&i.EditSet,
		&i.BaseContent,
		&i.Findings,
		&i.RawOutput,
		&i.Model,
		&i.PromptVersion,
		&i.JobFingerprint,
		&i.Cost,
		&i.DraftDocID,
		&i.Status,
		&i.Outcome,
		&i.KeptAs,
		&i.KeepNote,
		&i.Attempts,
		&i.DueAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const insertDraft = `-- name: InsertDraft :one
INSERT INTO tailored_cvs (user_id, job_id, base_doc_id, base_tab_id, achievement_ids)
SELECT $1::uuid, j.id, $2::text, $3::text, $4::uuid[]
FROM jobs j WHERE j.id = $5::uuid
RETURNING id, user_id, job_id, base_doc_id, base_tab_id, achievement_ids, edit_set, base_content, findings, raw_output, model, prompt_version, job_fingerprint, cost, draft_doc_id, status, outcome, kept_as, keep_note, attempts, due_at, lease_until, last_error, created_at
`

type InsertDraftParams struct {
	UserID         pgtype.UUID
	BaseDocID      string
	BaseTabID      string
	AchievementIds []pgtype.UUID
	JobID          pgtype.UUID
}

func (q *Queries) InsertDraft(ctx context.Context, arg InsertDraftParams) (TailoredCv, error) {
	row := q.db.QueryRow(ctx, insertDraft,
		arg.UserID,
		arg.BaseDocID,
		arg.BaseTabID,
		arg.AchievementIds,
		arg.JobID,
	)
	var i TailoredCv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.BaseDocID,
		&i.BaseTabID,
		&i.AchievementIds,
		&i.EditSet,
		&i.BaseContent,
		&i.Findings,
		&i.RawOutput,
		&i.Model,
		&i.PromptVersion,
		&i.JobFingerprint,
		&i.Cost,
		&i.DraftDocID,
		&i.Status,
		&i.Outcome,
		&i.KeptAs,
		&i.KeepNote,
		&i.Attempts,
		&i.DueAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const listJobDrafts = `-- name: ListJobDrafts :many
SELECT id, user_id, job_id, base_doc_id, base_tab_id, achievement_ids, edit_set, base_content, findings, raw_output, model, prompt_version, job_fingerprint, cost, draft_doc_id, status, outcome, kept_as, keep_note, attempts, due_at, lease_until, last_error, created_at FROM tailored_cvs WHERE job_id = $1 AND user_id = $2 ORDER BY created_at DESC, id
`

type ListJobDraftsParams struct {
	JobID  pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) ListJobDrafts(ctx context.Context, arg ListJobDraftsParams) ([]TailoredCv, error) {
	rows, err := q.db.Query(ctx, listJobDrafts, arg.JobID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TailoredCv
	for rows.Next() {
		var i TailoredCv
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.BaseDocID,
			&i.BaseTabID,
			&i.AchievementIds,
			&i.EditSet,
			&i.BaseContent,
			&i.Findings,
			&i.RawOutput,
			&i.Model,
			&i.PromptVersion,
			&i.JobFingerprint,
			&i.Cost,
			&i.DraftDocID,
			&i.Status,
			&i.Outcome,
			&i.KeptAs,
			&i.KeepNote,
			&i.Attempts,
			&i.DueAt,
			&i.LeaseUntil,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueKeep = `-- name: QueueKeep :one
UPDATE tailored_cvs SET status = 'keeping', attempts = 0, due_at = NOW(), lease_until = NULL, last_error = ''
WHERE id = $1 AND user_id = $2 AND status = 'ready' AND outcome IS NULL
RETURNING id, user_id, job_id, base_doc_id, base_tab_id, achievement_ids, edit_set, base_content, findings, raw_output, model, prompt_version, job_fingerprint, cost, draft_doc_id, status, outcome, kept_as, keep_note, attempts, due_at, lease_until, last_error, created_at
`

type QueueKeepParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) QueueKeep(ctx context.Context, arg QueueKeepParams) (TailoredCv, error) {
	row := q.db.QueryRow(ctx, queueKeep, arg.ID, arg.UserID)
	var i TailoredCv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.BaseDocID,
		&i.BaseTabID,
		&i.AchievementIds,
		&i.EditSet,
		&i.BaseContent,
		&i.Findings,
		&i.RawOutput,
		&i.Model,
		&i.PromptVersion,
		&i.JobFingerprint,
		&i.Cost,
		&i.DraftDocID,
		&i.Status,
		&i.Outcome,
		&i.KeptAs,
		&i.KeepNote,
		&i.Attempts,
		&i.DueAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const setDraftDoc = `-- name: SetDraftDoc :exec
UPDATE tailored_cvs SET draft_doc_id = $1::text
WHERE id = $2::uuid AND attempts = $3::int AND status = 'running'
`

type SetDraftDocParams struct {
	DraftDocID string
	ID         pgtype.UUID
	Attempts   int32
}

func (q *Queries) SetDraftDoc(ctx context.Context, arg SetDraftDocParams) error {
	_, err := q.db.Exec(ctx, setDraftDoc, arg.DraftDocID, arg.ID, arg.Attempts)
	return err
}

const setDraftEdits = `-- name: SetDraftEdits :execrows
UPDATE tailored_cvs SET edit_set = $1::jsonb, findings = $2::jsonb
WHERE id = $3::uuid AND user_id = $4::uuid
`

type SetDraftEditsParams struct {
	EditSet  []byte
	Findings []byte
	ID       pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) SetDraftEdits(ctx context.Context, arg SetDraftEditsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDraftEdits,
		arg.EditSet,
		arg.Findings,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDraftOutcome = `-- name: SetDraftOutcome :one
UPDATE tailored_cvs SET outcome = $1::text,
    draft_doc_id = CASE WHEN $1::text = 'discarded' THEN NULL ELSE draft_doc_id END
WHERE id = $2::uuid AND user_id = $3::uuid
RETURNING id, user_id, job_id, base_doc_id, base_tab_id, achievement_ids, edit_set, base_content, findings, raw_output, model, prompt_version, job_fingerprint, cost, draft_doc_id, status, outcome, kept_as, keep_note, attempts, due_at, lease_until, last_error, created_at
`

type SetDraftOutcomeParams struct {
	Outcome string
	ID      pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) SetDraftOutcome(ctx context.Context, arg SetDraftOutcomeParams) (TailoredCv, error) {
	row := q.db.QueryRow(ctx, setDraftOutcome, arg.Outcome, arg.ID, arg.UserID)
	var i TailoredCv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.BaseDocID,
		&i.BaseTabID,
		&i.AchievementIds,
		&i.EditSet,
		&i.BaseContent,
		&i.Findings,
		&i.RawOutput,
		&i.Model,
		&i.PromptVersion,
		&i.JobFingerprint,
		&i.Cost,
		&i.DraftDocID,
		&i.Status,
		&i.Outcome,
		&i.KeptAs,
		&i.KeepNote,
		&i.Attempts,
		&i.DueAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}
