// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: experience.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAchievement = `-- name: CreateAchievement :one
INSERT INTO achievements (position_id, user_id, text, sort_order)
SELECT p.id, p.user_id, $1,
       (SELECT COALESCE(MAX(a.sort_order), 0) + 1 FROM achievements a WHERE a.position_id = p.id)
FROM positions p
WHERE p.user_id = $2 AND p.id = $3
RETURNING id, position_id, user_id, text, sort_order, created_at, updated_at
`

type CreateAchievementParams struct {
	Text       string
	UserID     pgtype.UUID
	PositionID pgtype.UUID
}

func (q *Queries) CreateAchievement(ctx context.Context, arg CreateAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, createAchievement, arg.Text, arg.UserID, arg.PositionID)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.UserID,
		&i.Text,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (user_id, employer, title, start_date, end_date, sort_order)
VALUES (
    $1, $2, $3, $4, $5,
    (SELECT COALESCE(MIN(p.sort_order), 1) - 1 FROM positions p WHERE p.user_id = $1)
)
RETURNING id, user_id, employer, title, start_date, end_date, sort_order, created_at, updated_at
`

type CreatePositionParams struct {
	UserID    pgtype.UUID
	Employer  string
	Title     string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.UserID,
		arg.Employer,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Employer,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAchievement = `-- name: DeleteAchievement :execrows
DELETE FROM achievements WHERE user_id = $1 AND id = $2
`

type DeleteAchievementParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) DeleteAchievement(ctx context.Context, arg DeleteAchievementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAchievement, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePosition = `-- name: DeletePosition :execrows
DELETE FROM positions WHERE user_id = $1 AND id = $2
`

type DeletePositionParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePosition, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPosition = `-- name: GetPosition :one
SELECT id, user_id, employer, title, start_date, end_date, sort_order, created_at, updated_at FROM positions WHERE user_id = $1 AND id = $2
`

type GetPositionParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, arg.UserID, arg.ID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Employer,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAchievements = `-- name: ListAchievements :many
SELECT id, position_id, user_id, text, sort_order, created_at, updated_at FROM achievements
WHERE user_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListAchievements(ctx context.Context, userID pgtype.UUID) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.UserID,
			&i.Text,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT id, user_id, employer, title, start_date, end_date, sort_order, created_at, updated_at FROM positions
WHERE user_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListPositions(ctx context.Context, userID pgtype.UUID) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Employer,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderAchievements = `-- name: ReorderAchievements :execrows
UPDATE achievements a
SET sort_order = o.ord::int
FROM unnest($3::uuid[]) WITH ORDINALITY AS o(id, ord)
WHERE a.user_id = $1 AND a.position_id = $2 AND a.id = o.id
`

type ReorderAchievementsParams struct {
	UserID     pgtype.UUID
	PositionID pgtype.UUID
	Ids        []pgtype.UUID
}

func (q *Queries) ReorderAchievements(ctx context.Context, arg ReorderAchievementsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderAchievements, arg.UserID, arg.PositionID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reorderPositions = `-- name: ReorderPositions :execrows
UPDATE positions p
SET sort_order = o.ord::int
FROM unnest($2::uuid[]) WITH ORDINALITY AS o(id, ord)
WHERE p.user_id = $1 AND p.id = o.id
`

type ReorderPositionsParams struct {
	UserID pgtype.UUID
	Ids    []pgtype.UUID
}

func (q *Queries) ReorderPositions(ctx context.Context, arg ReorderPositionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderPositions, arg.UserID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAchievement = `-- name: UpdateAchievement :one
UPDATE achievements
SET text = $1, updated_at = NOW()
WHERE user_id = $2 AND id = $3
RETURNING id, position_id, user_id, text, sort_order, created_at, updated_at
`

type UpdateAchievementParams struct {
	Text   string
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) UpdateAchievement(ctx context.Context, arg UpdateAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, updateAchievement, arg.Text, arg.UserID, arg.ID)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.UserID,
		&i.Text,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
SET employer = $1, title = $2,
    start_date = $3, end_date = $4, updated_at = NOW()
WHERE user_id = $5 AND id = $6
RETURNING id, user_id, employer, title, start_date, end_date, sort_order, created_at, updated_at
`

type UpdatePositionParams struct {
	Employer  string
	Title     string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	UserID    pgtype.UUID
	ID        pgtype.UUID
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition,
		arg.Employer,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
		arg.ID,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Employer,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
