// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: headings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listHeadingMappings = `-- name: ListHeadingMappings :many
SELECT user_id, doc_id, tab_id, heading_text, position_id, created_at, updated_at FROM cv_heading_mappings
WHERE user_id = $1 AND doc_id = $2 AND tab_id = $3
ORDER BY heading_text
`

type ListHeadingMappingsParams struct {
	UserID pgtype.UUID
	DocID  string
	TabID  string
}

func (q *Queries) ListHeadingMappings(ctx context.Context, arg ListHeadingMappingsParams) ([]CvHeadingMapping, error) {
	rows, err := q.db.Query(ctx, listHeadingMappings, arg.UserID, arg.DocID, arg.TabID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CvHeadingMapping
	for rows.Next() {
		var i CvHeadingMapping
		if err := rows.Scan(
			&i.UserID,
			&i.DocID,
			&i.TabID,
			&i.HeadingText,
			&i.PositionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHeadingMapping = `-- name: UpsertHeadingMapping :exec
INSERT INTO cv_heading_mappings (user_id, doc_id, tab_id, heading_text, position_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, doc_id, tab_id, heading_text)
DO UPDATE SET position_id = EXCLUDED.position_id, updated_at = NOW()
`

type UpsertHeadingMappingParams struct {
	UserID      pgtype.UUID
	DocID       string
	TabID       string
	HeadingText string
	PositionID  pgtype.UUID
}

func (q *Queries) UpsertHeadingMapping(ctx context.Context, arg UpsertHeadingMappingParams) error {
	_, err := q.db.Exec(ctx, upsertHeadingMapping,
		arg.UserID,
		arg.DocID,
		arg.TabID,
		arg.HeadingText,
		arg.PositionID,
	)
	return err
}
