-- Seeds the scoring_options bank. Idempotent (ON CONFLICT DO NOTHING) — safe to
-- rerun in any environment: just seed-scoring-options.

INSERT INTO scoring_options (id, dimension, label, question) VALUES
    ('tech:go', 'tech', 'Go', 'Does the role use Go?'),
    ('tech:python', 'tech', 'Python', 'Does the role use Python?'),
    ('tech:typescript', 'tech', 'TypeScript', 'Does the role use TypeScript?'),
    ('tech:javascript', 'tech', 'JavaScript', 'Does the role use JavaScript?'),
    ('tech:rust', 'tech', 'Rust', 'Does the role use Rust?'),
    ('tech:java', 'tech', 'Java', 'Does the role use Java?'),
    ('tech:kotlin', 'tech', 'Kotlin', 'Does the role use Kotlin?'),
    ('tech:scala', 'tech', 'Scala', 'Does the role use Scala?'),
    ('tech:c#', 'tech', 'C#', 'Does the role use C#?'),
    ('tech:-net', 'tech', '.NET', 'Does the role use .NET?'),
    ('tech:c++', 'tech', 'C++', 'Does the role use C++?'),
    ('tech:c', 'tech', 'C', 'Does the role use C?'),
    ('tech:ruby', 'tech', 'Ruby', 'Does the role use Ruby?'),
    ('tech:rails', 'tech', 'Rails', 'Does the role use Rails?'),
    ('tech:php', 'tech', 'PHP', 'Does the role use PHP?'),
    ('tech:laravel', 'tech', 'Laravel', 'Does the role use Laravel?'),
    ('tech:elixir', 'tech', 'Elixir', 'Does the role use Elixir?'),
    ('tech:erlang', 'tech', 'Erlang', 'Does the role use Erlang?'),
    ('tech:clojure', 'tech', 'Clojure', 'Does the role use Clojure?'),
    ('tech:haskell', 'tech', 'Haskell', 'Does the role use Haskell?'),
    ('tech:ocaml', 'tech', 'OCaml', 'Does the role use OCaml?'),
    ('tech:swift', 'tech', 'Swift', 'Does the role use Swift?'),
    ('tech:objective-c', 'tech', 'Objective-C', 'Does the role use Objective-C?'),
    ('tech:dart', 'tech', 'Dart', 'Does the role use Dart?'),
    ('tech:flutter', 'tech', 'Flutter', 'Does the role use Flutter?'),
    ('tech:zig', 'tech', 'Zig', 'Does the role use Zig?'),
    ('tech:lua', 'tech', 'Lua', 'Does the role use Lua?'),
    ('tech:r', 'tech', 'R', 'Does the role use R?'),
    ('tech:julia', 'tech', 'Julia', 'Does the role use Julia?'),
    ('tech:node-js', 'tech', 'Node.js', 'Does the role use Node.js?'),
    ('tech:deno', 'tech', 'Deno', 'Does the role use Deno?'),
    ('tech:bun', 'tech', 'Bun', 'Does the role use Bun?'),
    ('tech:react', 'tech', 'React', 'Does the role use React?'),
    ('tech:react-native', 'tech', 'React Native', 'Does the role use React Native?'),
    ('tech:next-js', 'tech', 'Next.js', 'Does the role use Next.js?'),
    ('tech:vue', 'tech', 'Vue', 'Does the role use Vue?'),
    ('tech:nuxt', 'tech', 'Nuxt', 'Does the role use Nuxt?'),
    ('tech:svelte', 'tech', 'Svelte', 'Does the role use Svelte?'),
    ('tech:solidjs', 'tech', 'SolidJS', 'Does the role use SolidJS?'),
    ('tech:angular', 'tech', 'Angular', 'Does the role use Angular?'),
    ('tech:remix', 'tech', 'Remix', 'Does the role use Remix?'),
    ('tech:astro', 'tech', 'Astro', 'Does the role use Astro?'),
    ('tech:tailwind', 'tech', 'Tailwind', 'Does the role use Tailwind?'),
    ('tech:graphql', 'tech', 'GraphQL', 'Does the role use GraphQL?'),
    ('tech:grpc', 'tech', 'gRPC', 'Does the role use gRPC?'),
    ('tech:rest', 'tech', 'REST', 'Does the role use REST?'),
    ('tech:trpc', 'tech', 'tRPC', 'Does the role use tRPC?'),
    ('tech:django', 'tech', 'Django', 'Does the role use Django?'),
    ('tech:flask', 'tech', 'Flask', 'Does the role use Flask?'),
    ('tech:fastapi', 'tech', 'FastAPI', 'Does the role use FastAPI?'),
    ('tech:spring', 'tech', 'Spring', 'Does the role use Spring?'),
    ('tech:express', 'tech', 'Express', 'Does the role use Express?'),
    ('tech:nestjs', 'tech', 'NestJS', 'Does the role use NestJS?'),
    ('tech:phoenix', 'tech', 'Phoenix', 'Does the role use Phoenix?'),
    ('tech:postgres', 'tech', 'Postgres', 'Does the role use Postgres?'),
    ('tech:mysql', 'tech', 'MySQL', 'Does the role use MySQL?'),
    ('tech:sqlite', 'tech', 'SQLite', 'Does the role use SQLite?'),
    ('tech:mongodb', 'tech', 'MongoDB', 'Does the role use MongoDB?'),
    ('tech:redis', 'tech', 'Redis', 'Does the role use Redis?'),
    ('tech:valkey', 'tech', 'Valkey', 'Does the role use Valkey?'),
    ('tech:cassandra', 'tech', 'Cassandra', 'Does the role use Cassandra?'),
    ('tech:dynamodb', 'tech', 'DynamoDB', 'Does the role use DynamoDB?'),
    ('tech:clickhouse', 'tech', 'ClickHouse', 'Does the role use ClickHouse?'),
    ('tech:snowflake', 'tech', 'Snowflake', 'Does the role use Snowflake?'),
    ('tech:bigquery', 'tech', 'BigQuery', 'Does the role use BigQuery?'),
    ('tech:redshift', 'tech', 'Redshift', 'Does the role use Redshift?'),
    ('tech:elasticsearch', 'tech', 'Elasticsearch', 'Does the role use Elasticsearch?'),
    ('tech:opensearch', 'tech', 'OpenSearch', 'Does the role use OpenSearch?'),
    ('tech:cockroachdb', 'tech', 'CockroachDB', 'Does the role use CockroachDB?'),
    ('tech:neo4j', 'tech', 'Neo4j', 'Does the role use Neo4j?'),
    ('tech:kafka', 'tech', 'Kafka', 'Does the role use Kafka?'),
    ('tech:rabbitmq', 'tech', 'RabbitMQ', 'Does the role use RabbitMQ?'),
    ('tech:nats', 'tech', 'NATS', 'Does the role use NATS?'),
    ('tech:sqs', 'tech', 'SQS', 'Does the role use SQS?'),
    ('tech:pulsar', 'tech', 'Pulsar', 'Does the role use Pulsar?'),
    ('tech:temporal', 'tech', 'Temporal', 'Does the role use Temporal?'),
    ('tech:airflow', 'tech', 'Airflow', 'Does the role use Airflow?'),
    ('tech:dbt', 'tech', 'dbt', 'Does the role use dbt?'),
    ('tech:spark', 'tech', 'Spark', 'Does the role use Spark?'),
    ('tech:flink', 'tech', 'Flink', 'Does the role use Flink?'),
    ('tech:kubernetes', 'tech', 'Kubernetes', 'Does the role use Kubernetes?'),
    ('tech:docker', 'tech', 'Docker', 'Does the role use Docker?'),
    ('tech:terraform', 'tech', 'Terraform', 'Does the role use Terraform?'),
    ('tech:pulumi', 'tech', 'Pulumi', 'Does the role use Pulumi?'),
    ('tech:ansible', 'tech', 'Ansible', 'Does the role use Ansible?'),
    ('tech:helm', 'tech', 'Helm', 'Does the role use Helm?'),
    ('tech:argocd', 'tech', 'ArgoCD', 'Does the role use ArgoCD?'),
    ('tech:aws', 'tech', 'AWS', 'Does the role use AWS?'),
    ('tech:gcp', 'tech', 'GCP', 'Does the role use GCP?'),
    ('tech:azure', 'tech', 'Azure', 'Does the role use Azure?'),
    ('tech:cloudflare', 'tech', 'Cloudflare', 'Does the role use Cloudflare?'),
    ('tech:vercel', 'tech', 'Vercel', 'Does the role use Vercel?'),
    ('tech:fly-io', 'tech', 'Fly.io', 'Does the role use Fly.io?'),
    ('tech:linux', 'tech', 'Linux', 'Does the role use Linux?'),
    ('tech:nix', 'tech', 'Nix', 'Does the role use Nix?'),
    ('tech:bazel', 'tech', 'Bazel', 'Does the role use Bazel?'),
    ('tech:github-actions', 'tech', 'GitHub Actions', 'Does the role use GitHub Actions?'),
    ('tech:prometheus', 'tech', 'Prometheus', 'Does the role use Prometheus?'),
    ('tech:grafana', 'tech', 'Grafana', 'Does the role use Grafana?'),
    ('tech:opentelemetry', 'tech', 'OpenTelemetry', 'Does the role use OpenTelemetry?'),
    ('tech:datadog', 'tech', 'Datadog', 'Does the role use Datadog?'),
    ('tech:sentry', 'tech', 'Sentry', 'Does the role use Sentry?'),
    ('tech:pytorch', 'tech', 'PyTorch', 'Does the role use PyTorch?'),
    ('tech:tensorflow', 'tech', 'TensorFlow', 'Does the role use TensorFlow?'),
    ('tech:llms', 'tech', 'LLMs', 'Does the role use LLMs?'),
    ('tech:pandas', 'tech', 'Pandas', 'Does the role use Pandas?'),
    ('tech:webassembly', 'tech', 'WebAssembly', 'Does the role use WebAssembly?'),
    ('tech:webrtc', 'tech', 'WebRTC', 'Does the role use WebRTC?'),
    ('tech:ebpf', 'tech', 'eBPF', 'Does the role use eBPF?'),
    ('tech:solidity', 'tech', 'Solidity', 'Does the role use Solidity?'),
    ('tech:unity', 'tech', 'Unity', 'Does the role use Unity?'),
    ('role:backend', 'role', 'Backend', 'Is this primarily a Backend role?'),
    ('role:platform', 'role', 'Platform', 'Is this primarily a Platform role?'),
    ('role:infrastructure', 'role', 'Infrastructure', 'Is this primarily a Infrastructure role?'),
    ('role:sre', 'role', 'SRE', 'Is this primarily a SRE role?'),
    ('role:full-stack', 'role', 'Full-stack', 'Is this primarily a Full-stack role?'),
    ('role:frontend', 'role', 'Frontend', 'Is this primarily a Frontend role?'),
    ('role:mobile', 'role', 'Mobile', 'Is this primarily a Mobile role?'),
    ('role:data-engineering', 'role', 'Data engineering', 'Is this primarily a Data engineering role?'),
    ('role:ml-engineering', 'role', 'ML engineering', 'Is this primarily a ML engineering role?'),
    ('role:security', 'role', 'Security', 'Is this primarily a Security role?'),
    ('role:developer-experience', 'role', 'Developer experience', 'Is this primarily a Developer experience role?'),
    ('role:engineering-management', 'role', 'Engineering management', 'Is this primarily a Engineering management role?'),
    ('role:product-engineering', 'role', 'Product engineering', 'Is this a product engineering role: shipping user-facing features across the stack?'),
    ('domain:fintech', 'domain', 'fintech', 'Is the company''s main product or market fintech? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:payments', 'domain', 'payments', 'Is the company''s main product or market payments? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:devtools', 'domain', 'devtools', 'Is the company''s main product or market devtools? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:health', 'domain', 'health', 'Is the company''s main product or market health? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:climate', 'domain', 'climate', 'Is the company''s main product or market climate? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:energy', 'domain', 'energy', 'Is the company''s main product or market energy? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:crypto', 'domain', 'crypto', 'Is the company''s main product or market crypto? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:adtech', 'domain', 'adtech', 'Is the company''s main product or market adtech? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:agency', 'domain', 'agency', 'Is the company''s main product or market agency? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:ecommerce', 'domain', 'ecommerce', 'Is the company''s main product or market ecommerce? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:edtech', 'domain', 'edtech', 'Is the company''s main product or market edtech? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:gaming', 'domain', 'gaming', 'Is the company''s main product or market gaming? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:gambling', 'domain', 'gambling', 'Is the company''s main product or market gambling? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:defence', 'domain', 'defence', 'Is the company''s main product or market defence? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:govtech', 'domain', 'govtech', 'Is the company''s main product or market govtech? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:insurance', 'domain', 'insurance', 'Is the company''s main product or market insurance? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:logistics', 'domain', 'logistics', 'Is the company''s main product or market logistics? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:proptech', 'domain', 'proptech', 'Is the company''s main product or market proptech? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:legal', 'domain', 'legal', 'Is the company''s main product or market legal? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:media', 'domain', 'media', 'Is the company''s main product or market media? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:security', 'domain', 'security', 'Is the company''s main product or market security? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:ai-tooling', 'domain', 'AI tooling', 'Is the company''s main product or market AI tooling? Employee benefits, perks and clients'' industries don''t count.'),
    ('domain:recruitment', 'domain', 'recruitment', 'Is the company a recruitment or staffing agency, hiring on behalf of an unnamed client?'),
    ('work:remote', 'work', 'Remote', 'Is the role fully remote (not hybrid or office-based)?'),
    ('work:hybrid', 'work', 'Hybrid', 'Is the role hybrid, split between home and an office (not fully remote or fully onsite)?'),
    ('work:onsite', 'work', 'Onsite', 'Is the role fully onsite in an office (not remote or hybrid)?'),
    ('work:office_1', 'work', '1 office day/week', 'Does the role expect you in an office exactly 1 day a week? A range that includes 1, like "1-2 days", counts as yes.'),
    ('work:office_2', 'work', '2 office days/week', 'Does the role expect you in an office exactly 2 days a week? A range that includes 2, like "2-3 days", counts as yes.'),
    ('work:office_3', 'work', '3 office days/week', 'Does the role expect you in an office exactly 3 days a week? A range that includes 3, like "2-3 days", counts as yes.'),
    ('work:office_4plus', 'work', '4+ office days/week', 'Does the role expect you in an office 4 or more days a week? A range that reaches 4 or more, like "3-4 days", counts as yes.'),
    ('employment:permanent', 'employment', 'Permanent', 'Is the role a permanent, full-time employment contract (not contract, freelance or part-time)?'),
    ('employment:contract', 'employment', 'Contract', 'Is the role a fixed-term or day-rate contract, (not permanent)?'),
    ('employment:part_time', 'employment', 'Part-time', 'Is the role part-time (not full-time)?'),
    ('stage:seed', 'stage', 'Seed', 'Is the company at Seed stage (not pre-seed, Series A or later, or public)?'),
    ('stage:series_a', 'stage', 'Series A', 'Is the company at Series A stage (not Seed, Series B or later, or public)?'),
    ('stage:series_b', 'stage', 'Series B', 'Is the company at Series B stage (not Series A, Series C or later, or public)?'),
    ('stage:series_c_plus', 'stage', 'Series C+', 'Is the company at Series C or later stage (not Seed, Series A or B, or public)?'),
    ('stage:public', 'stage', 'Public', 'Is the company publicly listed (not a private or venture-backed company)?'),
    ('size:startup', 'size', 'Startup', 'Does the company have under 50 employees (not a scale-up, large or enterprise company)?'),
    ('size:scaleup', 'size', 'Scale-up', 'Does the company have 50 to 500 employees (not under 50, or over 500)?'),
    ('size:large', 'size', 'Large', 'Does the company have 500 to 5,000 employees (not under 500, or over 5,000)?'),
    ('size:enterprise', 'size', 'Enterprise', 'Does the company have over 5,000 employees (not 5,000 or fewer)?'),
    ('seniority:junior', 'seniority', 'Junior', 'Weighing title, required years and scope together, is the role Junior level (Junior or Graduate, about 0-2 years, works under guidance)?'),
    ('seniority:mid', 'seniority', 'Mid', 'Weighing title, required years and scope together, is the role Mid level (about 2-5 years, delivers independently, no Senior or higher title)?'),
    ('seniority:senior', 'seniority', 'Senior', 'Weighing title, required years and scope together, is the role Senior level (Senior title or about 5-8 years, owns features and mentors, not leading a team)?'),
    ('seniority:lead_staff', 'seniority', 'Lead / Staff', 'Weighing title, required years and scope together, is the role Lead or Staff level (Lead, Staff or Tech Lead, about 8+ years, leads a team or owns cross-team technical scope)?'),
    ('seniority:principal_head', 'seniority', 'Principal / Head', 'Weighing title, required years and scope together, is the role Principal or Head level (Principal, Head of or Director, organisation-wide scope or manages managers)?') ON CONFLICT (id) DO NOTHING;
