/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthOverviewRouteImport } from './routes/_auth/overview'
import { Route as AuthJobsRouteImport } from './routes/_auth/jobs'
import { Route as AuthApplicationsRouteImport } from './routes/_auth/applications'
import { Route as AuthSettingsStatusesRouteImport } from './routes/_auth/settings/statuses'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOverviewRoute = AuthOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthRoute,
} as any)
const AuthJobsRoute = AuthJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApplicationsRoute = AuthApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsStatusesRoute = AuthSettingsStatusesRouteImport.update({
  id: '/statuses',
  path: '/statuses',
  getParentRoute: () => AuthSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/applications': typeof AuthApplicationsRoute
  '/jobs': typeof AuthJobsRoute
  '/overview': typeof AuthOverviewRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/settings/statuses': typeof AuthSettingsStatusesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/applications': typeof AuthApplicationsRoute
  '/jobs': typeof AuthJobsRoute
  '/overview': typeof AuthOverviewRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/settings/statuses': typeof AuthSettingsStatusesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/applications': typeof AuthApplicationsRoute
  '/_auth/jobs': typeof AuthJobsRoute
  '/_auth/overview': typeof AuthOverviewRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/settings/statuses': typeof AuthSettingsStatusesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/applications'
    | '/jobs'
    | '/overview'
    | '/settings'
    | '/settings/statuses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/applications'
    | '/jobs'
    | '/overview'
    | '/settings'
    | '/settings/statuses'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/applications'
    | '/_auth/jobs'
    | '/_auth/overview'
    | '/_auth/settings'
    | '/_auth/settings/statuses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/overview': {
      id: '/_auth/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthOverviewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/jobs': {
      id: '/_auth/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthJobsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/applications': {
      id: '/_auth/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthApplicationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/statuses': {
      id: '/_auth/settings/statuses'
      path: '/statuses'
      fullPath: '/settings/statuses'
      preLoaderRoute: typeof AuthSettingsStatusesRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
  }
}

interface AuthSettingsRouteChildren {
  AuthSettingsStatusesRoute: typeof AuthSettingsStatusesRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsStatusesRoute: AuthSettingsStatusesRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthApplicationsRoute: typeof AuthApplicationsRoute
  AuthJobsRoute: typeof AuthJobsRoute
  AuthOverviewRoute: typeof AuthOverviewRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthApplicationsRoute: AuthApplicationsRoute,
  AuthJobsRoute: AuthJobsRoute,
  AuthOverviewRoute: AuthOverviewRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
