/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthOverviewRouteImport } from './routes/_auth/overview'
import { Route as AuthJobsRouteImport } from './routes/_auth/jobs'
import { Route as AuthInsightsRouteImport } from './routes/_auth/insights'
import { Route as AuthExperienceRouteImport } from './routes/_auth/experience'
import { Route as AuthCvTemplatesRouteImport } from './routes/_auth/cv-templates'
import { Route as AuthCompaniesRouteImport } from './routes/_auth/companies'
import { Route as AuthApplicationsRouteImport } from './routes/_auth/applications'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthSettingsUsageRouteImport } from './routes/_auth/settings/usage'
import { Route as AuthSettingsStatusesRouteImport } from './routes/_auth/settings/statuses'
import { Route as AuthSettingsSearchesRouteImport } from './routes/_auth/settings/searches'
import { Route as AuthSettingsScoringRouteImport } from './routes/_auth/settings/scoring'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthSettingsIntegrationsRouteImport } from './routes/_auth/settings/integrations'
import { Route as AuthSettingsAiRouteImport } from './routes/_auth/settings/ai'
import { Route as AuthJobsIdRouteImport } from './routes/_auth/jobs_.$id'
import { Route as AuthCompaniesNewRouteImport } from './routes/_auth/companies_.new'
import { Route as AuthCompaniesIdRouteImport } from './routes/_auth/companies_.$id'
import { Route as AuthSettingsScoringIndexRouteImport } from './routes/_auth/settings/scoring/index'
import { Route as AuthTailoringDraftsIdRouteImport } from './routes/_auth/tailoring.drafts.$id'
import { Route as AuthSettingsScoringSectionRouteImport } from './routes/_auth/settings/scoring/$section'
import { Route as AuthJobsIdTailorRouteImport } from './routes/_auth/jobs_.$id_.tailor'
import { Route as AuthCvTemplatesDocIdTabIdRouteImport } from './routes/_auth/cv-templates_.$docId.$tabId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOverviewRoute = AuthOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthRoute,
} as any)
const AuthJobsRoute = AuthJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInsightsRoute = AuthInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExperienceRoute = AuthExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCvTemplatesRoute = AuthCvTemplatesRouteImport.update({
  id: '/cv-templates',
  path: '/cv-templates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompaniesRoute = AuthCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApplicationsRoute = AuthApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsUsageRoute = AuthSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsStatusesRoute = AuthSettingsStatusesRouteImport.update({
  id: '/statuses',
  path: '/statuses',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsSearchesRoute = AuthSettingsSearchesRouteImport.update({
  id: '/searches',
  path: '/searches',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsScoringRoute = AuthSettingsScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsIntegrationsRoute =
  AuthSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsAiRoute = AuthSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthJobsIdRoute = AuthJobsIdRouteImport.update({
  id: '/jobs_/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompaniesNewRoute = AuthCompaniesNewRouteImport.update({
  id: '/companies_/new',
  path: '/companies/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompaniesIdRoute = AuthCompaniesIdRouteImport.update({
  id: '/companies_/$id',
  path: '/companies/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsScoringIndexRoute =
  AuthSettingsScoringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSettingsScoringRoute,
  } as any)
const AuthTailoringDraftsIdRoute = AuthTailoringDraftsIdRouteImport.update({
  id: '/tailoring/drafts/$id',
  path: '/tailoring/drafts/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsScoringSectionRoute =
  AuthSettingsScoringSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthSettingsScoringRoute,
  } as any)
const AuthJobsIdTailorRoute = AuthJobsIdTailorRouteImport.update({
  id: '/jobs_/$id_/tailor',
  path: '/jobs/$id/tailor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCvTemplatesDocIdTabIdRoute =
  AuthCvTemplatesDocIdTabIdRouteImport.update({
    id: '/cv-templates_/$docId/$tabId',
    path: '/cv-templates/$docId/$tabId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/applications': typeof AuthApplicationsRoute
  '/companies': typeof AuthCompaniesRoute
  '/cv-templates': typeof AuthCvTemplatesRoute
  '/experience': typeof AuthExperienceRoute
  '/insights': typeof AuthInsightsRoute
  '/jobs': typeof AuthJobsRoute
  '/overview': typeof AuthOverviewRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/companies/$id': typeof AuthCompaniesIdRoute
  '/companies/new': typeof AuthCompaniesNewRoute
  '/jobs/$id': typeof AuthJobsIdRoute
  '/settings/ai': typeof AuthSettingsAiRoute
  '/settings/integrations': typeof AuthSettingsIntegrationsRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/scoring': typeof AuthSettingsScoringRouteWithChildren
  '/settings/searches': typeof AuthSettingsSearchesRoute
  '/settings/statuses': typeof AuthSettingsStatusesRoute
  '/settings/usage': typeof AuthSettingsUsageRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/cv-templates/$docId/$tabId': typeof AuthCvTemplatesDocIdTabIdRoute
  '/jobs/$id/tailor': typeof AuthJobsIdTailorRoute
  '/settings/scoring/$section': typeof AuthSettingsScoringSectionRoute
  '/tailoring/drafts/$id': typeof AuthTailoringDraftsIdRoute
  '/settings/scoring/': typeof AuthSettingsScoringIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/applications': typeof AuthApplicationsRoute
  '/companies': typeof AuthCompaniesRoute
  '/cv-templates': typeof AuthCvTemplatesRoute
  '/experience': typeof AuthExperienceRoute
  '/insights': typeof AuthInsightsRoute
  '/jobs': typeof AuthJobsRoute
  '/overview': typeof AuthOverviewRoute
  '/companies/$id': typeof AuthCompaniesIdRoute
  '/companies/new': typeof AuthCompaniesNewRoute
  '/jobs/$id': typeof AuthJobsIdRoute
  '/settings/ai': typeof AuthSettingsAiRoute
  '/settings/integrations': typeof AuthSettingsIntegrationsRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/searches': typeof AuthSettingsSearchesRoute
  '/settings/statuses': typeof AuthSettingsStatusesRoute
  '/settings/usage': typeof AuthSettingsUsageRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/cv-templates/$docId/$tabId': typeof AuthCvTemplatesDocIdTabIdRoute
  '/jobs/$id/tailor': typeof AuthJobsIdTailorRoute
  '/settings/scoring/$section': typeof AuthSettingsScoringSectionRoute
  '/tailoring/drafts/$id': typeof AuthTailoringDraftsIdRoute
  '/settings/scoring': typeof AuthSettingsScoringIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/applications': typeof AuthApplicationsRoute
  '/_auth/companies': typeof AuthCompaniesRoute
  '/_auth/cv-templates': typeof AuthCvTemplatesRoute
  '/_auth/experience': typeof AuthExperienceRoute
  '/_auth/insights': typeof AuthInsightsRoute
  '/_auth/jobs': typeof AuthJobsRoute
  '/_auth/overview': typeof AuthOverviewRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/companies_/$id': typeof AuthCompaniesIdRoute
  '/_auth/companies_/new': typeof AuthCompaniesNewRoute
  '/_auth/jobs_/$id': typeof AuthJobsIdRoute
  '/_auth/settings/ai': typeof AuthSettingsAiRoute
  '/_auth/settings/integrations': typeof AuthSettingsIntegrationsRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/scoring': typeof AuthSettingsScoringRouteWithChildren
  '/_auth/settings/searches': typeof AuthSettingsSearchesRoute
  '/_auth/settings/statuses': typeof AuthSettingsStatusesRoute
  '/_auth/settings/usage': typeof AuthSettingsUsageRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/cv-templates_/$docId/$tabId': typeof AuthCvTemplatesDocIdTabIdRoute
  '/_auth/jobs_/$id_/tailor': typeof AuthJobsIdTailorRoute
  '/_auth/settings/scoring/$section': typeof AuthSettingsScoringSectionRoute
  '/_auth/tailoring/drafts/$id': typeof AuthTailoringDraftsIdRoute
  '/_auth/settings/scoring/': typeof AuthSettingsScoringIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/applications'
    | '/companies'
    | '/cv-templates'
    | '/experience'
    | '/insights'
    | '/jobs'
    | '/overview'
    | '/settings'
    | '/companies/$id'
    | '/companies/new'
    | '/jobs/$id'
    | '/settings/ai'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/scoring'
    | '/settings/searches'
    | '/settings/statuses'
    | '/settings/usage'
    | '/settings/'
    | '/cv-templates/$docId/$tabId'
    | '/jobs/$id/tailor'
    | '/settings/scoring/$section'
    | '/tailoring/drafts/$id'
    | '/settings/scoring/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/applications'
    | '/companies'
    | '/cv-templates'
    | '/experience'
    | '/insights'
    | '/jobs'
    | '/overview'
    | '/companies/$id'
    | '/companies/new'
    | '/jobs/$id'
    | '/settings/ai'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/searches'
    | '/settings/statuses'
    | '/settings/usage'
    | '/settings'
    | '/cv-templates/$docId/$tabId'
    | '/jobs/$id/tailor'
    | '/settings/scoring/$section'
    | '/tailoring/drafts/$id'
    | '/settings/scoring'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/applications'
    | '/_auth/companies'
    | '/_auth/cv-templates'
    | '/_auth/experience'
    | '/_auth/insights'
    | '/_auth/jobs'
    | '/_auth/overview'
    | '/_auth/settings'
    | '/_auth/companies_/$id'
    | '/_auth/companies_/new'
    | '/_auth/jobs_/$id'
    | '/_auth/settings/ai'
    | '/_auth/settings/integrations'
    | '/_auth/settings/profile'
    | '/_auth/settings/scoring'
    | '/_auth/settings/searches'
    | '/_auth/settings/statuses'
    | '/_auth/settings/usage'
    | '/_auth/settings/'
    | '/_auth/cv-templates_/$docId/$tabId'
    | '/_auth/jobs_/$id_/tailor'
    | '/_auth/settings/scoring/$section'
    | '/_auth/tailoring/drafts/$id'
    | '/_auth/settings/scoring/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/overview': {
      id: '/_auth/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthOverviewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/jobs': {
      id: '/_auth/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthJobsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/insights': {
      id: '/_auth/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthInsightsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/experience': {
      id: '/_auth/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof AuthExperienceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cv-templates': {
      id: '/_auth/cv-templates'
      path: '/cv-templates'
      fullPath: '/cv-templates'
      preLoaderRoute: typeof AuthCvTemplatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/companies': {
      id: '/_auth/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthCompaniesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/applications': {
      id: '/_auth/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthApplicationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/usage': {
      id: '/_auth/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof AuthSettingsUsageRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/statuses': {
      id: '/_auth/settings/statuses'
      path: '/statuses'
      fullPath: '/settings/statuses'
      preLoaderRoute: typeof AuthSettingsStatusesRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/searches': {
      id: '/_auth/settings/searches'
      path: '/searches'
      fullPath: '/settings/searches'
      preLoaderRoute: typeof AuthSettingsSearchesRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/scoring': {
      id: '/_auth/settings/scoring'
      path: '/scoring'
      fullPath: '/settings/scoring'
      preLoaderRoute: typeof AuthSettingsScoringRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/integrations': {
      id: '/_auth/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthSettingsIntegrationsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/ai': {
      id: '/_auth/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthSettingsAiRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/jobs_/$id': {
      id: '/_auth/jobs_/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthJobsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/companies_/new': {
      id: '/_auth/companies_/new'
      path: '/companies/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof AuthCompaniesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/companies_/$id': {
      id: '/_auth/companies_/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthCompaniesIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/scoring/': {
      id: '/_auth/settings/scoring/'
      path: '/'
      fullPath: '/settings/scoring/'
      preLoaderRoute: typeof AuthSettingsScoringIndexRouteImport
      parentRoute: typeof AuthSettingsScoringRoute
    }
    '/_auth/tailoring/drafts/$id': {
      id: '/_auth/tailoring/drafts/$id'
      path: '/tailoring/drafts/$id'
      fullPath: '/tailoring/drafts/$id'
      preLoaderRoute: typeof AuthTailoringDraftsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/scoring/$section': {
      id: '/_auth/settings/scoring/$section'
      path: '/$section'
      fullPath: '/settings/scoring/$section'
      preLoaderRoute: typeof AuthSettingsScoringSectionRouteImport
      parentRoute: typeof AuthSettingsScoringRoute
    }
    '/_auth/jobs_/$id_/tailor': {
      id: '/_auth/jobs_/$id_/tailor'
      path: '/jobs/$id/tailor'
      fullPath: '/jobs/$id/tailor'
      preLoaderRoute: typeof AuthJobsIdTailorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cv-templates_/$docId/$tabId': {
      id: '/_auth/cv-templates_/$docId/$tabId'
      path: '/cv-templates/$docId/$tabId'
      fullPath: '/cv-templates/$docId/$tabId'
      preLoaderRoute: typeof AuthCvTemplatesDocIdTabIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthSettingsScoringRouteChildren {
  AuthSettingsScoringSectionRoute: typeof AuthSettingsScoringSectionRoute
  AuthSettingsScoringIndexRoute: typeof AuthSettingsScoringIndexRoute
}

const AuthSettingsScoringRouteChildren: AuthSettingsScoringRouteChildren = {
  AuthSettingsScoringSectionRoute: AuthSettingsScoringSectionRoute,
  AuthSettingsScoringIndexRoute: AuthSettingsScoringIndexRoute,
}

const AuthSettingsScoringRouteWithChildren =
  AuthSettingsScoringRoute._addFileChildren(AuthSettingsScoringRouteChildren)

interface AuthSettingsRouteChildren {
  AuthSettingsAiRoute: typeof AuthSettingsAiRoute
  AuthSettingsIntegrationsRoute: typeof AuthSettingsIntegrationsRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsScoringRoute: typeof AuthSettingsScoringRouteWithChildren
  AuthSettingsSearchesRoute: typeof AuthSettingsSearchesRoute
  AuthSettingsStatusesRoute: typeof AuthSettingsStatusesRoute
  AuthSettingsUsageRoute: typeof AuthSettingsUsageRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsAiRoute: AuthSettingsAiRoute,
  AuthSettingsIntegrationsRoute: AuthSettingsIntegrationsRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsScoringRoute: AuthSettingsScoringRouteWithChildren,
  AuthSettingsSearchesRoute: AuthSettingsSearchesRoute,
  AuthSettingsStatusesRoute: AuthSettingsStatusesRoute,
  AuthSettingsUsageRoute: AuthSettingsUsageRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthApplicationsRoute: typeof AuthApplicationsRoute
  AuthCompaniesRoute: typeof AuthCompaniesRoute
  AuthCvTemplatesRoute: typeof AuthCvTemplatesRoute
  AuthExperienceRoute: typeof AuthExperienceRoute
  AuthInsightsRoute: typeof AuthInsightsRoute
  AuthJobsRoute: typeof AuthJobsRoute
  AuthOverviewRoute: typeof AuthOverviewRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthCompaniesIdRoute: typeof AuthCompaniesIdRoute
  AuthCompaniesNewRoute: typeof AuthCompaniesNewRoute
  AuthJobsIdRoute: typeof AuthJobsIdRoute
  AuthCvTemplatesDocIdTabIdRoute: typeof AuthCvTemplatesDocIdTabIdRoute
  AuthJobsIdTailorRoute: typeof AuthJobsIdTailorRoute
  AuthTailoringDraftsIdRoute: typeof AuthTailoringDraftsIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthApplicationsRoute: AuthApplicationsRoute,
  AuthCompaniesRoute: AuthCompaniesRoute,
  AuthCvTemplatesRoute: AuthCvTemplatesRoute,
  AuthExperienceRoute: AuthExperienceRoute,
  AuthInsightsRoute: AuthInsightsRoute,
  AuthJobsRoute: AuthJobsRoute,
  AuthOverviewRoute: AuthOverviewRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthCompaniesIdRoute: AuthCompaniesIdRoute,
  AuthCompaniesNewRoute: AuthCompaniesNewRoute,
  AuthJobsIdRoute: AuthJobsIdRoute,
  AuthCvTemplatesDocIdTabIdRoute: AuthCvTemplatesDocIdTabIdRoute,
  AuthJobsIdTailorRoute: AuthJobsIdTailorRoute,
  AuthTailoringDraftsIdRoute: AuthTailoringDraftsIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
